### ISSUE TITLE
Button "Add IP Addresses" in ipam/ip-ranges/<pk>/ip-addresses/ page is disappear

### ISSUE THREAD

**Issue by KuanTing0612** [netbox-community/netbox-docker#1005]
### Current Behavior

After updating docker image to VERSION-v3.4-2.4.0, button "Add IP Addresses" in iprange-ipaddresses page is disappear
![image](https://user-images.githubusercontent.com/106938598/236103540-9abcfeba-7245-4a99-ac4a-ff58b55c7bc2.png)

I tried to figure out what happened from the frontend code and found that active_tab == 'ip-addresses' contains in if condition as following picture
![image](https://user-images.githubusercontent.com/106938598/236105648-f1784290-16a2-4d9f-9346-6ab0afed2050.png)
It seems that active_tab == 'ip-addresses' does not be written in ipaddress views.  
So after I remove this code, the button "Add Ip Addresses" is back and also be able to work as older version.

### Expected Behavior

![image](https://user-images.githubusercontent.com/106938598/236103650-82725536-5465-48b7-a7a8-fa9d9d7e76e4.png)

### Docker Compose Version

Docker Compose version v2.2.2

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:04:24 2022
 OS/Arch:           linux/amd64
 Context:           default
```

### The git Revision

39c7de4af41703108f8b3af7274bc65813c41799

### The git Status

```text
no changes added to commit (use "git add" and/or "git commit -a")
```

### Startup Command

docker-compose up

### NetBox Logs

```text
2023/05/04 02:35:04 [info] 398662#398662 "netbox" application started
netbox_1               | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1               | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1               | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox_1               | 🧬 loaded config '/etc/netbox/config/plugins.py
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - 8100:8080
```

**Comment by tobiasge** [comment]
Version `v3.4-2.4.0` is not a current version. Please check if you have the same error in `v3.5-2.6.1`.
From the description I don't think this is a problem with the Docker image.
