### ISSUE TITLE
Obsolete 'Quickstart' documentation on Docker Hub and Quay.io

### ISSUE THREAD

**Issue by 5bentz** [netbox-community/netbox-docker#1016]
### Current Behavior

Commit 3e2bf7ec934 "Don't create superuser with default credentials" changed the default behavior and the necessary steps to have a netbox container up and running.

These changes have not been propagated to the other registries:  [Docker Hub](https://hub.docker.com/r/netboxcommunity/netbox/) and [Quay.io](https://quay.io/repository/netboxcommunity/netbox). They are still referring to the `admin` superuser.

Thus, a user following these instructions cannot login with the provided credentials (admin/admin).

### Expected Behavior

I may suggest to fix the documentation on [Docker Hub](https://hub.docker.com/r/netboxcommunity/netbox/) and [Quay.io](https://quay.io/repository/netboxcommunity/netbox).

Or to avoid these issues, the best might be to replace the duplicated docs with a link to the reference documentation [here on GitHub](https://github.com/netbox-community/netbox-docker#readme).

### Docker Compose Version

-

### Docker Version

```text
-
```

### The git Revision

22486fefb5c4cc326bd091abeac5314eb7acd37f

### The git Status

```text
-
```

### Startup Command

-

### NetBox Logs

```text
-
```

### Content of docker-compose.override.yml

```yaml
-
```

**Comment by tobiasge** [comment]
Description was updated in both registries.
