### ISSUE TITLE
Monitoring docs should change 

### ISSUE THREAD

**Issue by amirgilan** [netbox-community/netbox-docker#1020]
### Desired Behavior

In a wiki page for monitoring "https://github.com/netbox-community/netbox-docker/wiki/Monitoring" 
we see depends on service 'nginx' inside "nginx-exporter" which is undefined on main docker-compose.override.yml file.

### Contrast to Current Behavior

I think we should ignore this from monitoring services and change the wiki page.

**Comment by cimnine** [comment]
It's a community wiki. Anybody discovering better practices, outdated content or errors is asked to adjust and enhance the wiki.
