### ISSUE TITLE
unknown option --state (unitd)

### ISSUE THREAD

**Issue by aauerswald** [netbox-community/netbox-docker#1023]
### Current Behavior

After updating to version 3.5.3 Netbox will not start.

I get the following message from launch-netbox.sh (line 54)

unknown option "--state", try "unitd -h" for available options 

### Expected Behavior

Netbox will start. again .....

### Docker Compose Version

-

### Docker Version

```text
-
```

### The git Revision

-

### The git Status

```text
-
```

### Startup Command

-

### NetBox Logs

```text
🧬 loaded config '/etc/netbox/config/configuration.py'2023-06-05T15:43:21.230350244+02:00 
🧬 loaded config '/etc/netbox/config/extra.py'2023-06-05T15:43:21.230550447+02:00 
🧬 loaded config '/etc/netbox/config/logging.py'2023-06-05T15:43:21.230649217+02:00 
🧬 loaded config '/etc/netbox/config/plugins.py'2023-06-05T15:43:21.230754047+02:00 
💡 Superuser Username: admin, E-Mail: admin@example.com
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
✅ Initialisation is done.
⏳ Waiting for control socket to be created... (1/10)
unknown option "--state", try "unitd -h" for available options
```

### Content of docker-compose.override.yml

```yaml
-
```

**Comment by tobiasge** [comment]
The newest version of Nginx Unit changed some parameter names, thats where this error is coming from.
But the images build by our workflows don't use that version, as of now. A change for that is in the develop branch, but not yet released.

Which image are you using?

**Comment by aauerswald** [comment]
Hello, sorry the issue was home made. I used "netboxcommunity/netbox:v3.5.3" but during build  process I ran "apt-get update && apt-get upgrade", so I got the newest version of nginx. I removed the step and now it works!
