### ISSUE TITLE
June 22 2023 release failures

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox-docker#1025]
### Current Behavior

Today’s release action failed. https://github.com/netbox-community/netbox-docker/actions/runs/5330568264

GitHub container registry push failed and it seems dockerhub pushed 3.5.4, but did not tag it as latest.

### Expected Behavior

Push to all container registries and tag the latest netbox build with latest.

### Docker Compose Version

N/A

### Docker Version

```text
N/A
```

### The git Revision

N/A

### The git Status

```text
N/A
```

### Startup Command

N/A

### NetBox Logs

```text
N/A
```

### Content of docker-compose.override.yml

```yaml
N/A
```

**Comment by lucatortiglione** [comment]
it's working now

**Comment by tobiasge** [comment]
Looks like temporary problem with the push. I will close this for now.
