### ISSUE TITLE
Images for v3.5.5 - 2023-07-06 not build

### ISSUE THREAD

**Issue by Delta1977** [netbox-community/netbox-docker#1028]
### Current Behavior

No images for v3.5.5 - 2023-07-06 on Dockerhub / last Images are 3 day's old

### Expected Behavior

Images for v3.5.5 - 2023-07-06

### Docker Compose Version

.

### Docker Version

```text
.
```

### The git Revision

.

### The git Status

```text
.
```

### Startup Command

.

### NetBox Logs

```text
.
```

### Content of docker-compose.override.yml

```yaml
.
```

**Comment by tobiasge** [comment]
The problem is tracked in this issue: https://github.com/netbox-community/netbox/issues/13116

**Comment by Delta1977** [comment]
?? https://github.com/netbox-community/netbox/issues/13116 is for "Netbox won't start with empty database" ??

**Comment by tobiasge** [comment]
Yes, that is the reason the tests are failing. And because of that, the images aren't pushed into the registries.
