### ISSUE TITLE
Please add Height (U) units in the devices dashboard

### ISSUE THREAD

**Issue by csetarun2** [netbox-community/netbox-docker#1031]
### Desired Behavior

Devices dashboard should contain the Height (U) units as well

### Contrast to Current Behavior

na

### Required Changes

add the required logic in the code

### Discussion: Benefits and Drawbacks

it will be easy for us to check how many units its consuming there itself, instead checking device height in from the device type itself.

**Comment by csetarun2** [comment]
can you please check this option , please add Height column in the devices info section.
![height](https://github.com/netbox-community/netbox-docker/assets/21236859/bfb2fcd9-1c13-4d7a-82fc-375173257608)

**Comment by tobiasge** [comment]
This is not an issue with the Docker image.
