### ISSUE TITLE
Loading Script Issue

### ISSUE THREAD

**Issue by SirHardware** [netbox-community/netbox-docker#1055]
So I opened an Issue in the Netbox Repo but there it was blocked because I used a Containerized Setup.
See: https://github.com/netbox-community/netbox/issues/13496
### NetBox version

v3.5.8

### Python version

3.10

### Steps to Reproduce

1. Containerized Netbox Installation
2. Add Git Datasource
3. Add Script from Git Datasource (with Autosync enabled)
4. Make Changes to Script via Git
5. Sync Datasource
6. Script can't be loaded
![image](https://github.com/netbox-community/netbox/assets/58984793/c268bcb7-3694-4d72-8be6-83813fcbb78b)
7. If error doesn't occur repeat steps 4 and 5 until it does

### Expected Behavior

The Script in Netbox gets updated

### Observed Behavior

The Scipt can't be loaded und thus not executed

In the Filesystem the Script is correct with the updated content

**Comment by tobiasge** [comment]
Could you enable logging and provide more information?

**Comment by SirHardware** [comment]
Here are the logs of the Netbox and the Netbox Worker Container
[netbox.log](https://github.com/netbox-community/netbox-docker/files/12370351/netbox.log)
[netbox-worker.log](https://github.com/netbox-community/netbox-docker/files/12370352/netbox-worker.log)

**Comment by FliesLikeABrick** [comment]
This occurs, amongst other reasons, if the script has a compile-time syntax error in it.  Have you tried running the script with python on the command line just to make sure it parses completely/correctly?

**Comment by SirHardware** [comment]
Yeah, that was the error.
Thank you for your time.
