### ISSUE TITLE
Restart Policy in the YAML?

### ISSUE THREAD

**Issue by Jadrie** [netbox-community/netbox-docker#1175]
### Desired Behavior

Would it be possible to add a restart policy to the docker compose yaml?

### Contrast to Current Behavior

presently there is no line in the docker-compose for restarting.

### Required Changes

add the following line to each service-
restart: unless-stopped

### Discussion: Benefits and Drawbacks

container will automatically restart if it's ever not running, if say, the server reboots.

**Comment by tobiasge** [comment]
You can set the restart policy in the override file.
