### ISSUE TITLE
Copying of Admin->Authentication->Permissions

### ISSUE THREAD

**Issue by Dominik9798** [netbox-community/netbox-docker#1176]
### Desired Behavior

At the moment there is no option to copy an existing authorization with all set rights.

### Contrast to Current Behavior

I have to copy it manually

### Required Changes

Add a button and function "clone" on Admin/Authentication/Permission

### Discussion: Benefits and Drawbacks

Simpler granting of authorizations

**Comment by tobiasge** [comment]
This would need to be a FR for Netbox and not the Docker image.
