### ISSUE TITLE
manage.py has no rqworker subcommand

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [netbox-community/netbox-docker#127]
## Current Behavior

netbox-worker exiting

```
Attaching to netbox-docker_netbox-worker_1
ESC[36mnetbox-worker_1  |ESC[0m Traceback (most recent call last):
ESC[36mnetbox-worker_1  |ESC[0m   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 204, in fetch_command
ESC[36mnetbox-worker_1  |ESC[0m     app_name = commands[subcommand]
ESC[36mnetbox-worker_1  |ESC[0m KeyError: 'rqworker'


$ docker-compose exec netbox /bin/bash
bash-4.4# ./manage.py 

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    runserver
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver
Note that only Django core commands are listed as settings are not properly configured (error: Configuration file is not present. Please define netbox/netbox/configuration.py per the documentation.).

```

**Comment by cimnine** [comment]
Thank you for your report. Please fill in all the details [from the template](https://github.com/netbox-community/netbox-docker/blob/master/.github/issue_template.md).

**Comment by cimnine** [comment]
I have not heard back after almost a week so I'm going to close this issue.

**Comment by sbibow** [comment]
I got the same error when trying to get netbox to run on Kubernetes. I am using the official `netboxcommunity/netbox:latest` image for both the main netbox image and the netbox-worker.
When the container starts it just outputs the following:

```
Unknown command: 'rqworker'
Type 'manage.py help' for usage.
```

Conversely when using the docker-compose locally it is working. Is there a volume mount that contains that command?

**Comment by cimnine** [comment]
That command is not available if you didn't define `WEBHOOKS_ENABLED=true`. If your problem persists, please open a new issue instead of hijacking this one.
