### ISSUE TITLE
Add In ui_editable and ui_visible To Custom_Fields.yml

### ISSUE THREAD

**Issue by mr1716** [netbox-community/netbox-docker#1282]
### Desired Behavior

New Custom Field Values were added, ui_editable and ui_visible. It would be great to have them added into the usable custom fields.yml file

### Contrast to Current Behavior

Doesnt have the ability to set this currently, so it defaults to Visible

**Comment by cimnine** [comment]
Please refer to the netbox-initializer project. Initializers are no longer part of the netbox-docker project.
