### ISSUE TITLE
Docker image is not available for version 3.0

### ISSUE THREAD

**Issue by jonlarsdizparc** [netbox-community/netbox-docker#1302]
### Current Behavior

Version specified in the docker-compose manifest does not exist in Docker Hub:
`docker.io/netboxcommunity/netbox:${VERSION-v4.1-3.0.0}`

### Expected Behavior

N/A

### Docker Compose Version

N/A

### Docker Version

```text
N/A
```

### The git Revision

N/A

### The git Status

```text
N/A
```

### Startup Command

N/A

### NetBox Logs

```text
N/A
```

### Content of docker-compose.override.yml

```yaml
N/A
```

**Comment by tobiasge** [comment]
See: https://github.com/netbox-community/netbox-docker/issues/1300
