### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [netbox-community/netbox-docker#132]
## Current Behavior

docker network is created without IPv6 networking (default for docker), should update docker-compose.yml to enable IPv6 networking support

## Expected Behavior

netbox can reach devices via IPv6

## Debug Information

```
docker network inspect netbox-docker_default
...
        "EnableIPv6": false,                      
        "IPAM": {                              
            "Driver": "default", 
            "Options": null,
            "Config": [                                                          
                {                               
                    "Subnet": "172.18.0.0/16",                                                                                                                                            
                    "Gateway": "172.18.0.1"                       
                }                              
            ]                           
        },                      
...

**Comment by cimnine** [comment]
Thank you for this feature request. Please feel free [to submit a PR][pr] if you like.

[pr]: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by cimnine** [comment]
I will close this, as ipv6 is currently not supported in `docker-compose.yml` files with version 3: https://docs.docker.com/compose/compose-file/#enable_ipv6

Feel free to re-open this issue again once the support becomes available.
