### ISSUE TITLE
update filtering and sorting of objects (dcim - racks, locations, 

### ISSUE THREAD

**Issue by sharkbait411** [netbox-community/netbox-docker#1325]
### Desired Behavior

We have a deployed containerized instance of netbox, and have built out and extensive site/location/rack inventory. When we go to use filtering or look at elevations, if we have racks assets with the following (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12), the filter list, or elevation view will showcase the racks like this instead: (A1, A10, A11, A12, A2, A3, A4, A5, A7, A8, A9)
we are looking to see if we can get a "natural sorting" option added to the admin settings, that we could turn on, in order to get the proper natural listing (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12). Totally get that NetBox is currently sorting lexicographically by default. Just looking to see if we can get an updated sorting

### Contrast to Current Behavior

the current behavior is sorting lexicographically by default

### Required Changes

would love to see this is a toggle admin option.

### Discussion: Benefits and Drawbacks

na

**Comment by cimnine** [comment]
I believe you have to request this feature in the upstream NetBox project. This project only concerns itself with the containerization of NetBox.
