### ISSUE TITLE
docker tag latest not "latest"

### ISSUE THREAD

**Issue by TakeMeNL** [netbox-community/netbox-docker#138]
The current `netboxcommunity/netbox:latest` is still tagged as something (can't fiqure out that it's tagged?)
While v2.5.13/v2.5 should also be tagged latest.

Tag | SHA256
--- | ------
latest|![#f03c15](https://placehold.it/15/f03c15/000000?text=+)f08a69639d0eb002c5dfc7b2f4fdc4443e1ed03215d0604bda398974136d414d
develop-2.6|b472123b51f3d7bbf8bd618a626be0941a9eb447be9580050d4c177c444d1fb5
snapshot|9aae37e9a546a902ecbc43dc20f3f15f3b6e45eb0ceeb99f44d232e9abf18fd5
v2.6-beta1|92fa409682078b4cd529e07aba9beba063b4cf2ed5934bb879fd8484ce6d6ceb
v2.5|![#c5f015](https://placehold.it/15/c5f015/000000?text=+)d657d5f435c836027329b91b1bc99e2ae9bca76b0d87bc641a8d190f396f01e6
v2.5.13|![#c5f015](https://placehold.it/15/c5f015/000000?text=+)d657d5f435c836027329b91b1bc99e2ae9bca76b0d87bc641a8d190f396f01e6
v2.5.12|ea6775d66e394039a967c7eeb5fee81fc6f1788bd2111ba3b8d7eb06df4b212b
v2.5.11|bf2bdfe93605d7c9b52f5b72c1428c015deace8048a4c84649301eb448c39d35

Even the latest-ldap is not the same as v2.5-ldap/v2.5.13-ldap

Tag | SHA256
--- | ------
latest-ldap|![#f08915](https://placehold.it/15/F08915/000000?text=+)9d6db07b108c6896b09b0c4d18f2f2f4d2bb78aa674a18cf8aadb652c4ac72d9
develop-2.6-ldap|97974cd77aed4bc995b042bb452924565eda39f64353fc3a4a785fb7c94bee9d
snapshot-ldap|97c5d895f2f9f04f49c467fbaeba94f999295f7f6a3b4b83a6ce6090b314d1a4
v2.6-beta1-ldap|6a492c39c59bf0ec8f2c02eb3392217dca5a4d6bd5913e78dbd295bc6cf66d7a
v2.5-ldap|![#1589F0](https://placehold.it/15/1589F0/000000?text=+)f04c831b61fbb40eb5897e7a58e12fcd54e3a668e884ee8ee2ef75eb6e801c70
v2.5.13-ldap|![#1589F0](https://placehold.it/15/1589F0/000000?text=+)f04c831b61fbb40eb5897e7a58e12fcd54e3a668e884ee8ee2ef75eb6e801c70
v2.5.12-ldap|c02249da62a1db0105d5df98627286a7dd9da2a9f137482601dd5389cd8bd9e5
v2.5.11-ldap|2a98e0748e03747b58d80070cbb5afce712bc6d13cde9828c19fd278e01333b1

**Comment by cimnine** [comment]
The `latest` tag of this project is not the same as _the latest version_ tag.
Here's why:

* `latest`: Built from https://github.com/digitalocean/netbox/tree/master
* `snapshot`: Built from https://github.com/digitalocean/netbox/tree/develop
* `v2.5.13`: Built from https://github.com/digitalocean/netbox/tree/v2.5.13
* `BRANCH`: Built from https://github.com/digitalocean/netbox/tree/BRANCH

The `-ldap` variants are just based on the 'normal' image and add more layers with additional dependencies and a different configuration file.

All the images are built automatically once a day directly on hub.docker.com`s CI system. Why the `latest` tag was not built for a while I don't know. But it's current again.
