### ISSUE TITLE
Tag v2.6 breaks containers because of CORS_ORIGIN

### ISSUE THREAD

**Issue by gun1x** [netbox-community/netbox-docker#139]
Since the v2.6 tag is out, the following error can be seen in the logs:
```
ERRORS:
?: (corsheaders.E013) Origin '' in CORS_ORIGIN_WHITELIST is missing scheme or netloc
	HINT: Add a scheme (e.g. https://) or netloc (e.g. example.com).
⏳ Waiting on DB...
SystemCheckError: System check identified some issues:

ERRORS:
?: (corsheaders.E013) Origin '' in CORS_ORIGIN_WHITELIST is missing scheme or netloc
	HINT: Add a scheme (e.g. https://) or netloc (e.g. example.com).
⏳ Waiting on DB...
SystemCheckError: System check identified some issues:

```

I tried adding `CORS_ORIGIN_ALLOW_ALL=true` to the env but this does not fix the issue.

**Comment by gun1x** [comment]
Fixed by setting the env var `CORS_ORIGIN_WHITELIST` to `http://localhost:3000 http://localhost:8000 http://localhost:8080`.

**Comment by cimnine** [comment]
Thank you for reporting this. I can confirm this behavior.

A workaround to restore 2.5 behavior is to add these lines to the `env/netbox.env` file:

```
CORS_ORIGIN_WHITELIST=http://localhost
CORS_ORIGIN_ALLOW_ALL=true
```
