### ISSUE TITLE
Changing BASE_PATH breaks certain URLs

### ISSUE THREAD

**Issue by Zer0t3ch** [netbox-community/netbox-docker#141]
## Current Behavior

Basic HTML loads but all URLs to "static data" (like JS files) return 404.

Example from browser console: `The script from “http://vt.myth.zone:32666/netbox/static/js/forms.js?v2.6.0” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type`
...

## Expected Behavior

Should function as normal with a slightly altered base URL
...

I assume this has something to do with the NGINX as a part of this `netbox-docker` project, rather than an issue with Netbox itself.

## Debug Information

The output of `docker-compose version`: `docker-compose version 1.17.0, build unknown`
The output of `docker version`: `Docker version 18.09.1, build 4c52b901c6cb`
The output of `git rev-parse HEAD`: `aed51262791e7cfd5839aef99e665b9fb241934b`
The command you used to start the project: `docker-compose up -d --force-recreate`

The output of `docker-compose logs netbox`:
https://gist.github.com/2c1ba38549980450efc492d73f969fa7

My `netbox.env` file: https://gist.github.com/43869162a74eb8fc35fa2b6b826f85c8

**Comment by cimnine** [comment]
Thank you for reporting this, and especially thank you for filling in the full template providing all the necessary information! ❤️ 

Just from looking at the logs it seems like a problem with the Nginx configuration.
What you would need to do is to adjust the configuration in your Nginx container.

`BASE_PATH` is a feature of Netbox, and the Docker image therefore offers a way to configure that  setting through an ENV variable. But the docker-compose configuration here serves for demo / development / testing purposes only. Although the Docker image itself is production ready, it is expected that one writes his/her own configuration in that case. (I.e. a setup that provides persistent storage for and proper backup of PostgreSQL, for example.) There is a whole section in the Readme dedicated to this.

Therefore I will leave it up to you to figure out the necessary changes required to the Nginx configuration, as adjusting the `BASE_PATH` is not a feature this project aims to provide out-of-the-box.

PS: I did not know about the `--force-recreate` trick, thanks for showing that :)

**Comment by Zer0t3ch** [comment]
I did figure out what changes needed to be made for my use-case, but it also seems to be a situation that could be handled by this project. (while full production-ready setup may not be the intent here, additional support wouldn't be a bad thing)

I understand if you don't want to personally pursue it, but if I make the necessary changes to automate it from an environment variable and make a pull request, will it be accepted? (otherwise, my manual adjustment is good enough for just me)

**Comment by cimnine** [comment]
That's a very kind offer of you. But I don't actually want to support more features than necessary. And for development / demo / testing purposes this feature is IMO not necessary. There are enough "features" for a Docker image already. If it turns out that this is a real demand, then we shall revisit this decision. Once more thank you for your effort trying to improve this project!

**Comment by kale1d0code** [comment]
I got this working
I have only tested the pathprefix ```netbox/``` but I assume others would work too

if I understand how this works correctly,
you need to mount the netbox files under the path you want to use so if the path prefix is foo you need to mount your volumes under /opt/netbox/foo and set
 ```- BASE_DIR=/opt/netbox/foo``` and ```BASE_PATH=foo/```

(as netbox is already mounted in /opt/netbox/netbox this is the easiest pathprefix to host on)

so BASE_DIR and BASE_PATH need to be used together

**Comment by Kani999** [comment]
> I got this working I have only tested the pathprefix `netbox/` but I assume others would work too
> 
> if I understand how this works correctly, you need to mount the netbox files under the path you want to use so if the path prefix is foo you need to mount your volumes under /opt/netbox/foo and set `- BASE_DIR=/opt/netbox/foo` and `BASE_PATH=foo/`
> 
> (as netbox is already mounted in /opt/netbox/netbox this is the easiest pathprefix to host on)
> 
> so BASE_DIR and BASE_PATH need to be used together

I'm not able to make it work. I'm trying to reproduce it with setting up the BASE_PATH as `foo/` . 
Could you point out, which files should be edited?  I tried to edit the `docker-compose.yml`, `netbox.env` and etc. but with no luck yet.

**Comment by kale1d0code** [comment]
I did have this working, I didn't edit any files in the image,
I found out about BASE_DIR from poking around in either this repo or the main netbox repo.
but since then and now, I am now getting the static media failure page.

The only suggestion I can make at this stage is to setup an nginx container to sit in front to workaround the problem with the netbox container.
A bonus would be to disable nginx in the netbox container and allow the nginx container to do all the work (hopefully this will require only changing one file) but I imagine if someone has enough knowledge to disable nginx in the netbox container it should be trivial to just fix the base_path issue, although I do prefer the micro-service approach.

**Comment by kale1d0code** [comment]
kkthxbye-code has identified the cause of the issue [here](https://github.com/netbox-community/netbox-docker/issues/650#issuecomment-967242563)

the nginx service uses a static config file.
mounting over it should solve the issue.
in the future maybe this file could be generated at startup from values in the environment variables
