### ISSUE TITLE
502 Bad Gateway after upgrade

### ISSUE THREAD

**Issue by pzhivov** [netbox-community/netbox-docker#145]
Hello, 

After upgrading v2.5.5 to the latet 2.6 release there is "502 Bad Gateway" error on the WebUI. I suspect, it indicates nginx cannot get some data. All containers, it seems, are running.

root@netbox:/netbox-docker# docker-compose ps
            Name                          Command               State              Ports            
----------------------------------------------------------------------------------------------------
netboxdocker_netbox-worker_1   python3 /opt/netbox/netbox ...   Up                                  
netboxdocker_netbox_1          /opt/netbox/docker-entrypo ...   Up                                  
netboxdocker_nginx_1           nginx -c /etc/netbox-nginx ...   Up      80/tcp, 0.0.0.0:80->8080/tcp
netboxdocker_postgres_1        docker-entrypoint.sh postgres    Up      5432/tcp                    
netboxdocker_redis_1           docker-entrypoint.sh sh -c ...   Up      6379/tcp        

Could you please help on how can I troubleshoot and fix that?

Pavel

**Comment by cimnine** [comment]
I'm sorry but I have to close this issue. It lacks any information that the issue template asks you to provide.
