### ISSUE TITLE
netbox-ldap cannot grant default permission to user

### ISSUE THREAD

**Issue by cutemomo6256** [netbox-community/netbox-docker#153]
Hello, I'm not sure if this is a bug or not, but I know that netbox recently disable permission to those who haven't login, which cannot even see any information, and I think this is very good. However, when I connect to ldap, and try to login with ldap user, the user still cannot see any information in netbox, unless the admin grant access to them, even though I set the "AUTH_LDAP_USER_FLAGS_BY_GROUP" "is staff" variable to some ldap user, it still need admin user to manually grant access to them. is there a default permission to those people who can at least login to the site? thanks for helping. 

## Current Behavior

When I login to the site by ldap user, it lock all information. I have to use admin user to manually grant access to ldap user to some group in netbox, so that they can see some information.

## Expected Behavior

non login user should not see any information, but login user may see some default information or be in the default group in netbox.

**Comment by cimnine** [comment]
Please file this issue with the netbox project. This does not seem to be related to the Docker package. If you think I'm mistaken, feel free to re-open this issue.
