### ISSUE TITLE
No v2.6.3-ldap image on Docker Hub

### ISSUE THREAD

**Issue by insertjokehere** [netbox-community/netbox-docker#156]
## Current Behavior

```
docker pull netboxcommunity/netbox:v2.6.3-ldap
Error response from daemon: manifest for netboxcommunity/netbox:v2.6.3-ldap not found: manifest unknown: manifest unknown
```

## Expected Behavior

```
docker pull netboxcommunity/netbox:v2.6.3-ldap
v2.6.3-ldap: Pulling from netboxcommunity/netbox
```

Netbox v2.6.3 has been released, and there is a `v2.6.3` tag on Docker Hub, but no `v2.6.3-ldap` tag. Either the `-ldap` version has been merged in with the generic image, or the `v2.6.3-ldap` image didn't get build correctly

**Comment by tobiasge** [comment]
The images is there now. It just took a while.

**Comment by insertjokehere** [comment]
It seems like there is the same issue with v2.6.4

**Comment by cimnine** [comment]
There is a race-condition in the build process. The `-ldap` variant relies on the regular variant. When a new version is out and the build process is trying to build the `-ldap` variant before the regular variant, it fails. It would require a re-work of the build process to fix that, and that's currently not something I have the time to do.

The situation automatically "fixes" itself after 24h, when the next build runs.
