### ISSUE TITLE
An superuser is unconditionally created on startup

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox-docker#160]
It is not possible to skip the creation of a superuser. The logic can be seen [here](https://github.com/netbox-community/netbox-docker/blob/master/docker/docker-entrypoint.sh#L10-L40).

The documentation says the following:
`SUPERUSER_*: Only define those variables during the initial setup, and drop them once the DB is set up. Don't use the default passwords!`

This is potentially dangerous, because if you did change SUPERUSER_NAME to something other than admin, and after the first run removed all the SUPERUSER_ options, a new superuser named admin would be created.

I think the best solution is to just skip the creation of the superuser if the required SUPERUSER_ variables are not set. When using LDAP auth, it doesn't really make sense to have a statically defined superuser.

**Comment by cimnine** [comment]
Would https://github.com/netbox-community/netbox-docker/pull/163 be a viable 'solution' to you?

The PR would introduce a new env variable `SKIP_SUPERUSER`, which – when set to `true` – would prevent creating the superuser.

**Comment by kkthxbye-code** [comment]
Looks good to me, that would fix our issue. Thanks for the quick fix.

**Comment by cimnine** [comment]
There is a new release containing the PR #163. Only new images for `snapshot` and `latest` are automatically re-built and pushed to Docker Hub. Versioned releases, e.g. `v2.6.6`, are not rebuilt.
