### ISSUE TITLE
Default Credentials Don't Work

### ISSUE THREAD

**Issue by vinaykapadia** [netbox-community/netbox-docker#165]
## Current Behavior

Followed the instructions to install (git pull, docker-compose pull, docker-compose up)
Access through browser
Enter "admin" as username and password
Errors and says "Please enter a correct username and password. Note that both fields may be case-sensitive."
...

## Expected Behavior

Logs me in.
...

## Debug Information

The output of `docker-compose version`: `1.24.1, build 4667896b`
The output of `docker version`: `19.03.1`
The output of `git rev-parse HEAD`: `19728fa3e6b4f409d53beeea740705af905bfef9`
The command you used to start the project: `docker-compose up -d`

The output of `docker-compose logs netbox`:

```
https://gist.github.com/vinaykapadia/d1618b830b0706b2c70e878f5a3b0780
```

**Comment by kkthxbye-code** [comment]
Change SKIP_SUPERUSER=true to SKIP_SUPERUSER=false in env/netbox.env, and change SUPERUSER_NAME to admin.

@cimnine I think you accidentally pushed netbox.env in this commit: 79d349133e8ae62b11bf618480d62303543946d2 

SKIP_SUPERUSER is true and SUPERUSER_NAME is admin2.

**Comment by cimnine** [comment]
Thank you for reporting this issue. As @kkthxbye-code pointed out, this is my fault, and I'm sorry this slipped in. A fix was just pushed and builds for `latest`, `snapshot` and co should start appearing soon on Docker Hub.

**Comment by vinaykapadia** [comment]
Thanks!
