### ISSUE TITLE
Switch to release/development branching model

### ISSUE THREAD

**Issue by cimnine** [netbox-community/netbox-docker#184]
## Current Behavior

Currently, the `master` branch is where development happens, and which PRs usually target.
But it's also the branch where all the Docker images are built from.

This leads to situations, where we merge PRs to the master branch, and - when not immediately releasing the branch - the Docker images are getting tagged with a wrong version.

## Expected Behavior

The version, which the label on the Docker image portraits, must always be accurate. This helps debugging any issues.

Therefore I suggest the following change of the development workflow:

- The `main` branch continues to be the `master` branch. It must be stable. People clone this branch to get started with the _Netbox Docker_ project. The Docker images continue to be built from this branch.
- We introduce a `develop` branch (like the Netbox project already has) to which we continually merge PRs and on which new features are developed and tested. Whenever we decide it's time for a release, we adjust the VERSION file to `x.y.z`, merge `develop` to `master`, tag that merge-commit with the VERSION number, and finally adjust the VERSION file on the `develop` branch to `x.y.z+1-develop`.

**Comment by cimnine** [comment]
I'm thinking about ditching the name `master` for the main branch and using `stable` or `release` instead.

**Comment by tobiasge** [comment]
I would use `release` and `develop` :+1:

**Comment by cimnine** [comment]
* I've pushed two branches, `release` & `develop`
* I've set up branch protection rules
* I've updated the [Release](https://github.com/netbox-community/netbox-docker/wiki/Release) wiki page
* I've created an explanation for the [Branching Model](https://github.com/netbox-community/netbox-docker/wiki/Branching-Model) on the wiki
* I've changed all PRs to target the `develop` branch
* I've created a PR to adapt the relevant repository files #202 
* Configured builds on the Docker Hub to also build the `release` branch. (No images should get pushed to the registry until #202 is merged to `release`. And then the `master` builds should not be pushed anymore.)

What's left to do:

* [x] Merge #202
* [x] Make a release, i.e. merge #212 and create a tag `0.20.0`.
* [x] Remove the builds on Docker Hub that target the `master` branch
* [x] Remove the `master` branch

**Comment by rasanentimo** [comment]
Please point the default branch to 'release' instead of 'develop'. It's a bit confusing the follow the guide and not get working environment, for example due to non-working develop branch.

**Comment by cimnine** [comment]
> Please point the default branch to 'release' instead of 'develop'. It's a bit confusing the follow the guide and not get working environment, for example due to non-working develop branch.

We will eventually revert to that behavior if we merge and release https://github.com/netbox-community/netbox-docker/pull/214.

For now, existing users should not be affected, since there is still a master branch. Once 0.20.0 is merged, people should update to the release branch. Any further `git pull` will be on the `release` branch.

The only concern is new users. For them, we have updated the instructions to clone the project to the following command. It causes the release branch to be automatically checked out.

```bash
git clone -b release https://github.com/netbox-community/netbox-docker.git
```
