### ISSUE TITLE
build.sh use of GNU date breaks build on BSD/macOS

### ISSUE THREAD

**Issue by mattolenik** [netbox-community/netbox-docker#197]
## Current Behavior

Build breaks on macOS due to the following in `build.sh`:
```
BUILD_DATE="$(date --utc --iso-8601=minutes)"
```

macOS uses BSD `date` and doesn't have these options.

## Expected Behavior

Build should work without GNU-specific `date`.

**Comment by cimnine** [comment]
Thank you for bringing up this issue. I have started a discussion in the PR about the proposed solution.
