### ISSUE TITLE
Docker images for version 2.6.8

### ISSUE THREAD

**Issue by TeroPihlaja** [netbox-community/netbox-docker#205]
Version 2.6.8 seems to be released but there is no docker image for that.

https://github.com/netbox-community/netbox/releases/tag/v2.6.8

**Comment by cimnine** [comment]
Yes, the hook that trigger Docker Hub's build system is broken.

**Comment by cimnine** [comment]
Images for 2.6.8 are now available. We'll know tomorrow whether processing webhook is fixed on Docker Hub's side.

**Comment by cimnine** [comment]
The trigger is now working again.

**Comment by TeroPihlaja** [comment]
Great. Seems to work.
