### ISSUE TITLE
Static volume is no longer writable from the netbox container

### ISSUE THREAD

**Issue by ChrisPortman** [netbox-community/netbox-docker#215]
Since this commit, the compose stack is no longer able to write the static files to the static volume

https://github.com/netbox-community/netbox-docker/commit/0a9991de962a6440ac372b913a9731b0dc99cac4#diff-3254677a7917c6c01f55212f86c57fbf

This commit changes the netbox container to run as uid 101.  Docker creates the volume owned by "root:root" 0755.

the commit includes a change to the build:
https://github.com/netbox-community/netbox-docker/blob/7863e5902e55ca06f9a4c6f9e1cfc0c98aee3709/Dockerfile#L76

 to chmod g+w static, but the group on the volume is still root.

**Comment by ozmend** [comment]
Hi,
If you are using RedHat, fedora or centos u can test "Z" parameters after volume
Exp:
volumes:
    - "/path/directory:path/directory:Z"
Also u can check audit.log by using audit2allow command

**Comment by ChrisPortman** [comment]
No selinux in play, im using arch

**Comment by cimnine** [comment]
Please provide all the information in the bug report template. We didn't make the template, so that less people make tickets. We made the template so that we can easily reproduce your issue with the exact same versions. Otherwise it's just wild guessing and I have better things to do in my spare time.

You find the issue template here: https://raw.githubusercontent.com/netbox-community/netbox-docker/develop/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by djs** [comment]
I ran into the same issue as @ChrisPortman when upgrading from 0.18.2 to 0.21.1. I believe the procedure to reproduce should just be to:
1. Bring up 0.18.2
2. Check out 0.21.1 and then attempt to bring up again with ```docker-compose up```

As a workaround I simply modified the volume permissions directly (your paths may vary, check with ```docker volume ls```):
```
$ sudo su
# cd /var/lib/docker/volumes/netboxdocker_netbox-static-files/
# chmod -R 101:101 _data
```
The line in Dockerfile is creating directories, but in my case the volume already existed and so the owner is not correct, so I think an additional line would need to be added to chown for the upgrade path. I'm not clear whether this line is operating on the container filesystem or the volume mount, though.

**Comment by ChrisPortman** [comment]
To be fair, my issue was that I didnt quite have the versions lined up.  I was using the develop version of this repo against the `latest` tagged image from docker hub.  Switching to `release` and refreshing sorted it for me.  I didnt try building the image from the `develop` branch of this repo.

(note I was at 0.19.4)
