### ISSUE TITLE
When change configuration in docker/nginx.conf no configuration saved in containers

### ISSUE THREAD

**Issue by kasatka231** [netbox-community/netbox-docker#216]
Here is config that i change:        
[root@netbox netbox-docker]# cat docker/nginx.conf 
}

    server {
        listen      8080;
        access_log  off;
        server_name netbox;
        keepalive_timeout 65;
        ssl_certificate /opt/certs/netbox_ssl.crt;
        ssl_certificate_key /opt/certs/netbox_ssl.key;
        ssl on;
        ssl_session_cache builtin:1000 shared:SSL:10m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
        ssl_prefer_server_ciphers on;

        location /static/ {
            alias /opt/netbox/netbox/static/;
        }

        location / {
            proxy_pass http://netbox:8001;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header P3P 'CP="ALL DSP COR PSAa PSDa OUR NOR ONL UNI COM NAV"';
        }
    }
}

Check configuration nginx in container and there are no changes:
docker exec -i netbox-docker_nginx_1 cat /etc/netbox-nginx/nginx.conf
daemon off;
worker_processes 1;

}

    server {
        listen      8080;
        access_log  off;

        location /static/ {
            alias /opt/netbox/netbox/static/;
        }

        location / {
            proxy_pass http://netbox:8001;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header P3P 'CP="ALL DSP COR PSAa PSDa OUR NOR ONL UNI COM NAV"';
        }
    }
}

I also add two screen when i add configuration "server_name" and after build containers there are no configuration that i add
<img width="936" alt="Screenshot 2020-01-10 at 23 21 48" src="https://user-images.githubusercontent.com/42998974/72184183-e2ec4200-3400-11ea-9a73-2c87b720387e.png">
<img width="896" alt="Screenshot 2020-01-10 at 23 24 31" src="https://user-images.githubusercontent.com/42998974/72184184-e2ec4200-3400-11ea-82d1-e6442577dbdd.png">

It is seems a bug  in the implementation of docker image and the original configuration of NGINX  is constantly and it is not possible to change it.  Also not possibly changed dockers images.

**Comment by cimnine** [comment]
I'm sorry, I can not accept this as a bug report, as you did not provide any of the information in the bug report template.

Please join the #netbox-docker channel on the Slack of Network To Code at http://slack.networktocode.com/ and ask your question there.

Tickets are only meant for bug reports and feature requests.
