### ISSUE TITLE
LDAP login error

### ISSUE THREAD

**Issue by ozmend** [netbox-community/netbox-docker#217]
I'm using netbox-docker-ldap version

local user accounts works normally.

Ldap user returns error while trying login

Caught LDAPError while authenticating CN=Test1,OU=Users,DC=EXAMPLE,DC=COM: LDAPError(0, 'Error')

My env settings in _netbox.env_ file is like this;

# LDAP Settings
AUTH_LDAP_BIND_DN='CN=Netbox,OU=ServiceUsers,OU=Users,DC=EXAMPLE,DC=COM'
AUTH_LDAP_BIND_PASSWORD='password'
AUTH_LDAP_SERVER_URI='ldaps://dc02.example.com'
AUTH_LDAP_USER_SEARCH_BASEDN='OU=Users,DC=EXAMPLE,DC=COM'
AUTH_LDAP_GROUP_SEARCH_BASEDN='OU=Groups,DC=EXAMPLE,DC=COM'
AUTH_LDAP_IS_SUPERUSER_DN='CN=Netbox_Users,OU=Groups,DC=EXAMPLE,DC=COM'
AUTH_LDAP_IS_ADMIN_DN='CN=Netbox_Admins,OU=Groups,DC=EXAMPLE,DC=COM'
LDAP_IGNORE_CERT_ERRORS='True'

Would you help to solve the problem

**Comment by cimnine** [comment]
Please join the #netbox-docker channel on the Slack of Network To Code at http://slack.networktocode.com/ and ask your question there.

Tickets are only meant for bug reports.
