### ISSUE TITLE
Error on startup "django.db.utils.OperationalError: could not translate host name "postgres" to address: Name does not resolve"

### ISSUE THREAD

**Issue by gordonjcp** [netbox-community/netbox-docker#223]
## Current Behavior

$ git pull
$ docker-compose pull
$ docker-compose up

Error occurs a few seconds into startup.  Not present when I switch to the "release" branch, only on "develop".
## Expected Behavior

Normal application startup

## Debug Information

The output of `docker-compose version`: docker-compose version 1.21.0, build unknown

The output of `docker version`:  Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.9
 Git commit:        6a30dfca03
 Built:             Mon Sep 16 03:56:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.9
  Git commit:       6a30dfca03
  Built:            Wed Sep 11 22:45:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10-0ubuntu1
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit: 
The output of `git rev-parse HEAD`: 870b44fdbc06eb5ac3d1576e1438fe9b7fd5d315

The command you used to start the project: "docker-compose up"

The output of `docker inspect netboxcommunity/netbox:latest --format "{{json .ContainerConfig.Labels}}"`:
```{"NETBOX_GIT_BRANCH":"","NETBOX_GIT_REF":"","NETBOX_GIT_URL":"","ORIGINAL_TAG":"","org.label-schema.build-date":"","org.label-schema.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.","org.label-schema.name":"Netbox Docker","org.label-schema.schema-version":"1.0","org.label-schema.url":"https://github.com/netbox-community/netbox-docker","org.label-schema.usage":"https://github.com/netbox-community/netbox-docker/wiki","org.label-schema.vcs-ref":"","org.label-schema.vcs-url":"https://github.com/netbox-community/netbox-docker.git","org.label-schema.vendor":"The netbox-docker contributors.","org.label-schema.version":"snapshot","org.opencontainers.image.authors":"The netbox-docker contributors.","org.opencontainers.image.created":"","org.opencontainers.image.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.","org.opencontainers.image.documentation":"https://github.com/netbox-community/netbox-docker/wiki","org.opencontainers.image.licenses":"Apache-2.0","org.opencontainers.image.revision":"","org.opencontainers.image.source":"https://github.com/netbox-community/netbox-docker.git","org.opencontainers.image.title":"Netbox Docker","org.opencontainers.image.url":"https://github.com/netbox-community/netbox-docker","org.opencontainers.image.vendor":"The netbox-docker contributors.","org.opencontainers.image.version":"snapshot"}


```

The output of `docker-compose logs netbox`:

https://gist.github.com/gordonjcp/6b81f5feefe8e42c508f6cf9dd111b24

**Comment by cimnine** [comment]
Could you also provide the output of `docker-compose logs postgres`?

**Comment by gordonjcp** [comment]
Sure, I should have thought of that.  This is weird, because I haven't run netbox-docker on this machine before, and docker-compose container prune followed by docker-compose volume-prune doesn't show anything being deleted.

Now there's a new issue though...

Nuking the whole machine and reinstalling from scratch seems to have cured it.

```
Attaching to netbox-docker_postgres_1
postgres_1       | 
postgres_1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1       | 
postgres_1       | 2020-01-18 18:04:42.122 UTC [1] FATAL:  database files are incompatible with server
postgres_1       | 2020-01-18 18:04:42.122 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 11.6.
```

**Comment by cimnine** [comment]
Usually `docker-compose down -v` does the trick to remove all the data and start from scratch.

**Comment by cimnine** [comment]
@gordonjcp is this still an issue or can we close it?

**Comment by gordonjcp** [comment]
I think so, yes.  I've got weird reproducible behaviour that any time I start up netbox-docker on a machine that's had some sort of postgres database for a different project in docker, it seems to collide and stop netbox's database from starting up.  I don't think it's netbox-docker's fault though.

**Comment by sigreer** [comment]
if anyone else bumps into this issue I was able to solve it by creating a separate backend network and adding all of the services to it.

**Comment by laviniamnedelea** [comment]
> Usually `docker-compose down -v` does the trick to remove all the data and start from scratch.

Can this behavior be reproduced in the context of swarm?

**Comment by plevart** [comment]
`docker-compose down -v` would remove the volumes and I don't want to loose the data (PostgreSQL database). Any way to keep data and make it work?

**Comment by devfinwiz** [comment]
I had the exact same problem... I got a fix by doing the following:
1. Your hostname under db service in the docker-compose.yml and your host in settings.py file for database should be the same. 

This will make sure you don't need to perform docker-compose down -v.
