### ISSUE TITLE
static content not found in podman/rootless pod.

### ISSUE THREAD

**Issue by nimbius** [netbox-community/netbox-docker#240]
## Current Behavior

podman run --pod netbox-pod --env-file=netbox-env netboxcommunity/netbox:v2.7.4 executes and connects as expected, however static assets all return 404.

## Expected Behavior

static assets load too.

## Debug Information

compose and docker are not used.  This is a podman rootless pod managed by systemd. 

Logs from the startup follow:

podman run --pod netbox-pod --env-file=netbox-env netboxcommunity/netbox:v2.7.4
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, secrets, sessions, taggit, tenancy, users, virtualization
Running migrations:
  No migrations to apply.
💡 Superuser Username: admin, E-Mail: admin@example.com
Running /opt/netbox/startup_scripts/000_users.py
Running /opt/netbox/startup_scripts/010_groups.py
Running /opt/netbox/startup_scripts/020_custom_fields.py
Running /opt/netbox/startup_scripts/030_regions.py
Running /opt/netbox/startup_scripts/040_sites.py
Running /opt/netbox/startup_scripts/050_manufacturers.py
Running /opt/netbox/startup_scripts/060_device_types.py
Running /opt/netbox/startup_scripts/070_rack_roles.py
Running /opt/netbox/startup_scripts/075_rack_groups.py
Running /opt/netbox/startup_scripts/080_racks.py
Running /opt/netbox/startup_scripts/090_device_roles.py
Running /opt/netbox/startup_scripts/100_platforms.py
Running /opt/netbox/startup_scripts/110_tenant_groups.py
Running /opt/netbox/startup_scripts/120_tenants.py
Running /opt/netbox/startup_scripts/130_devices.py
Running /opt/netbox/startup_scripts/140_cluster_types.py
Running /opt/netbox/startup_scripts/150_rirs.py
Running /opt/netbox/startup_scripts/160_aggregates.py
Running /opt/netbox/startup_scripts/170_clusters.py
Running /opt/netbox/startup_scripts/180_vrfs.py
Running /opt/netbox/startup_scripts/190_prefix_vlan_roles.py
Running /opt/netbox/startup_scripts/200_vlan_groups.py
Running /opt/netbox/startup_scripts/210_vlans.py
Running /opt/netbox/startup_scripts/220_prefixes.py
Running /opt/netbox/startup_scripts/230_virtual_machines.py
Running /opt/netbox/startup_scripts/240_virtualization_interfaces.py
Running /opt/netbox/startup_scripts/250_dcim_interfaces.py
Running /opt/netbox/startup_scripts/260_ip_addresses.py

979 static files copied to '/opt/netbox/netbox/static'.
✅ Initialisation is done.
[2020-02-09 02:32:10 +0000] [1] [DEBUG] Current configuration:
  config: /etc/netbox/config/gunicorn_config.py
  bind: ['0.0.0.0:8001']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /opt/netbox/netbox
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: -
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags:
  statsd_prefix:
  proc_name: None
  default_proc_name: netbox.wsgi
  pythonpath: /opt/netbox/netbox
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f13186bec20>
  on_reload: <function OnReload.on_reload at 0x7f13186bed40>
  when_ready: <function WhenReady.when_ready at 0x7f13186bee60>
  pre_fork: <function Prefork.pre_fork at 0x7f13186bef80>
  post_fork: <function Postfork.post_fork at 0x7f13186d60e0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f13186d6200>
  worker_int: <function WorkerInt.worker_int at 0x7f13186d6320>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f13186d6440>
  pre_exec: <function PreExec.pre_exec at 0x7f13186d6560>
  pre_request: <function PreRequest.pre_request at 0x7f13186d6680>
  post_request: <function PostRequest.post_request at 0x7f13186d6710>
  child_exit: <function ChildExit.child_exit at 0x7f13186d6830>
  worker_exit: <function WorkerExit.worker_exit at 0x7f13186d6950>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f13186d6a70>
  on_exit: <function OnExit.on_exit at 0x7f13186d6b90>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2020-02-09 02:32:10 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-02-09 02:32:10 +0000] [1] [DEBUG] Arbiter booted
[2020-02-09 02:32:10 +0000] [1] [INFO] Listening at: http://0.0.0.0:8001 (1)
[2020-02-09 02:32:10 +0000] [1] [INFO] Using worker: sync
[2020-02-09 02:32:10 +0000] [25] [INFO] Booting worker with pid: 25
[2020-02-09 02:32:10 +0000] [26] [INFO] Booting worker with pid: 26
[2020-02-09 02:32:10 +0000] [27] [INFO] Booting worker with pid: 27
[2020-02-09 02:32:10 +0000] [1] [DEBUG] 3 workers
[2020-02-09 02:32:15 +0000] [27] [DEBUG] GET /
10.0.2.2 - - [09/Feb/2020:02:32:16 +0000] "GET / HTTP/1.1" 200 45668 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:16 +0000] [27] [DEBUG] GET /static/bootstrap-3.4.1-dist/css/bootstrap.min.css
[2020-02-09 02:32:16 +0000] [25] [DEBUG] GET /static/font-awesome-4.7.0/css/font-awesome.min.css
[2020-02-09 02:32:16 +0000] [26] [DEBUG] GET /static/jquery-ui-1.12.1/jquery-ui.css
10.0.2.2 - - [09/Feb/2020:02:32:16 +0000] "GET /static/bootstrap-3.4.1-dist/css/bootstrap.min.css HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:16 +0000] [27] [DEBUG] GET /static/select2-4.0.12/dist/css/select2.min.css
10.0.2.2 - - [09/Feb/2020:02:32:16 +0000] "GET /static/select2-4.0.12/dist/css/select2.min.css HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:16 +0000] [27] [DEBUG] GET /static/select2-bootstrap-0.1.0-beta.10/select2-bootstrap.min.css
10.0.2.2 - - [09/Feb/2020:02:32:16 +0000] "GET /static/select2-bootstrap-0.1.0-beta.10/select2-bootstrap.min.css HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:16 +0000] [27] [DEBUG] GET /static/flatpickr-4.6.3/themes/light.css
10.0.2.2 - - [09/Feb/2020:02:32:16 +0000] "GET /static/flatpickr-4.6.3/themes/light.css HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:16 +0000] [27] [DEBUG] GET /static/css/base.css
10.0.2.2 - - [09/Feb/2020:02:32:16 +0000] "GET /static/css/base.css?v2.7.4 HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:16 +0000] [27] [DEBUG] GET /static/jquery/jquery-3.4.1.min.js
10.0.2.2 - - [09/Feb/2020:02:32:16 +0000] "GET /static/jquery/jquery-3.4.1.min.js HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:16 +0000] [27] [DEBUG] GET /static/jquery-ui-1.12.1/jquery-ui.min.js
10.0.2.2 - - [09/Feb/2020:02:32:16 +0000] "GET /static/jquery-ui-1.12.1/jquery-ui.min.js HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:16 +0000] [27] [DEBUG] GET /static/bootstrap-3.4.1-dist/js/bootstrap.min.js
10.0.2.2 - - [09/Feb/2020:02:32:16 +0000] "GET /static/bootstrap-3.4.1-dist/js/bootstrap.min.js HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:16 +0000] [27] [DEBUG] GET /static/select2-4.0.12/dist/js/select2.min.js
10.0.2.2 - - [09/Feb/2020:02:32:16 +0000] "GET /static/select2-4.0.12/dist/js/select2.min.js HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:16 +0000] [27] [DEBUG] GET /static/clipboard.js/clipboard-2.0.4.min.js
10.0.2.2 - - [09/Feb/2020:02:32:16 +0000] "GET /static/clipboard.js/clipboard-2.0.4.min.js HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:16 +0000] [27] [DEBUG] GET /static/flatpickr-4.6.3/flatpickr.min.js
10.0.2.2 - - [09/Feb/2020:02:32:16 +0000] "GET /static/flatpickr-4.6.3/flatpickr.min.js HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:16 +0000] [27] [DEBUG] GET /static/js/forms.js
10.0.2.2 - - [09/Feb/2020:02:32:16 +0000] "GET /static/js/forms.js?v2.7.4 HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
10.0.2.2 - - [09/Feb/2020:02:32:17 +0000] "GET /static/jquery-ui-1.12.1/jquery-ui.css HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
10.0.2.2 - - [09/Feb/2020:02:32:17 +0000] "GET /static/font-awesome-4.7.0/css/font-awesome.min.css HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:17 +0000] [25] [DEBUG] GET /static/img/netbox_logo.svg
10.0.2.2 - - [09/Feb/2020:02:32:17 +0000] "GET /static/img/netbox_logo.svg HTTP/1.1" 404 34635 "http://localhost:9000/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[2020-02-09 02:32:18 +0000] [27] [DEBUG] GET /

**Comment by cimnine** [comment]
This is expected behavior. Static content is served by a different container, e.g. an Nginx or Apache HTTPD. Please see the docker-compose.yml for how this works.
