### ISSUE TITLE
Incorrect file owner in netbox-static-files preventing startup after upgrade 0.19.4->0.22.0

### ISSUE THREAD

**Issue by adlerweb** [netbox-community/netbox-docker#243]
After updating my rather old installation from 0.19.4(?*) to 0.22.0 netbox crashed during startup with the following log:

```
...
netbox_1         | Running /opt/netbox/startup_scripts/250_dcim_interfaces.py
netbox_1         | Running /opt/netbox/startup_scripts/260_ip_addresses.py
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "./manage.py", line 10, in <module>
netbox_1         |     execute_from_command_line(sys.argv)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
netbox_1         |     utility.execute()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
netbox_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
netbox_1         |     self.execute(*args, **cmd_options)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
netbox_1         |     output = self.handle(*args, **options)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
netbox_1         |     collected = self.collect()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
netbox_1         |     handler(path, prefixed_path, storage)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 342, in copy_file
netbox_1         |     if not self.delete_file(path, prefixed_path, source_storage):
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 292, in delete_file
netbox_1         |     self.storage.delete(prefixed_path)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/files/storage.py", line 303, in delete
netbox_1         |     os.remove(name)
netbox_1         | PermissionError: [Errno 13] Permission denied: '/opt/netbox/netbox/static/bootstrap-3.4.1-dist/js/npm.js'
netbox-docker_netbox_1 exited with code 1
```

As far as I can tell files in volume **netbox-static-files** where previously owned by UID 0 with mode 755, the netbox process itself is currently running as UID 101 and tries to modify files in there. I chown'd the files and startup seems fine again.

As far as I can tell the files in there are not user-costumizable, right? In this case I would suggest to add a note to delete this volume inside the upgrade guide.

** netboxcommunity/netbox@sha256:cd5e547b560f944507b9362cfe9e4e03e9bedfe21714d12d0cee0053d02b9fb4, created 2020-01-07T04:37:48.032079264Z - could not find a matching tag

**Comment by tyler-8** [comment]
Saw this behavior as well. You have to drop down to `docker volume rm <volume-name>` to resolve the problem. Or possibly `docker-compose down -v` but then you lose ALL data, which you may not want to do.

**Comment by cimnine** [comment]
Thank for reporting this and also for suggesting a solution.

> As far as I can tell the files in there are not user-costumizable, right?

This is correct.

> In this case I would suggest to add a note to delete this volume inside the upgrade guide.

I've just done that: https://github.com/netbox-community/netbox-docker/releases/tag/0.20.0

> You have to drop down to `docker volume rm <volume-name>` to resolve the problem.

Thank you for providing the right command.
