### ISSUE TITLE
Issue with reports

### ISSUE THREAD

**Issue by rendxq** [netbox-community/netbox-docker#246]
## Current Behavior

I renamed file reports/devices.py.example to reports/devices.py. After that I tried getting report.
http://netbox.example.loc/extras/reports  Unfortunately got error. 
![image](https://user-images.githubusercontent.com/27946443/75090674-d9c1c980-5597-11ea-9e74-ed4435f7a7b5.png)
...

## Expected Behavior

Open reports-page 

...

## Debug Information

The output of `docker-compose version`: `1.25.4`
The output of `docker version`: `19.03.5`
The output of `git rev-parse HEAD`: `80f514fa90997bc7b132ea06b84056c6720f37d0`
The command you used to start the project: `docker-compose up -d`

The output of `docker inspect netboxcommunity/netbox:latest --format "{{json .Config.Labels}}"`:

```json
{
  "JSON JSON JSON":
    "{
   "NETBOX_GIT_BRANCH":"HEAD",
   "NETBOX_GIT_REF":"50926411573e958651deb418542a17fdae159526",
   "NETBOX_GIT_URL":"https://github.com/netbox-community/netbox.git",
   "ORIGINAL_TAG":"docker.io/netboxcommunity/netbox:latest",
   "org.label-schema.build-date":"2020-02-21T05:59+00:00",
   "org.label-schema.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.",
   "org.label-schema.name":"Netbox Docker",
   "org.label-schema.schema-version":"1.0",
   "org.label-schema.url":"https://github.com/netbox-community/netbox-docker",
   "org.label-schema.usage":"https://github.com/netbox-community/netbox-docker/wiki",
   "org.label-schema.vcs-ref":"80f514fa90997bc7b132ea06b84056c6720f37d0",
   "org.label-schema.vcs-url":"https://github.com/netbox-community/netbox-docker.git",
   "org.label-schema.vendor":"The netbox-docker contributors.",
   "org.label-schema.version":"0.22.0",
   "org.opencontainers.image.authors":"The netbox-docker contributors.",
   "org.opencontainers.image.created":"2020-02-21T05:59+00:00",
   "org.opencontainers.image.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.",
   "org.opencontainers.image.documentation":"https://github.com/netbox-community/netbox-docker/wiki",
   "org.opencontainers.image.licenses":"Apache-2.0",
   "org.opencontainers.image.revision":"80f514fa90997bc7b132ea06b84056c6720f37d0",
   "org.opencontainers.image.source":"https://github.com/netbox-community/netbox-docker.git",
   "org.opencontainers.image.title":"Netbox Docker",
   "org.opencontainers.image.url":"https://github.com/netbox-community/netbox-docker",
   "org.opencontainers.image.vendor":"The netbox-docker contributors.",
   "org.opencontainers.image.version":"0.22.0"
}"
}
```
The output of `docker-compose logs netbox`:
https://gist.github.com/rendxq/9b8e829436711f709d9f74543a7f0ef7#file-gistfile1-txt

Is anything changed at report schema?

**Comment by cimnine** [comment]
Thank you for reporting this issue.

In Netbox 2.7 they have changed the internal structure quite a bit. It looks like the sample report uses one of those old classes/models.

Since I've never worked with reports I can only hope that someone wants to fix the sample report we ship.

**Comment by weisdd** [comment]
@rendxq @cimnine Unfortunately, an example of [a similar report](https://netbox.readthedocs.io/en/stable/additional-features/reports/) in the official documentation is incorrect as well. As you can see from the error, dcim/constans.py doesn't contain the required variables. More specifically, CONNECTION_STATUS_PLANNED and DEVICE_STATUS_ACTIVE are not part of dcim.constants:
1. DEVICE_STATUS_ACTIVE was moved to DeviceStatusChoices.STATUS_ACTIVE. 
2. At first, I thought CONNECTION_STATUS_PLANNED was moved to CableStatusChoices.STATUS_PLANNED, but console_port.connection_status and power_port.connection_status happened to have this set of values:
* None = Cable not connected or connected to a Rear/Front port;
* False = Cable connected to a Console Server Port, marked as Planned;
* True = Cable connected to a Console Server Port, marked as Installed.

If we combine the example from docs with the details I mentioned, I believe the code should look like this:

```python
from dcim.choices import DeviceStatusChoices
from dcim.models import ConsolePort, Device, PowerPort
from extras.reports import Report


class DeviceConnectionsReport(Report):
    description = "Validate the minimum physical connections for each device"

    def test_console_connection(self):

        # Check that every console port for every active device has a connection defined.
        active = DeviceStatusChoices.STATUS_ACTIVE
        for console_port in ConsolePort.objects.prefetch_related('device').filter(device__status=active):
            if console_port.connected_endpoint is None:
                self.log_failure(
                    console_port.device,
                    "No console connection defined for {}".format(console_port.name)
                )
            elif not console_port.connection_status:
                self.log_warning(
                    console_port.device,
                    "Console connection for {} marked as planned".format(console_port.name)
                )
            else:
                self.log_success(console_port.device)

    def test_power_connections(self):

        # Check that every active device has at least two connected power supplies.
        for device in Device.objects.filter(status=DeviceStatusChoices.STATUS_ACTIVE):
            connected_ports = 0
            for power_port in PowerPort.objects.filter(device=device):
                if power_port.connected_endpoint is not None:
                    connected_ports += 1
                    if not power_port.connection_status:
                        self.log_warning(
                            device,
                            "Power connection for {} marked as planned".format(power_port.name)
                        )
            if connected_ports < 2:
                self.log_failure(
                    device,
                    "{} connected power supplies found (2 needed)".format(connected_ports)
                )
            else:
                self.log_success(device)
```

**Comment by cimnine** [comment]
This should be resolved in the next release. I therefore close this issue. Thanks to anyone contributing (either reporting, providing feedback or providing a PR).
