### ISSUE TITLE
Support/document usage of objects tags in initializers/startup_scripts

### ISSUE THREAD

**Issue by Zempashi** [netbox-community/netbox-docker#249]
## Desired Behavior

Would like to use `tags` in initializers/startup_scripts, and this could be nice to be documented for sure ;)

## Contrast to Current Behavior

Currently, I can't find a way to use `tags` with initializers/startup_scripts, it's may be a lack of documentation, but a quick testing adding a `tags` argument to various objects, resulted in stacktraces, or completely ignore during initialization.

## Changes Required

Don't know, sorry.

## Discussion: Benefits and Drawbacks

Benefits:
- easier to spawn a Netbox in CI with complete set of fixtures, and then test scripts against Netbox API

**Comment by cimnine** [comment]
Thank you for proposing this feature.

Currently I don't have time to implement it, but I'm sure it would not be that hard to do.

**Comment by cimnine** [comment]
In the next version, [it will be possible to define the tags themselves](https://github.com/netbox-community/netbox-docker/pull/384/files#diff-951e2218cbd7605f97e7c65ad07b6372090303a24b2c4bfb4227448f376b5e4b). But it's still not possible – to the best of my knowledge – to assign them right away to the object created by initializers.
