### ISSUE TITLE
DB Restore on another system incomplete

### ISSUE THREAD

**Issue by spoer78** [netbox-community/netbox-docker#257]
hi there,

sorry for bothering you, but we are currently using a quite old version of netbox-docker (v0.17.0), but it is running quite fine. We are making backups of the database, reports and media as described in the official documentation.

Now we wanted to move the installation from one server to another. So i stopped netbox-docker, created a backup of the whole folder, docker save and docker load the images to the new server, copied and extracted the netbox-docker dir and started everything with docker-compose up. It started but it was empty. So i copied all the backup files to the server and did a restore exactly as described in the howto and it went fine as well. No errors at all, smooth sailing all the way.

But when i check the netbox via browser, only Providers and Circuits are restored, everything else is missing. When i check the dump, the data is there.

Does someone has an idea what went wrong?

Best regards,
espe

PS: i know we have quite an old version, and i tried an upgrade to the current version (on the new server) as well, but after i imported the database, it fails with a KeyError when i try to upgrade the database to the current version.

**Comment by spoer78** [comment]
It might have just taken a looooooong time but now suddenly everything is there. So it might simply be resolved by "patience". :) Thanks anyway.

**Comment by cimnine** [comment]
Please use the Slack channel in the future to ask question.
