### ISSUE TITLE
RuntimeWarning: The cacheops cache is unreachable!

### ISSUE THREAD

**Issue by atkrv** [netbox-community/netbox-docker#259]
Hello! 👋

I can't get which password and where is invalid and cant' get rid of this warning. Could you guys please help me?

Thanks!

# Current Behavior
NetBox container logs sporadically shows:
`RuntimeWarning: The cacheops cache is unreachable! Error: invalid password`

# Expected Behavior
No errors in logs during container runtime

# Debug
NetBox container sporadically shows such warning:
```
...

/usr/local/lib/python3.7/site-packages/cacheops/redis.py:21: RuntimeWarning: The cacheops cache is unreachable! Error: invalid password
  warnings.warn("The cacheops cache is unreachable! Error: %s" % e, RuntimeWarning)
[2020-03-18 15:03:08 +0000] [27] [DEBUG] GET /dcim/sites/
10.80.78.129 - - [18/Mar/2020:15:03:08 +0000] "GET /dcim/sites/?region=france HTTP/1.0" 200 43681 "https://foo.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"

...
```

**Comment by atkrv** [comment]
BTW both Redis containers credentials are OK.

```
root@foo:~$ docker exec -it redis redis-cli -a fooboo -p 6379 ping
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
PONG
```

```
root@foo:~$ docker exec -it redis-cache redis-cli -a boofoo -p 6380 ping
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
PONG
```

**Comment by cimnine** [comment]
Usually I would close this issue, because you did not fill in the bug report template. (E.g. information about the Git revision.) For now I would like to ask you to test the `develop` branch, or least have a look at the changes of PR #245. It contains a fix about the Redis cache configuration.

**Comment by atkrv** [comment]
But I spent plenty of time tried to fill the issue according to the template :( I thought I drop only irrelevant  (optional) data..

The output of `git rev-parse HEAD`: `866a1c3bf2ce307cc0f805430be4efb09349adbc`

As for the Redis fixes in `develop` / #245 - some of them were quite obvious, so I've implemented those changes manually during the initial deploy. All of them configured on my site already but the issue persists anyway.

**Comment by cimnine** [comment]
Is this still an issue?

If it is, it would not be resolved by updating [to the recent release 0.23.0](https://github.com/netbox-community/netbox-docker/releases), would it?

Also, have you tried to re-create all the containers?

```bash
docker-compose down
docker-compose up --force-recreate
```

**Comment by cimnine** [comment]
No answer. Closing the issue.

**Comment by atkrv** [comment]
Hey 👋 

I'm so sorry, I completely forgot to report.

The updating resolved an issue in fact 🙂

Thanks!
