### ISSUE TITLE
Documentation on how to upgrade?

### ISSUE THREAD

**Issue by Mebus** [netbox-community/netbox-docker#269]
Hallo,

can you please document somewhere how I can upgrade the container?

Thanks

Mebus

**Comment by cimnine** [comment]
> **Do you have any questions?** Before opening an issue on Github, please join the Network To Code Slack and ask for help in our #netbox-docker channel.

That's about the 3rd and 4th sentence of the README.md.

> Please refer [to our wiki on Github](https://github.com/netbox-community/netbox-docker/wiki/) **for further information on how to use this Netbox Docker image properly**. It covers advanced topics such as using secret files, deployment to Kubernetes as well as NAPALM and LDAP configuration.

That's further down. In that wiki you'd find:

> [Troubleshooting](https://github.com/netbox-community/netbox-docker/wiki/Troubleshooting): Useful commands when something goes wrong, also covers basic backup techniques **and upgrading**.

Here's the direct link https://github.com/netbox-community/netbox-docker/wiki/Troubleshooting#how-to-upgrade.

Sorry for the tone, but I'm annoyed by spending my spare time on people who (a) don't stick to the issue template and (b) didn't seem to have bothered looking for documentation.

**Comment by Mebus** [comment]
Hallo cimnine,

upgrading doesn't belong in "Troubleshooting". And by the way netbox heavily breaks when I try to upgrade from 2.6 to 2.7. This should be handled automatically.

Mebus

**Comment by cimnine** [comment]
> upgrading doesn't belong in "Troubleshooting".

Anyone can edit the wiki. Feel free to improve it.

It's well known that updating from 2.6 to 2.7 requires some changes on your end. That's why the _How To Upgrade_ has this line:

> 💡 Read [the release notes](https://github.com/netbox-community/netbox-docker/releases). They include important update information.

**Comment by Mebus** [comment]
Sorry for being a stupid user.

I am on `tags/0.19.3` now. And I want to go to the latest release. So I need to do:

```
git pull origin/release
docker-compose rm -fs netbox netbox-worker
docker volume rm netbox-docker_netbox-static-files
docker-compose pull
docker-compose up -d netbox netbox-worker
```
?

Mebus

**Comment by cimnine** [comment]
> Do you have any questions?
Before opening an issue on Github, please join the [Network To Code][ntc-slack] Slack and ask for help in our [`#netbox-docker`][netbox-docker-slack] channel.


[github-stargazers]: https://github.com/netbox-community/netbox-docker/stargazers
[github-release]: https://github.com/netbox-community/netbox-docker/releases
[netbox-docker-microbadger]: https://microbadger.com/images/netboxcommunity/netbox
[netbox-dockerhub]: https://hub.docker.com/r/netboxcommunity/netbox/tags/
[netbox-docker-github]: https://github.com/netbox-community/netbox-docker/
[ntc-slack]: http://slack.networktocode.com/
[netbox-docker-slack]: https://slack.com/app_redirect?channel=netbox-docker&team=T09LQ7E9E
[netbox-docker-license]: https://github.com/netbox-community/netbox-docker/blob/release/LICENSE

If you need help, that is the place. Here is for bugs and feature requests.
