### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: REDIS section in configuration.py is missing the 'tasks' subsection.

### ISSUE THREAD

**Issue by Mebus** [netbox-community/netbox-docker#270]
Hallo,

after trying to upgrade to version 2.7 I get this error message:

```
netbox_1         |     self._wrapped = Settings(settings_module)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
netbox_1         |     mod = importlib.import_module(self.SETTINGS_MODULE)
netbox_1         |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
netbox_1         |     return _bootstrap._gcd_import(name[level:], package, level)
netbox_1         |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
netbox_1         |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
netbox_1         |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
netbox_1         |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
netbox_1         |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
netbox_1         |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
netbox_1         |   File "/opt/netbox/netbox/netbox/settings.py", line 193, in <module>
netbox_1         |     "REDIS section in configuration.py is missing the 'tasks' subsection."
netbox_1         | django.core.exceptions.ImproperlyConfigured: REDIS section in configuration.py is missing the 'tasks' subsection.
netbox_1         | ⏳ Waiting on DB... (27s / 30s)
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "./manage.py", line 10, in <module>
netbox_1         |     execute_from_command_line(sys.argv)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
netbox_1         |     utility.execute()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
netbox_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
netbox_1         |     self.execute(*args, **cmd_options)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
netbox_1         |     self.check()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
netbox_1         |     include_deployment_checks=include_deployment_checks,
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
netbox_1         |     issues = run_checks(tags=[Tags.database])
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
netbox_1         |     new_errors = check(app_configs=app_configs)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/database.py", line 9, in check_database_backends
netbox_1         |     for conn in connections.all():
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 216, in all
netbox_1         |     return [self[alias] for alias in self]
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 213, in __iter__
netbox_1         |     return iter(self.databases)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
netbox_1         |     res = instance.__dict__[self.name] = self.func(instance)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 147, in databases
netbox_1         |     self._databases = settings.DATABASES
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
netbox_1         |     self._setup(name)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
netbox_1         |     self._wrapped = Settings(settings_module)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
netbox_1         |     mod = importlib.import_module(self.SETTINGS_MODULE)
netbox_1         |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
netbox_1         |     return _bootstrap._gcd_import(name[level:], package, level)
netbox_1         |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
netbox_1         |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
netbox_1         |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
netbox_1         |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
netbox_1         |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
netbox_1         |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
netbox_1         |   File "/opt/netbox/netbox/netbox/settings.py", line 193, in <module>
netbox_1         |     "REDIS section in configuration.py is missing the 'tasks' subsection."
netbox_1         | django.core.exceptions.ImproperlyConfigured: REDIS section in configuration.py is missing the 'tasks' subsection.
netbox_1         | ❌ Waited 30s or more for the DB to become ready.
netbox-docker_netbox_1 exited with code 1
```

Mebus

**Comment by cimnine** [comment]
Is it too much to ask to follow the bug report template?

**Comment by manisha-tanwar** [comment]
@Mebus Did you find any solution for it?

**Comment by Mebus** [comment]
@manisha-tanwar No, didn't update nebox, because I don't have time at the moment to read tons of documentation to guess what I need to do. Let me know if you find a way that works reliable.

Mebus

**Comment by manisha-tanwar** [comment]
yeah it's really frustrating, Good Luck @Mebus !

**Comment by vdimko** [comment]
Try to copy 'tasks' section from /netbox/netbox/configuration.example.py to /netbox/netbox/configuration.py.
This worked in my case:

```
REDIS = {
        'tasks': {
                'host': 'localhost',
                'port': 6379,
                'password': '',
                'database': 0,
                'default_timeout': 300,
                'ssl': False,
        },
        'caching':{
            'HOST': 'localhost',
            'PORT': 6379,
            'PASSWORD': '',
            'DATABASE': 0,
            'CACHE_DATABASE': 1,
            'DEFAULT_TIMEOUT': 300,
            'SSL': False,
        }
}
```

**Comment by promeathus** [comment]
@vdimko that worked for me too. Thank you for posting that!

**Comment by DonovanEsterhuizen** [comment]
Hi i tried the above and I still get the same error.

Can anyone assist

Our Netbox is down at the moment

**Comment by DonovanEsterhuizen** [comment]
Im upgrading from 2.51 to 2.8

**Comment by DonovanEsterhuizen** [comment]
I was following the Option B: Clone the Git Repository to upgrade

**Comment by donovan-esterhuizen** [comment]
Hi

When i follow the upgrade documentation

Option B: Clone the Git Repository

This guide assumes that NetBox is installed at /opt/netbox. Pull down the most recent iteration of the master branch:

cd /opt/netbox
 git checkout master
 git pull origin master
 git status

Run the Upgrade Script

Once the new code is in place, verify that any optional Python packages required by your deployment (e.g. napalm or django-auth-ldap) are listed in local_requirements.txt. Then, run the upgrade script:

 ./upgrade.sh

I get the following error

Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 63, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/core/checks/database.py", line 9, in check_database_backends
    for conn in connections.all():
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/db/utils.py", line 222, in all
    return [self[alias] for alias in self]
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/db/utils.py", line 219, in __iter__
    return iter(self.databases)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 201, in <module>
    "REDIS section in configuration.py is missing the 'tasks' subsection."
django.core.exceptions.ImproperlyConfigured: REDIS section in configuration.py is missing the 'tasks' subsection.

When I look in my configuration.py file the REDIS is there

REDIS = {
    'tasks': {
        'HOST': 'localhost',
        'PORT': 6379,
        # Comment out `HOST` and `PORT` lines and uncomment the following if using Redis Sentinel
        # 'SENTINELS': [('mysentinel.redis.example.com', 6379)],
        # 'SENTINEL_SERVICE': 'netbox',
        'PASSWORD': '',
        'DATABASE': 0,
        'DEFAULT_TIMEOUT': 300,
        'SSL': False,
    },
    'caching': {
        'HOST': 'localhost',
        'PORT': 6379,
        # Comment out `HOST` and `PORT` lines and uncomment the following if using Redis Sentinel
        # 'SENTINELS': [('mysentinel.redis.example.com', 6379)],
        # 'SENTINEL_SERVICE': 'netbox',
        'PASSWORD': '',
        'DATABASE': 1,
        'DEFAULT_TIMEOUT': 300,
        'SSL': False,
    }
}

But i still get the error

**Comment by Mebus** [comment]
Meanwhile we fixed our netbox, so this issue is not relevant for me any longer.

Mebus

**Comment by krast-napoli** [comment]
> Try to copy 'tasks' section from /netbox/netbox/configuration.example.py to /netbox/netbox/configuration.py.
> This worked in my case:
> 
> ```
> REDIS = {
>         'tasks': {
>                 'host': 'localhost',
>                 'port': 6379,
>                 'password': '',
>                 'database': 0,
>                 'default_timeout': 300,
>                 'ssl': False,
>         },
>         'caching':{
>             'HOST': 'localhost',
>             'PORT': 6379,
>             'PASSWORD': '',
>             'DATABASE': 0,
>             'CACHE_DATABASE': 1,
>             'DEFAULT_TIMEOUT': 300,
>             'SSL': False,
>         }
> }
> ```

Hello, could you help me - I have seem problem, but there is no file configuration.py in Netbox2.9 project
