### ISSUE TITLE
Initializer for Custom Links?

### ISSUE THREAD

**Issue by creajoko** [netbox-community/netbox-docker#272]
Hi!
I am trying to find initializer for Custom Links, but I cannot find it.
Anyone knows?
Cheers,
Joakim

**Comment by cimnine** [comment]
> Do you have any questions?
> Before opening an issue on Github, please join the [Network To Code][ntc-slack] Slack and ask for help in our [`#netbox-docker`][netbox-docker-slack] channel.

You find an example for all the initializers we support in the [`initializers` folder](https://github.com/netbox-community/netbox-docker/tree/release/initializers). Feel free to open a pull request for additional implementations. You find the implementations in the [`startup_scripts` folder](https://github.com/netbox-community/netbox-docker/tree/release/startup_scripts).

[github-stargazers]: https://github.com/netbox-community/netbox-docker/stargazers
[github-release]: https://github.com/netbox-community/netbox-docker/releases
[netbox-docker-microbadger]: https://microbadger.com/images/netboxcommunity/netbox
[netbox-dockerhub]: https://hub.docker.com/r/netboxcommunity/netbox/tags/
[netbox-docker-github]: https://github.com/netbox-community/netbox-docker/
[ntc-slack]: http://slack.networktocode.com/
[netbox-docker-slack]: https://slack.com/app_redirect?channel=netbox-docker&team=T09LQ7E9E
[netbox-docker-license]: https://github.com/netbox-community/netbox-docker/blob/release/LICENSE
