### ISSUE TITLE
Rack links malformed

### ISSUE THREAD

**Issue by lopuk** [netbox-community/netbox-docker#282]
When running behind a reverse proxy everything works great with the exception of viewing existing items in racks.

When trying to view an item by clicking on it in the rack diagram the URL shows as: http://netbox.domain.com:443/dcim/devices/1/

All other links (including adding devices to the rack on the same page) are shown in the correct format of: https://netbox.domain.com/dcim/racks/

Obviously manually updating the URL to the correct format then shows the correct page. Would this be a code/config issue within the netbox-docker image itself?

**Comment by cimnine** [comment]
https://github.com/netbox-community/netbox-docker/issues/292 seems to be the same issue. Since that one uses the correct bug reporting template, I'm going to close this one here.
