### ISSUE TITLE
Quickstart instructions incorrect

### ISSUE THREAD

**Issue by kpblom** [netbox-community/netbox-docker#286]
> Quickstart
> ...
> _tee **netbox-docker.override.yml** <<EOF_
> version: '3.4'
> services:
>   nginx:
>     ports:
>       - 8000:8080
> EOF
> ..

should be:
tee **docker-compose.override.yml** <<EOF

Following the instructions on the wiki has the correct information that works but not the "frontpage" README.md

**Comment by weisdd** [comment]
@kpblom +1 I've encountered the same.
I think the author of README.md has a local .env file (not present in the repo), which specifies an alternative name for the override file (netbox-docker.override.yml).

**Comment by cimnine** [comment]
Already fixed in https://github.com/netbox-community/netbox-docker/pull/279
