### ISSUE TITLE
Having an issue with the database.

### ISSUE THREAD

**Issue by vsantiago113** [netbox-community/netbox-docker#287]
I am getting the error below on the container named "netbox-docker_netbox_1"

netbox_1         | The above exception was the direct cause of the following exception:
netbox_1         |
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "./manage.py", line 10, in <module>
netbox_1         |     execute_from_command_line(sys.argv)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
netbox_1         |     utility.execute()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
netbox_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
netbox_1         |     self.execute(*args, **cmd_options)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
netbox_1         |     output = self.handle(*args, **options)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
netbox_1         |     res = handle_func(*args, **kwargs)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 86, in handle
netbox_1         |     executor = MigrationExecutor(connection, self.migration_progress_callback)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
netbox_1         |     self.loader = MigrationLoader(self.connection)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
netbox_1         |     self.build_graph()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
netbox_1         |     self.applied_migrations = recorder.applied_migrations()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
netbox_1         |     if self.has_table():
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
netbox_1         |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
netbox_1         |     return func(*args, **kwargs)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 260, in cursor
netbox_1         |     return self._cursor()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 236, in _cursor
netbox_1         |     self.ensure_connection()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
netbox_1         |     return func(*args, **kwargs)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
netbox_1         |     self.connect()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
netbox_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
netbox_1         |     self.connect()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
netbox_1         |     return func(*args, **kwargs)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
netbox_1         |     self.connection = self.get_new_connection(conn_params)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
netbox_1         |     return func(*args, **kwargs)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
netbox_1         |     connection = Database.connect(**conn_params)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
netbox_1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
netbox_1         | django.db.utils.OperationalError: could not connect to server: Host is unreachable
netbox_1         |      Is the server running on host "postgres" (172.18.0.2) and accepting
netbox_1         |      TCP/IP connections on port 5432?
netbox_1         |
netbox_1         | ❌ Waited 30s or more for the DB to become ready.

================================================================

Then I am getting the following error on the container named "netbox-docker_netbox-worker_1"

Error 113 connecting to redis:6379. Host is unreachable.

**Comment by liviozanol** [comment]
Hi, I was having a similar issue.

In my case, it was related to old volumes containing old postgres version files (docker volume ls). After stoping and removing the containers I was able to remove the volumes and 'docker-compose pull/up', everything was fine.

**Comment by vsantiago113** [comment]
I thought I tried that, let me check again.

**Comment by vsantiago113** [comment]
The issue I was having was related to the VMware Workstation where I am running CentOS and Docker. I tried in a physical server and it works fine. Thanks.

**Comment by mattdujardin** [comment]
I am getting the same issue.

**Comment by ghost** [comment]
In case anyone else is having this issue, I found updating docker-compose from 1.27 to 1.28.2 fixed it for me.
