### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by tsvsj** [netbox-community/netbox-docker#288]
Is there any kind of plugin support for the docker version of Netbox? There is no plugin directory and even no plugin directive within the configuration.py. 

To support community plugins there need to be a way to install those plugins within the container. Any ideas?

**Comment by cimnine** [comment]
Please use the respective feature request issue template.

It should be straight-forward to extend the netbox-docker Docker container with plugins. See https://github.com/netbox-community/netbox-docker/wiki/Build#enhance-the-image for the basics.

See also the LDAP stage in our `Dockerfile` to learn how you can extend the `configuration.py` file: https://github.com/netbox-community/netbox-docker/blob/release/Dockerfile#L117-L125
