### ISSUE TITLE
Email Environment Variables

### ISSUE THREAD

**Issue by minitriga** [netbox-community/netbox-docker#293]
## Desired Behavior

Add environment variables for the new configuration that has been implemented within 2.8.4 
https://github.com/netbox-community/netbox/issues/4632

## Contrast to Current Behavior
Add SSL and TLS Email support

## Changes Required
Implement environment variables for SSL and TLS and change config file to look for these variables. 

...

## Discussion: Benefits and Drawbacks

Everyone can use SSL and TLS. In my case, this is preventing me from using Gmail smtp.

**Comment by cimnine** [comment]
Thanks you for bringing this to our attention. Currently we have limited capacity adding this ourselves. But we're happy to review and merge a respective PR.

The relevant commit in Netbox for further reference:
https://github.com/netbox-community/netbox/commit/569d4ee201bb61d0310283014cbe7a9a3d10f04f

**Comment by minitriga** [comment]
@cimnine of course. I implemented this locally. Let me push the changes I made.

**Comment by cimnine** [comment]
This will be in the next release. I therefore close the issue. Once again, thanks for the PR.
