### ISSUE TITLE
Wrong override compose file name in README.md

### ISSUE THREAD

**Issue by addtzg** [netbox-community/netbox-docker#297]
In README.md filename for overriding nginx port is **netbox-docker.override.yml** and in the wiki is **docker-compose.override.yml**. The second one is the proper one so the one in README should be changed.

--
Oh sorry, I see it's fixed in develop already, my bad. I think it should be pushed as fast as possible because README.md it's the first thing you read on docker hub. IMHO it's a really bad first impression when you can't even start it using tips from readme. Probably this issue should be linked to #279  and closed when the new version will be released.

**Comment by addtzg** [comment]
Oh sorry, I see it's fixed in develop already, my bad. I think it should be pushed as fast as possible because README.md it's the first thing you read on docker hub. IMHO it's a really bad first impression when you can't even start it using tips from readme.

**Comment by cimnine** [comment]
Since the README.md is not linked to the Docker Hub page anyway, I was able to fix it there. I'll therefore close this issue. Our next release is in preparation and should be ready soon-ish.

**Comment by addtzg** [comment]
Sure, it's great that instruction is fixed on Docker hub.
