### ISSUE TITLE
Add plugin guidance to documentation.

### ISSUE THREAD

**Issue by karrots** [netbox-community/netbox-docker#300]
## Desired Behavior

Documentation about best practices for interacting with plugins via docker containers
...

## Contrast to Current Behavior

No documentation.
...

## Changes Required

Documentation written
...

## Discussion: Benefits and Drawbacks

Plugins are new but questions of this nature will start coming in.

**Comment by james-powis** [comment]
I for one would like to know how to use netbox-docker to help develop a plugin locally...

**Comment by cimnine** [comment]
A specific guide would of course be nice. Until then find the basics to achieve that [in the wiki on the _Build_ page in the _Enhance the Image_ section](../wiki/Build#enhance-the-image).

PS: Anyone can edit the wiki. Feel free to add a guide once you've figured it out. Also feel free to ask in our Slack channel if you need help.

**Comment by karrots** [comment]
Yea the trick is plugins have to be added to the top build stage so the dependencies are built and copied into the main image.

**Comment by cimnine** [comment]
Do you mean Python packages with _the dependencies_? If so, they can IMO be installed the same way in the extension image as we do it in the main image:

```Dockerfile
##
# Build Stage
##

# make sure this is the same python image as used in Netbox Docker
# also make sure it's a `-alpine` image.
FROM python:3.7-alpine as builder

WORKDIR /install

COPY plugin_requirements.txt /
RUN pip install --prefix="/install" --no-warn-script-location -r /plugin_requirements.txt

##
# Main Stage
##
FROM netboxcommunity/netbox as main

COPY --from=builder /install /usr/local

COPY plugin /opt/netbox/netbox/...
```

(Disclaimer: The above snippet is straight out of my head and may not work as it is. But it should illustrate the general direction.)

**Comment by karrots** [comment]
Yes this is what I did.

**Comment by cimnine** [comment]
Netbox Docker user @minitriga was kind enough to document his Netbox Plugin setup in our wiki, hence I close this issue.

See https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins for more information. Also feel free to enhance the documentation if you feel like it is missing something important.
