### ISSUE TITLE
Installing netbox in docker Ubuntu 20

### ISSUE THREAD

**Issue by Abed1985** [netbox-community/netbox-docker#302]
Any ideas? while running netbox docker on an ubuntu20
`
root@ubuntu-dockers:/home/aalakhras/projects/netbox-docker# docker-compose logs -f
Attaching to netbox-docker_nginx_1, netbox-docker_netbox_1, netbox-docker_netbox-worker_1, netbox-docker_redis-cache_1, netbox-docker_postgres_1, netbox-docker_redis_1
nginx_1          | 2020/05/24 23:45:51 [emerg] 1#1: open() "/etc/nginx/mime.types" failed (13: Permission denied) in /etc/netbox-nginx/nginx.conf:11
nginx_1          | nginx: [emerg] open() "/etc/nginx/mime.types" failed (13: Permission denied) in /etc/netbox-nginx/nginx.conf:11
netbox_1         | /bin/bash: /opt/netbox/docker-entrypoint.sh: Permission denied
netbox-docker_nginx_1 exited with code 1
netbox-docker_netbox_1 exited with code 126
netbox-worker_1  | Error loading shared library libpython3.7m.so.1.0: No such file or directory (needed by /usr/local/bin/python3)
netbox-worker_1  | Error relocating /usr/local/bin/python3: _Py_UnixMain: symbol not found
netbox-docker_netbox-worker_1 exited with code 127
redis-cache_1    | /bin/sh: can't open '/usr/local/bin/docker-entrypoint.sh': Permission denied
redis-cache_1    | /bin/sh: can't open '/usr/local/bin/docker-entrypoint.sh': Permission denied
netbox-docker_redis-cache_1 exited with code 2
postgres_1       | bash: /usr/local/bin/docker-entrypoint.sh: Permission denied
postgres_1       | bash: /usr/local/bin/docker-entrypoint.sh: Permission denied
netbox-docker_postgres_1 exited with code 126
redis_1          | /bin/sh: can't open '/usr/local/bin/docker-entrypoint.sh': Permission denied
redis_1          | /bin/sh: can't open '/usr/local/bin/docker-entrypoint.sh': Permission denied
netbox-docker_redis_1 exited with code 2
`

**Comment by cimnine** [comment]
Please fill in the issue template if you think this is a bug. Otherwise you may seek help in the `#netbox-docker` channel of the NetworkToCode Slack server. All information can be found in the readme.
