### ISSUE TITLE
Not able to install plugin in running Netbox docker.

### ISSUE THREAD

**Issue by Minal1409** [netbox-community/netbox-docker#315]
I have a Netbox running in server. Now that Netbox onboarding plugin is available. I want to just install this plugin in already running netbox.

Steps Followed-

Pip install plugin-name <plugin-name> inside Netbox container
configuration file already had netbox plugin included in list
docker restarted
But no plugin displayed in UI nor any plugin code visible inside docker container

**Comment by cimnine** [comment]
Please [follow the guide](https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins) or ask in our Slack channel. Thanks.

**Comment by jaheshkhan** [comment]
> Please [follow the guide](https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins) or ask in our Slack channel. Thanks.

I tried that. but its always ended up saying the /opt/netbox/venv/bin is not available?

where can i find that? why its not showing...
the guide is not mentioning anything about it as if we know the missing piece.

**Comment by cimnine** [comment]
Is the `netboxcommunity/netbox:latest` image in your local Docker image cache recent? Try `docker pull netboxcommunity/netbox:latest`.

If that doesn't to the trick, please start [a new discussion](https://github.com/netbox-community/netbox-docker/discussions), ask [in our Slack channel](https://join.slack.com/t/netdev-community/shared_invite/zt-mtts8g0n-Sm6Wutn62q_M4OdsaIycrQ) `#netbox-docker` or open a new bug report.
