### ISSUE TITLE
netbox_1 do not connect error 

### ISSUE THREAD

**Issue by davidbunny** [netbox-community/netbox-docker#321]
Hi everybody, 

I did the steps to put netbox on by docker-compose on CentOS 7 and I got this error on docker-compose logs:

netbox_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
netbox_1         |     self.execute(*args, **cmd_options)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
netbox_1         |     output = self.handle(*args, **options)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
netbox_1         |     res = handle_func(*args, **kwargs)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 86, in handle
netbox_1         |     executor = MigrationExecutor(connection, self.migration_progress_callback)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
netbox_1         |     self.loader = MigrationLoader(self.connection)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
netbox_1         |     self.build_graph()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
netbox_1         |     self.applied_migrations = recorder.applied_migrations()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
netbox_1         |     if self.has_table():
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
netbox_1         |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
netbox_1         |     return func(*args, **kwargs)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 260, in cursor
netbox_1         |     return self._cursor()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 236, in _cursor
netbox_1         |     self.ensure_connection()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
netbox_1         |     return func(*args, **kwargs)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
netbox_1         |     self.connect()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
netbox_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
netbox_1         |     self.connect()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
netbox_1         |     return func(*args, **kwargs)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
netbox_1         |     self.connection = self.get_new_connection(conn_params)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
netbox_1         |     return func(*args, **kwargs)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
netbox_1         |     connection = Database.connect(**conn_params)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
netbox_1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
netbox_1         | django.db.utils.OperationalError: could not connect to server: Host is unreachable
netbox_1         |      Is the server running on host "postgres" (172.23.0.3) and accepting
netbox_1         |      TCP/IP connections on port 5432?
netbox_1         |
netbox_1         | ⏳ Waiting on DB... (3s / 30s)

Can someone help me ?

**Comment by cimnine** [comment]
Please use our Slack channel to ask questions or fill in a proper bug report, i.e. use the provided template.
