### ISSUE TITLE
Enable napalm config sanitize

### ISSUE THREAD

**Issue by dimm0** [netbox-community/netbox-docker#322]
## Current Behavior

Trying all combinations of parameters to use the sanitized config in napalm. How can I pass it? (seems like it's now added to napalm, https://github.com/napalm-automation/napalm/commit/5003cfcffaef439ceebd278478a2a2f96d0cfbe3)

## Expected Behavior

Using sanitized config in Napalm is documented

**Comment by cimnine** [comment]
Thank you for feature request. As I'm not a user of Napalm myself, it's hard to understand exactly what you requested. Please stick to the feature request template. If you know what to do, you're also very welcome to propose a PR.
