### ISSUE TITLE
Support for 2.9.x series

### ISSUE THREAD

**Issue by olafz** [netbox-community/netbox-docker#325]
Recently, the Netbox 2.9.x series [was released](https://github.com/netbox-community/netbox/releases). However, these do not show up at https://hub.docker.com/r/netboxcommunity/netbox/tags (yet?). Is there something that needs to be added/changed to support these series? I'm happy to help if needed.

## Current Behavior
There are no 2.9.x. versions of Netbox at https://hub.docker.com/r/netboxcommunity/netbox/tags

## Expected Behavior
2.9.x. versions of Netbox become automatically available at https://hub.docker.com/r/netboxcommunity/netbox/tags

**Comment by tobiasge** [comment]
This is a problem with some of the `startup_scripts` which are not compatible with  Netbox 2.9. Because of this the tests in the automated build are failing and the image is not pushed to Docker Hub.

I'm currently working on a solution for this.

**Comment by tobiasge** [comment]
The new release [0.25.0](https://github.com/netbox-community/netbox-docker/releases/tag/0.25.0) has been published.
Images for Netbox 2.9.x should be build in a few moments.
