### ISSUE TITLE
Maintainers Wanted

### ISSUE THREAD

**Issue by cimnine** [netbox-community/netbox-docker#334]
## Desired Behavior

There are more maintainers sharing the maintenance load that Netbox Docker project creates. This includes:

- Dispatch Issues
- Resolve Bugs
- Implement Featurs
- Review community contributions (aka PRs)
- Help out on our Slack channel

## Contrast to Current Behavior

Currently, @tobiasge and I are the only maintainers for this project. Tobias is using the Netbox Docker image at least on the job, me not so much anymore. We're both Europe-based, which means we're not active when our American or Asian friends are.

## Changes Required

Probably more formal communication structures and some _behind-the-scenes_-documentation.

## Discussion: Benefits and Drawbacks

More maintainers will mean more coordination effort. But I hope it would also result in more prompt feedback to issues and PRs.

I would love more maintainers on this project. But I would like to see some involvement first, e.g. quality comments on issues, helping out people on Slack or quality PRs. Currently I don't see it, but I may be blind!

**If you think you are qualified to help us out, please reach out to @cimnine or @tobiasge on Slack.** Please state your motivation, your affiliations and provide some reference contributions (issues, PRs, comments, Slack-messages, ...), either to this project – or any other.

Minimal qualifications:

- You are able to read and write in English
- You are committed to stay on-board for at least year (plans may change, but that should be your minimal goal)
- You know Docker
- You know Netbox

Ideally you also know something about Python, Django, Bash-scripting, Github Actions and you're good in dealing with people, especially beginners.

**Comment by n4zmz** [comment]
I’ve built a Raspberry Pi4 image but do not have permissions to update the image on docker hub.  Can I get permission or get the automated build to include aarch64?

**Comment by cimnine** [comment]
> Can I get permission or get the automated build to include aarch64?

This is really cool. We're building using Github Actions. You find the code in [`.github/workflows`](https://github.com/netbox-community/netbox-docker/tree/release/.github/workflows). Feel free to create a pull-request that adds a build of the Docker image for other CPU architectures, such as _aarch64_.

But we won't allow anyone to manually push to the Docker registry, as that would open up the door to potential manipulation.

If you have any questions regarding our build system, please continue the discussion in another issue, in your PR or join our [#netbox-docker Slack](https://networktocode.slack.com/archives/CD23LP8BC).

**Comment by cimnine** [comment]
> Can I get permission or get the automated build to include aarch64?

This is really cool. We're building using Github Actions. You find the code in [`.github/workflows`](https://github.com/netbox-community/netbox-docker/tree/release/.github/workflows). Feel free to create a pull-request that adds a build of the Docker image for other CPU architectures, such as _aarch64_.

But we won't allow anyone to manually push to the Docker registry, as that would open up the door to potential manipulation.

If you have any questions regarding our build system, please continue the discussion in another issue, in your PR or join our [#netbox-docker Slack](https://networktocode.slack.com/archives/CD23LP8BC).
