### ISSUE TITLE
Type Error If AUTH_LDAP_MIRROR_GROUPS is not set

### ISSUE THREAD

**Issue by SyraD** [netbox-community/netbox-docker#363]
Default field of None throws error. Default needs to be a string if .lower() is called, likely want to default to 'False' given the comments. https://github.com/netbox-community/netbox-docker/commit/20820e10c25a833c9d9d71cb66472d85e35bf5c0#commitcomment-44352504 

Sorry to be brief but wanted to mark before I forget. Will try to come back later and be more thorough.

**Comment by cimnine** [comment]
Thank you for bringing this to our attention. Fortunately this has been fixed in the meantime, see https://github.com/netbox-community/netbox-docker/blob/dcb3b5495d3d0a437f09f5a5df1e23760cd1c603/configuration/ldap/ldap_config.py#L77
