### ISSUE TITLE
Main configuration '/etc/netbox/config/configuration.py' not found.

### ISSUE THREAD

**Issue by hawk291** [netbox-community/netbox-docker#364]
Hi, while deploying netbox on Ubuntu 20.04 VM on proxmox, have some errors related to missing config files
`File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
netbox_1         |     return _bootstrap._gcd_import(name[level:], package, level)
netbox_1         |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
netbox_1         |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
netbox_1         |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
netbox_1         |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
netbox_1         |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
netbox_1         |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
netbox_1         |   File "/opt/netbox/netbox/netbox/settings.py", line 40, in <module>
netbox_1         |     from netbox import configuration
netbox_1         |   File "/opt/netbox/netbox/netbox/configuration.py", line 67, in <module>
netbox_1         |     _loaded_configurations = read_configurations(
netbox_1         |   File "/opt/netbox/netbox/netbox/configuration.py", line 55, in read_configurations
netbox_1         |     raise ImportError(f"No configuration files found in '{config_dir}'.")
netbox_1         | ImportError: No configuration files found in '/etc/netbox/config/'.
netbox_1         | ❌ Waited 30s or more for the DB to become ready.
netbox-docker_netbox_1 exited with code 1
`

**Comment by cimnine** [comment]
Thank you for your interest in Netbox Docker. Please fill in the entire bug report template so that we can help you quickly.
