### ISSUE TITLE
Default admin user is re-created after deletion

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [netbox-community/netbox-docker#366]
This can probably be considered as a security issue, since that behavior is not documented enough in my opinion. Deleting the `admin` user that was used for bootstraping (ironically, probably for additional security) while having removed the `SUPERUSER_*` variables probably happened to a few people out there. Especially since the issue only arises after a container reboot.

## Desired Behavior

1. Follow [Getting Started](https://github.com/netbox-community/netbox-docker/wiki/Getting-Started), probably with a strong `SUPERUSER_PASSWORD`.
2. Follow [Configure for Production](https://github.com/netbox-community/netbox-docker/wiki/Configuration#operations), notably drop the `SUPERUSER_*` variables
3. Create other admin users (maybe with LDAP), and **remove** the `admin` one
4. Have the `netbox` container to reboot
5. The admin user and associated token(s) stays deleted.

## Contrast to Current Behavior

5. The `admin` user is back, with the default password and default token, creating an unexpected security hole. 

## Changes Required

Either one of the following:

1. Explicitely document that the `admin` (or whatever `SUPERUSER_NAME` is set to) user will be recreated if deleted unless `SKIP_SUPERUSER` is set.
2. Ensure the admin user is not created twice

## Discussion: Benefits and Drawbacks

Benefits:

- Probably less deployment with `admin`/`admin` credentials

Drawbacks with proposed change 1.:

- More verbose documentation

Drawbacks with proposed change 2.:

- Complex to implement
- Might be a desired behaviour

**Comment by cimnine** [comment]
Thank you for bringing this to our attention. Also thanks for sticking (mostly) to the template, making it very easy to understand your concern. I've changed the relevant wiki page [Configuration](https://github.com/netbox-community/netbox-docker/wiki/Configuration) to mention the `SKIP_SUPERUSER` variable.

I believe this adequately addresses your concern. What do you think?

PS: Our Wiki is a community wiki. Everyone is invited to improve it :)

**Comment by GeoffreyFrogeye** [comment]
I just had a look, this should be enough, especially since it's after `SUPERUSER_*`. Thanks you!

> PS: Our Wiki is a community wiki. Everyone is invited to improve it :)

Indeed, I just wanted to see which option you wanted to go with first.
