### ISSUE TITLE
Issue with NGINX - Error Code 1

### ISSUE THREAD

**Issue by rarodrigo** [netbox-community/netbox-docker#367]
Hello Team,

This issue is same related with [Docker Issue](https://github.com/netbox-community/netbox-docker/issues/22).

For me situation the logs are:
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration,
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/,
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh,
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf,
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf,
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh,
/docker-entrypoint.sh: Configuration complete; ready for start up,
2020/12/14 13:58:05 [emerg] 1#1: host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:29,
nginx: [emerg] host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:29,

**Docker Compose**
docker-compose version 1.25.5, build unknown

Is there any another recommedation about it?

**Comment by cimnine** [comment]
Please see our Slack channel or the newly available [_Discussions_ section](https://github.com/netbox-community/netbox-docker/discussions) to ask questions. If you believe you've found a bug, then please stick to our bug report template.
