### ISSUE TITLE
Database Table updated from backend using GUI client using Import/export. but pointer to primary key is not updated for new entries. Error is displayed given primary key already present in DB. It should automatically take the next Id , why it is resetting to 1. New instance was created as server crashed

### ISSUE THREAD

**Issue by Minal1409** [netbox-community/netbox-docker#382]
## Current Behavior

Database Table updated from backend using postgres client. but pointer to primary key is not updated for new entries. Error is displayed given primary key already present in DB. It should automatically take the next Id , why it is resetting to 1

## Expected Behavior

Database Table updated from backend. but pointer to primary key should not conflict with already existing data in DB.

Debug

Creating a new entry from GUI gives error that given primary key is already present in database

**Comment by cimnine** [comment]
I'm sorry, we can't help you unless you fill in all (at least most) of the information we ask for in the bug report template.
