### ISSUE TITLE
Expand Initializers Support

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox-docker#383]
## Desired Behavior

Add support for startup scripts to load all data Netbox supports.

## Contrast to Current Behavior

I think only the circuits models are not supported.  IE CircuitType, Circuit, CircuitTermination, Provider.

## Changes Required

Create startup scripts and initializer yamls for the missing models.

## Discussion: Benefits and Drawbacks

Benefits include a more complete set of initializers that NetBox supports.  This allows developers, testers, and prod deployments to more fully leverage initializers for getting a deployment up and running.

Drawbacks really are the same as any startup script included in this project, IE that the project needs to update to match the  data model and that its all not necessarily within the core function of what the docker project is focused on.

**Comment by ryanmerolle** [comment]
I have a PR coming but, the most obvious missing initializers & startup scripts are 
**Easy or ROI**(I will check off what I have completed):

- [x] Tags
- [x] Secret Roles
- [x] Cluster Groups
- [x] Providers
- [x] CircuitTypes
- [x] Circuits
- [x] PowerPanels
- [x] PowerFeeds
- [x] Route Target
- [x] Service

**May not be worth the ROI**(Feel free to comment if these should be included):

- Secrets (not something I think would get used since it defeats the purpose to save in clear text, but may be useful for loading test data)
- Rack Reservations (Easy to add, but the model requires a user, would need to pass the admin user environment var)
- CableTermination
- CircuitTermination
- Other (not CableTermination) Device Component models (should mostly be handled by device types being predefined)
- Cables Model
- Device Component Templates models

Assuming @cimnine and @tobiasge are ok with this all, I would look reorder the existing startup_scripts to execute in order based on the new startup_scripts I would create.

**Comment by cimnine** [comment]
Secrets are about to be deprecated anyway afaik. I'd leave the other items to whoever needs them first ;)

**Comment by cimnine** [comment]
Since we've merged your PR and will release your changed in the next release, I'm closing this issue. Once more, thank you for your effort.
