### ISSUE TITLE
Update 2.9.11 -> 2.10.1

### ISSUE THREAD

**Issue by RHuehne** [netbox-community/netbox-docker#400]
- I have a netbox-docker-Version 0.26.2 with Netbox 2.9.11 up and running OK. (upgraded from 2.8.6)
- Now I want to go to 2.10.
- I downloaded netbox-docker-0.27.0 and extracted it to /opt
- As I am using volumes with relational path I copy the volumes folder from 0.26.2 to 0.27.0.
- I updated the new docker-compose.yml to my needs (volume path, pg version)
- I set the $VERSION variable from v2.9 to v.2.10

## Current Behavior

netbox_1 exited with code 1

## Expected Behavior

Netbox 2.10 should come up and runs
...

## Debug Information

The output of `docker-compose version`: `1.17.1, build unknown`
The output of `docker version`: `19.03.12, build 48a66213fe`

The output of `docker inspect netboxcommunity/netbox:latest --format "{{json .Config.Labels}}"`:

{"BUILD_REASON":"python","NETBOX_GIT_BRANCH":"HEAD","NETBOX_GIT_REF":"2c1a60b965d7778791f4ccce8d6f06a189ed34d1","NETBOX_GIT_URL":"https://github.com/netbox-community/netbox.git","ORIGINAL_TAG":"docker.io/netboxcommunity/netbox:v2.10.1","com.docker.compose.config-hash":"531776c16abf37706a829db59628211581c65c9436179446350f2b783aa6371c","com.docker.compose.container-number":"1","com.docker.compose.oneoff":"False","com.docker.compose.project":"netboxdocker0270","com.docker.compose.service":"netbox-worker","com.docker.compose.version":"1.17.1","org.label-schema.build-date":"2020-12-18T05:51+00:00","org.label-schema.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.","org.label-schema.name":"Netbox Docker","org.label-schema.schema-version":"1.0","org.label-schema.url":"https://github.com/netbox-community/netbox-docker","org.label-schema.usage":"https://github.com/netbox-community/netbox-docker/wiki","org.label-schema.vcs-ref":"aa4d630a0fa423c757635cdb95f97e3389bb6ff4","org.label-schema.vcs-url":"https://github.com/netbox-community/netbox-docker.git","org.label-schema.vendor":"The netbox-docker contributors.","org.label-schema.version":"0.27.0","org.opencontainers.image.authors":"The netbox-docker contributors.","org.opencontainers.image.created":"2020-12-18T05:51+00:00","org.opencontainers.image.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.","org.opencontainers.image.documentation":"https://github.com/netbox-community/netbox-docker/wiki","org.opencontainers.image.licenses":"Apache-2.0","org.opencontainers.image.revision":"aa4d630a0fa423c757635cdb95f97e3389bb6ff4","org.opencontainers.image.source":"https://github.com/netbox-community/netbox-docker.git","org.opencontainers.image.title":"Netbox Docker","org.opencontainers.image.url":"https://github.com/netbox-community/netbox-docker","org.opencontainers.image.vendor":"The netbox-docker contributors.","org.opencontainers.image.version":"0.27.0"}

The output of `docker-compose logs netbox`:

netbox_1         |   No migrations to apply.
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1         | 💡 Superuser Username: admin, E-Mail: admin@example.com
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/000_users.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/010_groups.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/020_custom_fields.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/030_regions.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/040_sites.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/050_manufacturers.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/060_device_types.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/070_rack_roles.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/075_rack_groups.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/080_racks.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/090_device_roles.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/100_platforms.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/110_tenant_groups.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/120_tenants.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/130_devices.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/140_cluster_types.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/150_rirs.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/160_aggregates.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/170_clusters.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/180_vrfs.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/190_prefix_vlan_roles.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/200_vlan_groups.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/210_vlans.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/220_prefixes.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/230_virtual_machines.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/240_virtualization_interfaces.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/250_dcim_interfaces.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/260_ip_addresses.py
netbox_1         | ▶️ Running the startup script /opt/netbox/startup_scripts/270_primary_ips.py
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "/opt/netbox/netbox/./manage.py", line 10, in <module>
netbox_1         |     execute_from_command_line(sys.argv)
netbox_1         |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
netbox_1         |     utility.execute()
netbox_1         |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
netbox_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1         |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
netbox_1         |     self.execute(*args, **cmd_options)
netbox_1         |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
netbox_1         |     output = self.handle(*args, **options)
netbox_1         |   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 194, in handle
netbox_1         |     collected = self.collect()
netbox_1         |   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 118, in collect
netbox_1         |     handler(path, prefixed_path, storage)
netbox_1         |   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 355, in copy_file
netbox_1         |     self.storage.save(prefixed_path, source_file)
netbox_1         |   File "/usr/local/lib/python3.9/site-packages/django/core/files/storage.py", line 52, in save
netbox_1         |     return self._save(name, content)
netbox_1         |   File "/usr/local/lib/python3.9/site-packages/django/core/files/storage.py", line 267, in _save
netbox_1         |     fd = os.open(full_path, self.OS_OPEN_FLAGS, 0o666)
netbox_1         | PermissionError: [Errno 13] Permission denied: '/opt/netbox/netbox/static/js/tableconfig.js'
netbox_1 exited with code 1

**Comment by tobiasge** [comment]
The problem seems to be the file permissions on the static files share.
This will be fixed with the upcoming version 0.28.0 (See #394) because then the static files are collected at container build time.
