### ISSUE TITLE
Receiving "The connection was reset" on mac 10.15.6 ( catalina )

### ISSUE THREAD

**Issue by layer7gmbh** [netbox-community/netbox-docker#404]
Hi, 

using mac + docker desktop:

<img width="1450" alt="Screenshot 2021-01-27 at 20 57 18" src="https://user-images.githubusercontent.com/52083968/106046054-0e140300-60e2-11eb-9134-187af09383cf.png">

I changed the port to 1234, just to check if anything changes.

But from the browser i just receive:

```
The connection was reset
```

in configuration.py i tried: ALLOWED_HOSTS = ['127.0.0.1']

in netbox.env i tried: ALLOWED_HOSTS=localhost ::1 127.0.0.1 0.0.0.0

Its no difference.

![Screenshot 2021-01-27 at 20 59 44](https://user-images.githubusercontent.com/52083968/106046351-6fd46d00-60e2-11eb-83eb-b942de8bc8df.png)

Any suggestion ?

Thank you and stay healthy :)
Greetings
Oliver

**Comment by cimnine** [comment]
Please use [our discussions](https://github.com/netbox-community/netbox-docker/discussions) to ask question. Issues are for feature requests or bug reports.

If this were a bug report or feature request, please use our template.

PS: You've changed the port of the Netbox container. This will not work. Please follow [the Getting Started guide](https://github.com/netbox-community/netbox-docker/wiki/Getting-Started) to learn how to change the port properly.
