### ISSUE TITLE
Binary operator expected

### ISSUE THREAD

**Issue by alexanderfefelov** [netbox-community/netbox-docker#412]
From the `docker logs netbox` output:

```
✅ Initialisation is done.
/opt/netbox/launch-netbox.sh: line 10: [: -gte: binary operator expected
⏳ Waiting for control socket to be created... (1/10)
```

https://github.com/netbox-community/netbox-docker/blob/ed6256172fd6242e7d9f4b07f6a00b8ba9dc5fbc/docker/launch-netbox.sh#L9-L11

**Comment by cimnine** [comment]
Unfortunately we can not help you if you can't tell us which version your using. I.e. please fill in the bug report template.

**Comment by tobiasge** [comment]
I know where the error is coming from. I have prepared a fix.
