### ISSUE TITLE
"ModuleNotFoundError: No module named 'django'"

### ISSUE THREAD

**Issue by buliwyf42** [netbox-community/netbox-docker#422]
Hello,

i deployed Netbox via docker compose last week. I was able to access Netbox and add Devices, Networks and Racks. 
During the weekend watchtower updated the "netbox-docker_netbox-worker_1" Container.
Since then the Container won't start.
The Output of the Log is:
`Traceback (most recent call last):

  File "/opt/netbox/netbox/manage.py", line 8, in <module>

    from django.core.management import execute_from_command_line

ModuleNotFoundError: No module named 'django'`

Today i redeployed the whole system but the error stayed the same. 

Any Idea how to resolve this Issue?

**Comment by cimnine** [comment]
Please use [discussions](https://github.com/netbox-community/netbox-docker/discussions) for questions. Otherwise we ask to fill in a complete bug report.

**Comment by buliwyf42** [comment]
Sorry i found the error and resolved the issue. Next time i will post to discussions.

**Comment by gmallapp** [comment]
@buliwyf42 How did you resolve this error? I'm getting the same error

**Comment by buliwyf42** [comment]
> @buliwyf42 How did you resolve this error? I'm getting the same error

This was an issue with the newer images of the container-stack which got updated automatically from watchtower. Therefore, I completely dropped the stack removed the images and recreated ist with the newer docker-stack files from github https://github.com/netbox-community/netbox
