### ISSUE TITLE
Region ID ignored when creating Site via REST API

### ISSUE THREAD

**Issue by ghost** [netbox-community/netbox-docker#433]
## Current Behavior

I created a Site via the REST API and supplied an ID for an existing Region. The Site was successfully created, but its Region value was null. Here is the Python `requests` command I used to create the POST request:

    requests.post('http://10.0.0.2/api/dcim/sites/',headers={'Authorization':'Token abc123abc123abc123'},data={'name':'NY1','slug':'site-NY1','region':3,'description':''})
...

## Expected Behavior

The API documentation found at /api/docs/ suggests the Region ID is allowed to be supplied when creating a Site via a POST request.
...

## Debug Information

The output of `docker-compose version`: `1.28.2, build 67630359`
The output of `docker version`: `20.10.3`
The output of `git rev-parse HEAD`: `4dd7a51c7d79b097dea8ee7cf493dff00ebf50c3`
The command you used to start the project: `docker-compose up -d`

The output of `docker inspect netboxcommunity/netbox:latest --format "{{json .Config.Labels}}"`:

```json
{"BUILD_REASON":"netbox-docker","NETBOX_GIT_BRANCH":"HEAD","NETBOX_GIT_REF":"856d2e317605011e16a17bd87062721737ce3474","NETBOX_GIT_URL":"https://github.com/netbox-community/netbox.git","ORIGINAL_TAG":"docker.io/netboxcommunity/netbox:v2.10.4","org.label-schema.build-date":"2021-02-10T12:16+00:00","org.label-schema.description":"A container based distribution of NetBox, the free and open IPAM and DCIM solution.","org.label-schema.name":"NetBox Docker","org.label-schema.schema-version":"1.0","org.label-schema.url":"https://github.com/netbox-community/netbox-docker","org.label-schema.usage":"https://github.com/netbox-community/netbox-docker/wiki","org.label-schema.vcs-ref":"c80fb19507679938528817ab8a9b03514bd1e8be","org.label-schema.vcs-url":"https://github.com/netbox-community/netbox-docker.git","org.label-schema.vendor":"The netbox-docker contributors.","org.label-schema.version":"1.0.2","org.opencontainers.image.authors":"The netbox-docker contributors.","org.opencontainers.image.created":"2021-02-10T12:16+00:00","org.opencontainers.image.description":"A container based distribution of NetBox, the free and open IPAM and DCIM solution.","org.opencontainers.image.documentation":"https://github.com/netbox-community/netbox-docker/wiki","org.opencontainers.image.licenses":"Apache-2.0","org.opencontainers.image.revision":"c80fb19507679938528817ab8a9b03514bd1e8be","org.opencontainers.image.source":"https://github.com/netbox-community/netbox-docker.git","org.opencontainers.image.title":"NetBox Docker","org.opencontainers.image.url":"https://github.com/netbox-community/netbox-docker","org.opencontainers.image.vendor":"The netbox-docker contributors.","org.opencontainers.image.version":"1.0.2"}
```

The output of `docker-compose logs netbox`: https://gist.github.com/routetehpacketz/e5bbc706bb07f7ebbec033c2ba9036fb

**Comment by tobiasge** [comment]
This doesn't look like a problem with the docker image.
Have you asked in the Netbox slack channel or opened an issue in the [Nebox](https://github.com/netbox-community/netbox) repository?

**Comment by ghost** [comment]
I must apologize; I didn't even think about this being a core issue to Netbox. I reported here since I have always used the Docker image. I also overlooked the mentioning of the Netbox Slack channel in the Issues post guide.

I will close this and report the issue through those appropriate channels.
