### ISSUE TITLE
Add Support for LDAP Trusted Certificates

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox-docker#446]
## Desired Behavior

Add "in the box" support for adding a trusted cert path as an environment variable and creating a volume to mount said certificate.

## Contrast to Current Behavior

There is no support for any of this today.

## Changes Required

- Wiki/documentation updates to show how to set the volume.
- Updates to `ldap_config.py`

## Discussion: Benefits and Drawbacks

Eliminate some of common confusion with setting up LDAP with this project.

**Comment by cimnine** [comment]
This sounds like something we want in the ldap configure. A PR would be great. The certificate could be mounted, added by a secret (e.g. in Docker Swarm or Kubernetes) or by actually extending the image.

I think there might even be two variables required: One to enable the feature and the other to point to a path as you suggested.

**Comment by ryanmerolle** [comment]
I will tackle this PR.

As an FYI there are a few variables required for this:

- `TLS_CACERT` is the path for the TLS cert itself
- `AUTH_LDAP_START_TLS` is the option to enable TLS, BUT cannot be set if `ldaps://` in the `AUTH_LDAP_SERVER_URI`

**Comment by ryanmerolle** [comment]
I was totally wrong this is just an additional volume `/etc/ssl/certs/<file.crt>:/etc/ssl/certs/<file.crt>`

I do not think a PR is needed, just some wiki documentation needs updating.  Do you agree? @cimnine

**Comment by cimnine** [comment]
I have no insights into this. If that's the way, then even better :)
Again, a certificate *could* also be added by extending the image:

```Dockerfile
FROM netboxcommunity/netbox:latest

COPY my_local.crt /etc/ssl/certs/my_ldap.crt
```

**Comment by ryanmerolle** [comment]
Several ways to skin the cat as they say.  But it seems a PR is not needed here.  I will add some blurb to the wiki in the next few days and close this issue out.

**Comment by ryanmerolle** [comment]
@cimnine Should I also add the variables for TLS_CACERT & AUTH_LDAP_START_TLS  to the env setup and config file along with the document update?

**Comment by gijs007** [comment]
I couldn't find any documentation on configuring LDAPS in the wiki. 

I've set a volume mount: /etc/ssl/certs/my.ca.name.cer:/etc/ssl/certs/my.ca.name.cer
However the ldaps login fails as soon as I set LDAP_IGNORE_CERT_ERRORS to false.

Any suggestions?
