### ISSUE TITLE
Improve LDAP group variable naming

### ISSUE THREAD

**Issue by kasimon** [netbox-community/netbox-docker#470]
## Desired Behavior

The `AUTH_LDAP_IS_ADMIN_DN` and `AUTH_LDAP_IS_SUPERUSER_DN` in `configuration/ldap/ldap_config.py` should be better named `AUTH_LDAP_ADMIN_GROUP_DN` and `AUTH_LDAP_SUPERUSER_GROUP_DN`. 

## Contrast to Current Behavior

The current names of these variables give no clue that they expect the DN of an LDAP group and not for example a LDAP user DN. So I propose to change them.

## Changes Required

Introduce the new variables and add a deprecation warning for the old names for a limited time.

## Discussion: Benefits and Drawbacks

IMO this would reduce a possible cause of errors by making the intent of these variables more clear.

**Comment by cimnine** [comment]
This is a noble suggestion, but I believe it's too late for this. There are plenty of users who use the current names and we would not want to have them changing their configurations just for better naming. Please consider updating [the wiki](https://github.com/netbox-community/netbox-docker/wiki/LDAP) if you feel that the names are unclear.

**Comment by kasimon** [comment]
I updated the wiki page and fixed the example dn's in the openldap example with references to groups instead of users. That should do it.
