### ISSUE TITLE
Custom Links initialiser breaks if content_type is invalid

### ISSUE THREAD

**Issue by marcus-crane** [netbox-community/netbox-docker#480]
I'm assuming the same standard here as the primary Netbox repo, which is that an issue is preferred first followed by a pull request if accepted but either way, I'm happy to provide a fix for this via pull request 🙂

## Current Behavior

The [custom links startup script](https://github.com/netbox-community/netbox-docker/blob/release/startup_scripts/280_custom_links.py) breaks if a custom link is defined with an invalid `content_type` at [the following block](https://github.com/netbox-community/netbox-docker/blob/release/startup_scripts/280_custom_links.py#L26):

```python
if link["content_type_id"] is None:
        print(
            "⚠️ Unable to create Custom Link '{0}': The content_type '{1}' is unknown".format(
                link.name, content_type
            )
        )
        continue
```

The issue here is that `link.name` is invalid as `link` is a `dict`. Either `link['name']` or `link.get('name')` would work here, although I suppose the latter is "safer" in the event that name isn't even defined.

## Expected Behavior

The custom links initializer continues upon finding a malformed `content_type`

## Debug Information

Not provided as I've already linked to the problem area in question. Happy to provide more information if requested but I don't think that information help provide any extra insight.

<sup>Marcus Crane, marcus.crane@daimler.com, Mercedes-Benz New Zealand Ltd on behalf of Daimler Truck AG on behalf of Daimler TSS ([Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md))</sup>

**Comment by cimnine** [comment]
Thank you for the bug report. We do allow PR without bugs first. Feel free to provide a PR anytime.

For bigger changes it might be good to ask/discuss first, as we might have opinions about such big changes.

**Comment by marcus-crane** [comment]
@cimnine Thanks! I've submitted a PR and I'll be trying to contribute to the initializers where I can, as we use them in our work instance of NetBox. I only discovered this bug because I was struggling to set up custom links properly so once I figure out how they work, I'll take to make it clearer 😉
