### ISSUE TITLE
Feature Request: Add ability to run lint tests locally

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox-docker#501]
## Desired Behavior

Setup a process for contributors to lint their contributions before a pull request.

## Contrast to Current Behavior

Contributors either just find linting issues upon commit to a PR or they manually run hadolint, markdownlint, black, flake8, and isort.

## Changes Required

Either create a pre-commit definition users can choose to use that references everything that the github superlinter is configured for by the repo or create a shell script for the same.

### Benefits

- higher quality PRs off the bat
- Development linting reflects CI/CD linting

### Drawbacks: 

- Need to maintain this process every time github superlinter is changed so the two match.
- No way to force users to use either model.

**Comment by cimnine** [comment]
Since we use superlinter, https://github.com/github/super-linter/blob/master/docs/run-linter-locally.md might be a start.

**Comment by ryanmerolle** [comment]
I’ll look into that.  I did not know superlinter could be run locally.

**Comment by ryanmerolle** [comment]
I have no problem running containers for this in my ci or even on my local machine.  I feel like for this project something running locally would be less of a barrier to entry.

On the other hand a make file or bash script would be sort of a pain to maintain and deploy needed decencies.  Pre-commit framework might work better.

@cimnine & @tobiasge any thoughts here?  Is the ROI low here?  I think if people lint more pre pull request, you might save some GitHub actions credits if that is a concern.

**Comment by cimnine** [comment]
> you might save some GitHub actions credits if that is a concern.

This has never been a concern so far.
