### ISSUE TITLE
custom scripts initializer defaults filter logic

### ISSUE THREAD

**Issue by chamberk** [netbox-community/netbox-docker#540]
## Current Behavior

When using the startup_scripts initializers to create a custom field, the filter_logic attribute is always defaulted to `loose`.
netbox-docker/initializers/custom_fields.yml has examples with a `filter_logic` attribue, but startup_scripts/020_custom_fields.py never reads it. 

## Expected Behavior

The custom_field filter_logic attribute should be set to the value defined in the custom_fields.yml. 

## Debug Information

The output of `docker-compose version`: `2.0.0-beta`
The output of `docker version`: `20.10.6`
The output of `git rev-parse HEAD`: `a51ad368017dc7543855946ef3a031cfe5cba10e`
The command you used to start the project: `docker-compose up -d`

The output of `docker inspect netboxcommunity/netbox:latest --format "{{json .Config.Labels}}"`:

```json
{

}
```

The output of `docker-compose logs netbox`:

**Comment by tobiasge** [comment]
Fixed in next release.
