### ISSUE TITLE
netbox-docker upgrade v2.10 to 2.11 failing on rack-groups import

### ISSUE THREAD

**Issue by jhoustek23** [netbox-community/netbox-docker#550]
docker-compose.yml:
version: '3.4'
services:
  netbox: &netbox
    image: netboxcommunity/netbox:v2.11.1-ldap
    restart: always
    depends_on:
    - postgres
    - redis
    - redis-cache
    - netbox-worker
    env_file: env/netbox.env
    volumes:
    - /data/netbox/startup_scripts:/opt/netbox/startup_scripts:z,ro
    - /data/netbox/initializers:/opt/netbox/initializers:z,ro
    - /data/netbox/configuration:/etc/netbox/config:z,ro
    - /data/netbox/reports:/etc/netbox/reports:z,ro
    - /data/netbox/scripts:/etc/netbox/scripts:z,ro
    - /data/netbox/media-files:/opt/netbox/netbox/media:z
    ports:
    - "8080:8080"
  netbox-worker:
    <<: *netbox
    depends_on:
    - redis
    entrypoint:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    ports:
    - "8080"
    command:
    - rqworker
  postgres:
    image: postgres:12-alpine
    restart: always
    env_file: env/postgres.env
    volumes:
    - /data/netbox-postgres:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    restart: always
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis.env
    volumes:
    - /data/netbox-redis:/data
  redis-cache:
    image: redis:6-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis-cache.env

-------

root@netbox:~/docker/netbox# docker logs netbox_netbox_1
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, secrets, sessions, taggit, tenancy, users, virtualization
Running migrations:
  Applying extras.0054_standardize_models... OK
  Applying extras.0055_objectchange_data... OK
  Applying dcim.0123_standardize_models... OK
  Applying dcim.0124_mark_connected... OK
  Applying dcim.0125_console_port_speed... OK
  Applying dcim.0126_rename_rackgroup_location... OK
  Applying dcim.0127_device_location... OK
  Applying dcim.0128_device_location_populate... OK
  Applying dcim.0129_interface_parent... OK
  Applying dcim.0130_sitegroup... OK
  Applying extras.0056_extend_configcontext... OK
  Applying extras.0057_customlink_rename_fields... OK
  Applying extras.0058_journalentry... OK
  Applying circuits.0025_standardize_models... OK
  Applying circuits.0026_mark_connected... OK
  Applying circuits.0027_providernetwork... OK
  Applying circuits.0028_cache_circuit_terminations...
    Caching circuit terminations...
 OK
  Applying circuits.0029_circuit_tracing... OK
  Applying dcim.0131_consoleport_speed... OK
  Applying extras.0059_exporttemplate_as_attachment... OK
  Applying ipam.0044_standardize_models... OK
  Applying ipam.0045_vlangroup_scope... OK
  Applying ipam.0046_set_vlangroup_scope_types... OK
  Applying ipam.0047_prefix_depth_children... OK
  Applying ipam.0048_prefix_populate_depth_children...
Updating 30 prefixes...
 OK
  Applying secrets.0013_standardize_models... OK
  Applying tenancy.0012_standardize_models... OK
  Applying users.0011_standardize_models... OK
  Applying virtualization.0020_standardize_models... OK
  Applying virtualization.0021_virtualmachine_vcpus_decimal... OK
  Applying virtualization.0022_vminterface_parent... OK
  Applying virtualization.0023_virtualmachine_natural_ordering... OK
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
💡 Superuser Username: admin, E-Mail: admin@example.com
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
▶️  Running the startup script /opt/netbox/startup_scripts/000_users.py
▶️  Running the startup script /opt/netbox/startup_scripts/010_groups.py
▶️  Running the startup script /opt/netbox/startup_scripts/020_custom_fields.py
▶️  Running the startup script /opt/netbox/startup_scripts/020_tags.py
▶️  Running the startup script /opt/netbox/startup_scripts/030_regions.py
▶️  Running the startup script /opt/netbox/startup_scripts/040_sites.py
▶️  Running the startup script /opt/netbox/startup_scripts/050_manufacturers.py
▶️  Running the startup script /opt/netbox/startup_scripts/060_device_types.py
▶️  Running the startup script /opt/netbox/startup_scripts/070_rack_roles.py
▶️  Running the startup script /opt/netbox/startup_scripts/075_rack_groups.py
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/commands/shell.py", line 93, in handle
    exec(sys.stdin.read(), globals())
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/runpy.py", line 282, in run_path
    return _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/netbox/netbox/../startup_scripts/__main__.py", line 27, in <module>
    runpy.run_path(f.path)
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/netbox/startup_scripts/075_rack_groups.py", line 3, in <module>
    from dcim.models import RackGroup, Site
ImportError: cannot import name 'RackGroup' from 'dcim.models' (/opt/netbox/netbox/dcim/models/__init__.py)

## Debug Information

The output of `docker-compose version`: `XXXXX`
The output of `docker version`: `XXXXX`
The output of `git rev-parse HEAD`: `XXXXX`
The command you used to start the project: `XXXXX`

The output of `docker inspect netboxcommunity/netbox:latest --format "{{json .Config.Labels}}"`:

```json
{
  "JSON JSON JSON":
    "--> Please paste formatted json. (Use e.g. `jq` or https://jsonformatter.curiousconcept.com/)"
}
```

The output of `docker-compose logs netbox`:

```text
LOG LOG LOG
```

The output of `cat docker-compose.override.yml`:

```text
LOG LOG LOG
```

**Comment by jhoustek23** [comment]
Resolved by removing /opt/netbox/startup_scripts/075_rack_groups.py

**Comment by DSI-BenThomas** [comment]
I'm hitting the same issue....
Is it safe to remove the 075_rack_groups.py script?

**Comment by DSI-BenThomas** [comment]
Seems to be caused by the fact that the example docker-compose mounts a number of volumes including the startup scripts folder through to the docker host https://github.com/netbox-community/netbox-docker/blob/676ca798cd684ce30fca2692180e680d2becf76e/docker-compose.yml#L12-L18
And therefore any changes to these files upstream never get through to new docker images on the host, as the old static files are mapped through.
I'd suggest startup scripts possibly be excluded from the compose file
