### ISSUE TITLE
"Waiting on DB..." message hides NetBox migration issues after 4d320f3

### ISSUE THREAD

**Issue by mk-fg** [netbox-community/netbox-docker#562]
## Current Behavior

When there is an issue with NetBox migrations after updating docker image,  entrypoint script keeps displaying "Waiting on DB..." message without any actual problem wrt database connection, and without even trying to connect to it.

## Expected Behavior

"Waiting on DB..." message would be printed when actually checking connection to database and doing as little other complicated stuff as possible, and/or would be able to print what the problem was during such attempt.

## Debug Information

Noticed this problem when trying to from update an older netbox release to v3.0 in a testing VM.

I think problem was introduced in 4d320f34 by addition of `>/dev/null` to `./manage.py showmigrations`, which was probably done because output from that command was unnecessary verbose for simple "connection refused" errors, but now it also completely hides stuff like this:

```
⚠ Main configuration '/etc/netbox/config/configuration.py' not found.
🧬 loaded config '/etc/netbox/config/10_netbox_docker_base.py'
🧬 loaded config '/etc/netbox/config/20_database_config.py'
🧬 loaded config '/etc/netbox/config/20_misc_defaults.py'
🧬 loaded config '/etc/netbox/config/20_napalm_ssh_access.py'
🧬 loaded config '/etc/netbox/config/50_local_override_example.py'
🧬 loaded config '/etc/netbox/config/90_testing_overrides.py'
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/migrations/loader.py", line 259, in build_graph
    self.graph.validate_consistency()
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/migrations/graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/migrations/graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/migrations/graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration dcim.0131_consoleport_speed dependencies reference nonexistent parent node ('dcim', '0130_sitegroup')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/netbox/netbox/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/commands/showmigrations.py", line 52, in handle
    return self.show_list(connection, options['app_label'])
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/commands/showmigrations.py", line 71, in show_list
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/migrations/loader.py", line 276, in build_graph
    raise NodeNotFoundError(
django.db.migrations.exceptions.NodeNotFoundError: Migration dcim.0131_consoleport_speed depends on nonexistent node ('dcim', '0130_sitegroup'). Django tried to replace migration dcim.0130_sitegroup with any of [dcim.0003_squashed_0130] but wasn't able to because some of the replaced migrations are already applied.
```

Exception and traceback itself is probably unrelated to this bug, which is about entrypoint script sending this information to >/dev/null, making it hard to debug such issues.

For example, #529 with similar issue has an attached logfile from similar command, which will not be produced after that change above.

**Comment by mk-fg** [comment]
As a random idea how that might be addressed here without dumping huge and scary tracebacks or changing anything in upstream netbox, maybe "while" loop can collect output to a tmpfile or a variable, and only print last line by default, with an extra env var allowing to print the rest.

I.e. given that it's a bash script, run something like this within a loop:
```bash
read -rd '' DB_ERR < <(./manage.py showmigrations 2>&1)
if [ -n "$DB_ERROR_DEBUG" ]
then echo "$DB_ERR"
else
  readarray -tn 0 DB_ERR_LINES <<< "$DB_ERR"
  echo "${DB_ERR_LINES[@]: -1}"
  echo '[ Use DB_ERROR_DEBUG=1 to netbox.env to print full traceback for errors here ]'
fi
```

With error from the original post, this should print this on each iteration:
```
django.db.migrations.exceptions.NodeNotFoundError: Migration dcim.0131_consoleport_speed depends on nonexistent node ('dcim', '0130_sitegroup'). Django tried to replace migration dcim.0130_sitegroup with any of [dcim.0003_squashed_0130] but wasn't able to because some of the replaced migrations are already applied.
[ Use DB_ERROR_DEBUG=1 to netbox.env to print full traceback for errors here ]
```

And I believe with any other kind of regular python exception, last line would be similar `<exception-name>: <exception-string>` output, so is useful to print, while not too confusing or overly verbose.
In case of not-yet-started db, it'd probably be something like "django.db.postgresql.Error: Connection refused".

Specifying DB_ERROR_DEBUG=1 in some env file as suggested should print full traceback output instead, which can be useful for bug-reporting or local debugging.

**Comment by tobiasge** [comment]
I think your suggestion is a good compromise to printing all errors every time. Are you willing to write a PR?

**Comment by mk-fg** [comment]
Sure, will do after I get back in a couple hours.

**Comment by cb3inco** [comment]
I'm getting this error too, am I missing how to actually fix this problem?

**Comment by tobiasge** [comment]
> I'm getting this error too, am I missing how to actually fix this problem?

```
django.db.migrations.exceptions.NodeNotFoundError: Migration dcim.0131_consoleport_speed depends on nonexistent node ('dcim', '0130_sitegroup'). Django tried to replace migration dcim.0130_sitegroup with any of [dcim.0003_squashed_0130] but wasn't able to because some of the replaced migrations are already applied.
```

This points to a problem with the migrations. Those have been changed with the 3.0 release. You need to update to 2.11.x before updating to 3.0.x. See the [release notes](https://github.com/netbox-community/netbox/releases/tag/v3.0.0).

**Comment by cb3inco** [comment]
Thanks - I think I got it. I forgot about the database upgrade and brought the compose-file up by accident then remembered and stopped it. So I did a quick db backup, delete, and restore. Looks to be working now. :)

**Comment by mk-fg** [comment]
> I'm getting this error too, am I missing how to actually fix this problem?

Yeah, in my case it was a 2.10.10 -> 3.0.0 update - seen the error, checked the changes, updated through 2.11 just fine.
Bit weird that there's no check for pre-2.11 in the code to raise something like "Update to 2.11 first" error instead of leaving it up to django's cryptic confusion.
