### ISSUE TITLE
Upgrade from 2.11.9 to 3.0.2 INSECURE_SKIP_TLS_VERIFY not working?

### ISSUE THREAD

**Issue by darkpixel** [netbox-community/netbox-docker#580]
I'm running Netbox in a kubernetes cluster using the netboxcommunity/netbox image, and it's worked well for the last few months.  When I tried to upgrade, I started getting "connection refused" errors for Redis.  If I roll back to 2.11.9 it works perfectly.

I dug through the changelog and issues, and I see a few mentions of Redis, but I nothing appears to be directly related, but it appears the Redis library has been updated...which might indicate that cert validation is now enabled or something.

I dug around and found the INSECURE_SKIP_TLS_VERIFY setting in netbox, and tried setting it in my k8s environment, but that didn't resolve the issue.  After doing some more digging, it looks like possibly the netboxcommunity/netbox image doesn't support setting that environment variable in the configuration file.  For now I've rolled back to 2.11.9.

```
<class 'redis.exceptions.ConnectionError'>

Error 111 connecting to private-<redacted>-do-user-<redacted>-0.b.db.ondigitalocean.com:25060. Connection refused.

Python version: 3.9.5
NetBox version: 3.0.2
```

**Comment by tobiasge** [comment]
Fixed in #630 and will be in next release.
