### ISSUE TITLE
UID for K8s/OpenShift ( starting from 1001 ) 

### ISSUE THREAD

**Issue by ricristian** [netbox-community/netbox-docker#588]
In this moment from different reasons we have to build netbox image using build.sh script. 
I've looked on launch-netbox.sh and I see that it tries to start using 101 UID but in case of k8s or openshift where UID's could be allocated starting from 1001 the problems starts coming meaning that netbox container won't start because it will have the errors reported on #586 

## Desired Behavior

The UID used in launch-netbox.sh should be fetched as variables set in Docker file or something in order to provide us at building phase the possibility to provide UID based on our infrastructure ( k8s, openshift, vm and so on ... ) 

## Contrast to Current Behavior
Current behaviour is specifying statically the UID in launch script .... 

## Discussion: Benefits and Drawbacks

The benefit will be given to the fact that we can run netbox on different environments without affecting netbox scripts or core ... 

I'm not an expert in k8s but let's say that netbox uses 101 UID and openshift or k8s is giving 1005 UID or dynamic UID's on each run starting from 1001 to 9001 .. is there possibility to update folder / file permissions in order for netbox which runs with 101 to start correctly into a pod which has as `securityContext: runAsUser: 1000, runAsGroup: 2000` ? 
Also runAsUser uid could be assigned dynamic by k8s/openshift ... 

I will gladly accept some hints or even tutorials. 
Many thanks for any type of help

**Comment by tobiasge** [comment]
The container can already be run as any user ID as long as you run it with group ID 0.
```bash
/opt/netbox/netbox $ id
uid=1002170000(1002170000) gid=0(root) groups=1002170000
```

This is the default for Openshift (I've been using that for a while).

**Comment by ricristian** [comment]
Thanks @tobiasge  for sharing but in https://github.com/netbox-community/netbox-docker/blob/release/docker/launch-netbox.sh#L55 the user id is specified static here ... so basically I have to update also this line UID according to one given by k8s or openshift ?

**Comment by tobiasge** [comment]
No, when the container is not started as root NGinx Unit ignores those parameters because it can't drop privileges.
Those parameters are there as a fallback, when someone starts the container as root (which is NOT recomended).

**Comment by ricristian** [comment]
Ohh ok. 

I've just tested in k8s adding `securityContext: runAsUser: 1001` in deployment set and it started ok. Many thanks for your explanation
