### ISSUE TITLE
Impossible to run last version of netbox-docker

### ISSUE THREAD

**Issue by daurpam** [netbox-community/netbox-docker#596]
## Current Behavior

After upgrade netbox-docker it doesn't start. Trying from scratch doesn't work too.

## Expected Behavior

Start netbox-docker and access via web.

## Debug Information

The output of `docker-compose version`: `1.21.0`
The output of `docker version`: `20.10.7`
The output of `git rev-parse HEAD`: `6a52a48b71187eabb16db2149060cffc159f5f72`
The command you used to start the project: `docker-compose up -d`

The output of `docker inspect netboxcommunity/netbox:latest --format "{{json .Config.Labels}}"`:

```json
{"BUILD_REASON":"alpine netbox netbox-docker",
"NETBOX_GIT_BRANCH":"HEAD",
"NETBOX_GIT_REF":"9cc4992fad2fe04ef0211d998c517414e8871d8c",
"NETBOX_GIT_URL":"https://github.com/netbox-community/netbox.git",
"ORIGINAL_TAG":"docker.io/netboxcommunity/netbox:v2.11.12",
"org.label-schema.build-date":"2021-08-24T05:51+00:00",
"org.label-schema.description":"A container based distribution of NetBox, the free and open IPAM and DCIM solution.",
"org.label-schema.name":"NetBox Docker",
"org.label-schema.schema-version":"1.0",
"org.label-schema.url":"https://github.com/netbox-community/netbox-docker",
"org.label-schema.usage":"https://github.com/netbox-community/netbox-docker/wiki",
"org.label-schema.vcs-ref":"676ca798cd684ce30fca2692180e680d2becf76e",
"org.label-schema.vcs-url":"https://github.com/netbox-community/netbox-docker.git",
"org.label-schema.vendor":"The netbox-docker contributors.",
"org.label-schema.version":"1.2.0",
"org.opencontainers.image.authors":"The netbox-docker contributors.",
"org.opencontainers.image.created":"2021-08-24T05:51+00:00",
"org.opencontainers.image.description":"A container based distribution of NetBox, the free and open IPAM and DCIM solution.",
"org.opencontainers.image.documentation":"https://github.com/netbox-community/netbox-docker/wiki",
"org.opencontainers.image.licenses":"Apache-2.0",
"org.opencontainers.image.revision":"676ca798cd684ce30fca2692180e680d2becf76e",
"org.opencontainers.image.source":"https://github.com/netbox-community/netbox-docker.git",
"org.opencontainers.image.title":"NetBox Docker",
"org.opencontainers.image.url":"https://github.com/netbox-community/netbox-docker",
"org.opencontainers.image.vendor":"The netbox-docker contributors.",
"org.opencontainers.image.version":"1.2.0"}
```

The output of `docker-compose logs netbox`:
https://gist.github.com/daurpam/c337b5674b1a7bfccb7a2eeedd4bdc90

The output of `cat docker-compose.override.yml`:
```
version: '3.4'
services:
  netbox:
    ports:
      - 8000:8080
```

**Comment by kkthxbye-code** [comment]
Your database container is not running. When you upgraded netbox-docker the postgres image was bumped. Postgres is not backwards compatible with older db versions.

If you want to keep your data, create a docker-compose.override.yml with a tagged postgres version equal to what you upgraded from.

If you want to start from scratch, just make sure you deleted the netbox-postgres-data volume. Make sure you have a backup of your database first if it contains in production data.

More info: https://github.com/netbox-community/netbox-docker/wiki/Updating#postgresql-update

**Comment by daurpam** [comment]
Thanks @kkthxbye-code for the advice.
I've tried that too, but still not running, even from scratch without saving database data.

Perhaps is related with the prior [issue](https://github.com/netbox-community/netbox-docker/issues/586) Because I've get this error message while starting:
```
2021/10/02 21:09:10 [warn] 6#6 Unit is running unprivileged, then it cannot use arbitrary user and group.
```
But follow the instructions on that post (changing user environment doesn't change anything).
Fortunately this container it isn't on production, but others will have to wait their upgrade til I fix this one first.

**Comment by kkthxbye-code** [comment]
No, that warning is not the reason it is not working. Can't tell you anything else without new logs where the database is running.

**Comment by daurpam** [comment]
Thanks for your assistance, really appreciated. Another log from scratch:
[netbox.log](https://gist.github.com/daurpam/522c3287cb9fa1b2d8e58568f6740b62)

**Comment by kkthxbye-code** [comment]
Are you running this without -d?

**Comment by daurpam** [comment]
> Are you running this without -d?

I've tested with and without that

**Comment by kkthxbye-code** [comment]
Your logs look like a regular succesful launch of netbox. I just did a fresh git pull on a fresh docker install and it works fine and the logs look like exactly like yours. The site was avaliable on port 8000 after using the override example from the readme.

**Comment by daurpam** [comment]
You're right, I've tested in another VM, and it works, there must be a problem with the original VM.

Thanks too much for your support. Regards
