### ISSUE TITLE
SKIP_SUPERUSER does not work when set to "true"

### ISSUE THREAD

**Issue by mumblez** [netbox-community/netbox-docker#609]
It always creates the `admin` account with `admin` password.

I believe the issue is how the check is made in `docker/docker-entrypoint.sh` on [line 52](https://github.com/netbox-community/netbox-docker/blob/6a52a48b71187eabb16db2149060cffc159f5f72/docker/docker-entrypoint.sh#L52)

```sh
[ "$SKIP_SUPERUSER" == "true" ] # <-- should either be a single `=` or wrap with `[[ ... ]]`
```

**Comment by tobiasge** [comment]
I just tested this again (also with `SKIP_STARTUP_SCRIPTS`, where the same check is used): Although it is not standard Bash syntax, it is working correctly.

**Comment by mumblez** [comment]
for me it always generates the admin account
using `v3.0.5-ldap` image

**Comment by mumblez** [comment]
it does indeed work locally, e.g `SKIP_SUPERUSER="true"` but on a VM on google cloud for some reason it's not interpreted the same way, I'll look into this...

**Comment by mumblez** [comment]
```
root@netbox-instance-p63z:/etc/netbox# cat docker-compose.yml
version: '3.7'
services:
  netbox: &netbox
    restart: always
    image: netboxcommunity/netbox:v3.0.5-ldap
    env_file: netbox.env
    user: '101'
    volumes:
    - /var/netbox/reports:/etc/netbox/reports:z,rw
    - /var/netbox/media:/opt/netbox/netbox/media:z,rw
 ...

root@netbox-instance-p63z:/etc/netbox# dc exec netbox bash
bash-5.1$ env | grep SKIP
SKIP_STARTUP_SCRIPTS="true"
SKIP_SUPERUSER="true"

bash-5.1$ echo $SKIP_SUPERUSER
"true" # <-- retains quotes
bash-5.1$ if [ "$SKIP_SUPERUSER" == "true" ]; then echo "hey"; fi # <-- doesn't match

root@netbox-instance-p63z:/etc/netbox# docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
root@netbox-instance-p63z:/etc/netbox# docker version
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:29 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

Maybe it's the new docker / docker-compose combo, when we set the `env_file:` in docker compose and the file contains:  
`SKIP_SUPERUSER="true"`
it seems to retain the quotes, therefore breaking the check.

As a workaround, I set the value without quoting and it worked as expected!

**Comment by tobiasge** [comment]
I think it relates to this [issue](https://github.com/docker/compose/issues/3702). `docker-compose` is parsing ENV files differently than bash.

It is mentioned in the [docker-compose documentation](https://docs.docker.com/compose/env-file/).
