### ISSUE TITLE
Virtualenv not loaded when it should after new entrypoint change

### ISSUE THREAD

**Issue by xeor** [netbox-community/netbox-docker#631]
### Current Behavior

I'm not able to use `./manage.py` in latest netbox (unsure from which version this started happening).

```sh
# docker-compose run --rm netbox ./manage.py nbshell
Creating lars_netbox_run ... done
env: can't execute 'python': No such file or directory
ERROR: 127

# docker-compose run --rm netbox python3 manage.py nbshell
Creating lars_netbox_run ... done
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
ERROR: 1


bash-5.1$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

bash-5.1$ python3 -c 'import sys; print(sys.path)'
['', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/usr/lib/python3.9/site-packages']
```

Django is in `/opt/netbox/venv/lib/python3.9/site-packages/django`

If I do `export PATH=/opt/netbox/venv/bin:$PATH` (add the virtualenv to path) or `source /opt/netbox/venv/bin/activate`, it works without problems..

### Expected Behavior

./manage.py should work without having to manually add `/opt/netbox/venv/bin` to `PATH` or run activate.

This have probably started happening after https://github.com/netbox-community/netbox-docker/commit/a8b6883183078ec927655be53ba36b02a31a9274

There are plenty of documentation that is about running stuff like `docker-compose run --rm netbox ./manage.py nbshell`.

Maybe the best solution is to add to PATH, if that is sufficient to run nbshell and other local cli tools?

### Docker Compose Version

not relevant

### Docker Version

```text
not relevant
```

### The git Revision

not relevant

### The git Status

```text
not relevant
```

### Startup Command

not relevant

### NetBox Logs

```text
not relevant
```

### Content of docker-compose.override.yml

```yaml
not relevant
```

**Comment by tobiasge** [comment]
[Troubleshooting](https://github.com/netbox-community/netbox-docker/wiki/Troubleshooting) Wiki page has been updated with the corrected commands.
