### ISSUE TITLE
Napalm: cannot import name 'etree' from 'lxml'

### ISSUE THREAD

**Issue by anthr76** [netbox-community/netbox-docker#652]
### Current Behavior

I'm trying to using napalm but the dependencies within alpine appear to be broken? A releated issue to the problem is here https://github.com/babybuddy/babybuddy/issues/336#issuecomment-968137401

### Expected Behavior

This bit to work, or it to work within netbox itself

```bash
bash-5.1$ source /opt/netbox/venv/bin/activate
(venv) bash-5.1$ python3.9
Python 3.9.5 (default, May 12 2021, 20:44:22)
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from napalm import get_network_driver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm/__init__.py", line 11, in <module>
    import napalm.iosxr
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm/iosxr/__init__.py", line 22, in <module>
    from napalm.iosxr.iosxr import IOSXRDriver  # noqa
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm/iosxr/iosxr.py", line 23, in <module>
    from lxml import etree as ETREE
ImportError: cannot import name 'etree' from 'lxml' (/opt/netbox/venv/lib/python3.9/site-packages/lxml/__init__.py)
>>> import pprint
```

### Docker Compose Version

N/A This is Kubernetes

### Docker Version

```text
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

### The git Revision

```
?
```

```
skopeo inspect docker://docker.io/netboxcommunity/netbox:v3.0.10
{
    "Name": "docker.io/netboxcommunity/netbox",
    "Digest": "sha256:042371b7687b25d584408520cceb6eb1f153f41f14c95b73a3e9799055f4ffec"
```

### The git Status

```text
?
```

### Startup Command

https://github.com/anthr76/infra/blob/main/gitops/base/infra/netbox/helm-release.yaml

### NetBox Logs

```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm/__init__.py", line 11, in <module>
    import napalm.iosxr
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm/iosxr/__init__.py", line 22, in <module>
    from napalm.iosxr.iosxr import IOSXRDriver  # noqa
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm/iosxr/iosxr.py", line 23, in <module>
    from lxml import etree as ETREE
ImportError: cannot import name 'etree' from 'lxml' (/opt/netbox/venv/lib/python3.9/site-packages/lxml/__init__.py)
>>> import pprint
```
```


### Content of docker-compose.override.yml

```yaml
N/A
```

**Comment by peshev** [comment]
I have the same issue. It is apparently caused by an incorrectly built binary wheel for lxml==4.6.4. I managed to resolve it by specifying lxml<4.6.4 in my requirements-container.txt file and rebuilding the images

**Comment by itsec-lib** [comment]
Facing the same issue with version 1.4.1-3.0.10.
docker-compose version 1.29.2, build 5becea4c
docker version: 20.10.10
Tried to specify lxml==4.6.4 and lxml<4.6.4 in requirements-container.txt file and rebuilding the images - didn't help.
Still getting the same error.
>>> import lxml
>>> print(lxml.__version__)
4.6.4
>>> from lxml import etree as ETREE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'etree' from 'lxml' (/opt/netbox/venv/lib/python3.9/site-packages/lxml/__init__.py)

**Comment by peshev** [comment]
@itsec-lib 
Which version of the netbox images are your containers running?
Did you do `docker-compose stop && docker-compose rm && VERSION=latest docker-compose up` after you built the new images?
If you don't specify the version explicitly using the env variable, the docker-compose.yml defaults to a specific version instead of `latest` ( `v3.0-1.4.1` at the time of writing) - while the ones you're building are tagged `latest`, and therefore not used

**Comment by itsec-lib** [comment]
No luck, still the same error.
I found a difference in python behaviour in 2 different systems:

(testenv3.9.5) XXXXXXXXXXXXX1:~$ python
Python 3.9.5 (default, May 19 2021, 11:32:47) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml
>>> print(lxml.__version__)
4.6.4
>>> from lxml import etree
>>> 

But this is what happening in the container netbox-docker_netbox_1:
(venv) bash-5.1# python
Python 3.9.5 (default, May 12 2021, 20:44:22) 
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml
>>> print(lxml.__version__)
4.6.4
>>> from lxml import etree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'etree' from 'lxml' (/opt/netbox/venv/lib/python3.9/site-packages/lxml/__init__.py)

Wonder if anyone can explain the difference.

**Comment by kkthxbye-code** [comment]
https://bugs.launchpad.net/lxml/+bug/1951022

The binary wheel for musl doesn't work.

**Comment by kkthxbye-code** [comment]
Disregard the other post, the issue is actually with alpine:

https://gitlab.alpinelinux.org/alpine/aports/-/issues/13227

**Comment by tobiasge** [comment]
Alpine has fixed the issue. With the image for 3.0.11 it works again.
