### ISSUE TITLE
Update Unit to 1.25 or higher

### ISSUE THREAD

**Issue by bootc** [netbox-community/netbox-docker#654]
### Desired Behavior

Unit 1.25 includes support for X-Forwarded-For (https://github.com/nginx/unit/issues/132). Purely selfishly this would help me fix https://github.com/bootc/netbox-chart/issues/46.

### Contrast to Current Behavior

The current base image is Alpine 3.14 with Unit 1.23.

### Required Changes

This could be achieved by updating the base image to Alpine 3.15 but @cimnine says (in https://github.com/netbox-community/netbox-docker/issues/654#issuecomment-981083391) that the preferred approach it to update to a Debian base image (see #604) which should do the job just as well.

### Discussion: Benefits and Drawbacks

Enabling X-Forwarded-For would allow NetBox to see (and the Unit logs to display) correct client IPs when going via a reverse proxy, which is almost universally the case in Kubernetes.

**Comment by cimnine** [comment]
Thanks for the suggestion. We currently plan to switch to a Debian-based build (see #604), so we won't actively update to Alpine 3.15 for now. The Debian-based build time would be better, we'd be able to release ARM64 images and – to address your case – it will use Unit 1.26 (or later) as well.

**Comment by bootc** [comment]
Ah, sure, that should work. Let me re-title and update the issue to reframe that as updating to Unit 1.25 or later, then.

**Comment by l1bra2013** [comment]
Just a note about unit - doing some local testing with 1.26.0 and 1.26.1, I had some issues where all of the static files would redirect infinitely. Example: `/static/netbox-print.css` to `/static/netbox-print.css/` to `/static/netbox-print.css//` and for whatever reason ultimately staying there. Not sure if this is a netbox config issue or a unit issue, but downgrading to 1.25.0 fixes that issue

**Comment by dteach-rv** [comment]
FYI I've been working on building a container that meets my security teams requirements. This forced me to look at Alpine 3.16 and Debian bullseye. Both builds exhibited the redirect loop that @l1bra2013 mentioned above. After some digging, I discovered that there was a change in functionality in the way unit handles the `share` action. More info [here](https://unit.nginx.org/configuration/#static-files). TL;DR Pre-1.26, `share` used to operate like the document root. Post-1.26  , `share` uses variable interpolation, and in this case appends, `$uri` to the end of the share. This causes the redirect issue for some reason.  Manually setting share to `"share": "/opt/netbox/netbox/$uri"` appears to fix the issue in my build.

**Comment by Memorist23** [comment]
@dteach-rv Where did you apply that setting?

**Comment by tobiasge** [comment]
Switched to Debian and Unit 1.27 with PR #775.
