### ISSUE TITLE
Docker tag with pre-installed library

### ISSUE THREAD

**Issue by gaby** [netbox-community/netbox-docker#655]
### Desired Behavior

It would be very beneficial if NetBox provided a Docker tag in which all the devices from https://github.com/netbox-community/devicetype-library are pre-installed. 

### Contrast to Current Behavior

The current installation provides zero data, making it harder for a new user to adapt to NetBox. New user currently need to spend hours trying to configure devices, etc. 

### Discussion: Benefits and Drawbacks

* Users won't have to spend hours configuring/installing devices.
* Would heavily benefit installations in air-gap systems, which have no access to Github.com

**Comment by rizlas** [comment]
Check this out https://github.com/minitriga/Netbox-Device-Type-Library-Import

**Comment by ryanmerolle** [comment]
The devicetype-library is not perfect and its frankly a step behind on adding features added to netbox overall.  I should know as the main reviewer approver of PRs to the repo.

There are a few scripts to auto add.  Adding this could break a NetBox spin up if an underlying template is broken.  This is not worth the added troubleshooting and headache.
