### ISSUE TITLE
Issue with SOCIAL_AUTH_* variables

### ISSUE THREAD

**Issue by dostalradim** [netbox-community/netbox-docker#667]
### Current Behavior

I am trying to configure authentication against keycloak but the error which I get looks like the variables with SOCIAL_AUTH_ prefix are not inserted to authentication library. I am using docker image with tag v3.1 which should got merged the bugfix from #653 issue. Is it really working now? I set these variables:

```
REMOTE_AUTH_BACKEND: "social_core.backends.keycloak.KeycloakOAuth2"
SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY: "7Rm-OTIKXXXXXXXXMjEjUc0Ml1PVQbvYtkQ9rEnbg"
SOCIAL_AUTH_KEYCLOAK_KEY: "netbox"
SOCIAL_AUTH_KEYCLOAK_SECRET: "ec5c49fa-8e18-4a1a-XXX-3bb5cdac369a"
SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL: "https://keycloak.testXXX/auth"
SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL: "https://keycloak.testXXX/auth/realms/XXX-TEST/protocol/openid-connect/token"
```

And link keycloak on login page is redirecting to this place

`http://10.247.66.76:8080/oauth/login/keycloak/None?client_id=None&redirect_uri=http%3A%2F%2F10.247.66.76%3A8080%2Foauth%2Fcomplete%2Fkeycloak%2F%3Fredirect_state%3DRKvg4NotEH5q7urSjSXEOkgHD53dh0ZF&state=RKvg4NotEH5q7urSjSXEOkgHD53dh0ZF&response_type=code`

And the Nones in link URL looks like it is ignoring my configuration. I found that the part of code which should process the SOCIAL_AUTH_ variables is in settings.py file but the netbox does not print the file name during startup like the others files.

### Expected Behavior

I expted that the netbox will redirect me to keycloak.

### Docker Compose Version

v1.20.0

### Docker Version

```text
Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:02 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

### The git Revision

docker image v3.1

### The git Status

```text
v3.1 docker image
```

### Startup Command

docker compose up

### NetBox Logs

```text
⏳ Waiting on DB... (0s / 30s)
⚙️ Applying database migrations
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
...
```

### Content of docker-compose.override.yml

```yaml
Nothing.
```

**Comment by ryanmerolle** [comment]
I am pretty sure there has been no work to set SOCIAL_AUTH_* variables in docker with the ENV approach.  We would need someone familiar with the SOCIAL_AUTH_ function just introduced to submit a PR.

In the mean time you can expand what is included in the config by adding your own https://github.com/netbox-community/netbox-docker/blob/release/configuration/extra.py similar to what is commented out.

**Comment by cimnine** [comment]
As ryan said, the `SOCIAL_AUTH_*` variables are too dyamic and we can't have them all as regular environment variables. So you need to create a seperate configuration file, e.g. the `extra.py` configuration file. If you launch via `docker-compose` and did not modify the default mounts, then you should be able to put all the `SOCIAL_AUTH_*` variables in that extra configuration file and then restart the container. These files behave like the 'regular non-docker' NetBox configuration and you can put all the configurations that NetBox support in there.

(Of course, you can load the values for the variables from the ENV, but you need to implement this in your config file like we implemented it in the default `configuration.py` file. Have a look for inspiration there.)
