### ISSUE TITLE
Duplicated startup script

### ISSUE THREAD

**Issue by TomaszKrassowski** [netbox-community/netbox-docker#669]
### Current Behavior

The startup script for creating initial Cluster entities is duplicated: 
* 135_clusters.py 
* 140_clusters.py
![image](https://user-images.githubusercontent.com/30243513/147458788-05438697-467c-4949-988a-e6eb1e935750.png)

### Expected Behavior

The script shouldn't be duplicated, as the second run of the same script won't do anything, but it will probably only slower down the initialization (if there are many items in clusters.yml, I guess the script will make a get_or_create query for every item).

### Docker Compose Version

1.29.2

### Docker Version

```text
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:58:50 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

58a157983259d3a9992776dbe9f166ca11d2f987

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.

nothing to commit, working tree clean
```

### Startup Command

-

### NetBox Logs

```text
-
```

### Content of docker-compose.override.yml

```yaml
-
```

**Comment by ryanmerolle** [comment]
This is one of the easiest PRs for someone to raise. @TomaszKrassowski would you like to take a stab at it?

**Comment by TomaszKrassowski** [comment]
@ryanmerolle Yeah, sure. What are the steps to follow?

**Comment by ryanmerolle** [comment]
Fork the repo, delete one of the duplicate files, file a pull request.
