### ISSUE TITLE
after upgrade the docker container

### ISSUE THREAD

**Issue by DerMeso** [netbox-community/netbox-docker#686]
### Current Behavior

We have the problem after the update that the postgres does not want to resolve the address:

django.db.utils.OperationalError: could not translate host name "postgres" to address: Name does not resolv

### Expected Behavior

That the Docker container boots up and starts Postgres

### Docker Compose Version

docker-compose version 1.25.0, build unknown docker-py version: 4.1.0 CPython version: 3.9.2 OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021

### Docker Version

```text
Docker version 20.10.5+dfsg1, build 55c4c88
```

### The git Revision

58a157983259d3a9992776dbe9f166ca11d2f987

### The git Status

```text
On Branch release
Your branch is at the same state as 'origin/release'.

Nothing to commit, working directory unchanged
```

### Startup Command

docker-compose up

### NetBox Logs

```text
netbox_1               | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name does not resolve
netbox_1               | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox_1               | ⏳ Waiting on DB... (0s / 30s
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - 80:8080
```

**Comment by tobiasge** [comment]
This is probably not a bug. The Postgres version was upgraded in the last release. You need to follow the instructions to bring the database to the new version. It's mentioned in the release notes and documented in the Wiki.

**Comment by DerMeso** [comment]
And how do I get the redis updated in a container. The instructions are not very helpful unfortunately.

**Comment by DerMeso** [comment]
According to the container, redis is on the latest version:

redis-cache_1 | 1:C 11 Jan 2022 09:10:15.131 # redis version=6.2.6, bits=64, commit=000000, modified=0, pid=1, just started
