### ISSUE TITLE
Add GRAPHQL_ENABLED ENV

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox-docker#694]
### Desired Behavior

Add GRAPHQL_ENABLED ENV

### Contrast to Current Behavior

GRAPHQL_ENABLED is not a default configuration.py

### Required Changes

Add GRAPHQL_ENABLED to `configuration.py` and `netbox.env`

**Comment by cimnine** [comment]
I close the issue since (a) the PR is merged and (b) it does not provide any additional information over #695, so it's redundant. (I know it's common practice in the NetBox repo to do this.)
