### ISSUE TITLE
Using the /metrics endpoint repeatedly slowly increases memory usage

### ISSUE THREAD

**Issue by heapdavid** [netbox-community/netbox-docker#702]
### Current Behavior

I'm not sure whether this is related to netbox-docker or upstream netbox, but we're using netbox-docker so thought it best to report here first.

We're using the `/metrics` endpoint as a healthcheck for our docker swarm ingress/reverse proxy containers, and we've noticed that the netbox container's memory usage grows slowly over time:

![image](https://user-images.githubusercontent.com/88432183/154521777-56a1f0aa-0dfa-408e-975b-607bcdc8fbb0.png)
- y-axis is megabytes

There is no memory usage growth when we don't use the endpoint. We also used a static file to test instead and there was no increase.

Testing locally with docker-compose I can reproduce this, by visiting the endpoint repeatedly and watching `docker stats`. It looks like the memory is released 120 seconds after the last visit, so if one visits the endpoint more frequently than that, it's never released and just keeps growing.

### Expected Behavior

I expected that memory usage wouldn't grow over time from using the /metrics endpoint

### Docker Compose Version

Docker Compose version v2.2.1

### Docker Version

```text
Client: Docker Engine - Community
 Cloud integration: v1.0.22
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:39 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

58a157983259d3a9992776dbe9f166ca11d2f987

### The git Status

```text
git status
On branch release
Your branch is up to date with 'origin/release'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   env/netbox.env

no changes added to commit (use "git add" and/or "git commit -a")
```

### Startup Command

docker-compose up -d

### NetBox Logs

```text
netbox_1  | 172.21.0.1 - - [17/Feb/2022:15:45:30 +0000] "GET /metrics HTTP/1.1" 200 19552 "-" "curl/7.68.0"
netbox_1  | 172.21.0.1 - - [17/Feb/2022:15:45:30 +0000] "GET /metrics HTTP/1.1" 200 19549 "-" "curl/7.68.0"
netbox_1  | 172.21.0.1 - - [17/Feb/2022:15:45:30 +0000] "GET /metrics HTTP/1.1" 200 19551 "-" "curl/7.68.0"
netbox_1  | 172.21.0.1 - - [17/Feb/2022:15:45:30 +0000] "GET /metrics HTTP/1.1" 200 19552 "-" "curl/7.68.0"
netbox_1  | 172.21.0.1 - - [17/Feb/2022:15:45:30 +0000] "GET /metrics HTTP/1.1" 200 19663 "-" "curl/7.68.0"
netbox_1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox_1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox_1  | 2022/02/17 15:47:31 [notice] 8#8 process 32 exited with code 0
netbox_1  | 2022/02/17 15:51:17 [info] 34#34 "netbox" application started
netbox_1  | 172.21.0.1 - - [17/Feb/2022:15:51:17 +0000] "GET /metrics HTTP/1.1" 200 19552 "-" "curl/7.68.0"
netbox_1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox_1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox_1  | 2022/02/17 15:53:18 [notice] 8#8 process 34 exited with code 0
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - 8000:8080
  postgres:
    image: postgres:12-alpine
```

**Comment by kkthxbye-code** [comment]
I would assume this is an issue in [django-prometheus](https://github.com/korfuri/django-prometheus) or in the [official prometheus client](https://github.com/prometheus/client_python/tree/master/prometheus_client). Someone would probably need to profile the leak to find out where it is and then report it upstream. I might have a look if I get the time, but I can't promise anything.

As a workaround you can use the nginx-unit [limits](https://unit.nginx.org/configuration/#configuration-proc-mgmt-lmts) option. Set the requests parameter to whatever you find a sane value (not sure how often you are calling the endpoint and how much it leaks in each iteration). Nginx-unit sadly doesn't have support restarting workers based on a memory limit like other similar application servers.

**Comment by heapdavid** [comment]
Thanks, I've applied some limits to the workers, looks like it's keeping the memory usage down.

For reference on the graph above, the healthcheck runs every 5 seconds, but from 4 different ingress containers, so it would average out at one request every 1.25 seconds. I also reduced the healthcheck rate by various increments, which made the graph less steep each time.
