### ISSUE TITLE
NetBox v3.2 Beta

### ISSUE THREAD

**Issue by ingvaldlorentzen** [netbox-community/netbox-docker#704]
### Desired Behavior

Would love to have a `v3.2-beta1` Docker Image tag to test out the new beta. This is a pretty large release, so I presume it might be in beta for a while, so dedicated images with tags for the betas would be very convenient for testing!

### Contrast to Current Behavior

No `v3.2` images in Docker Hub

### Required Changes

Build `v3.2` images and push with appropriate tags

### Discussion: Benefits and Drawbacks

The benefits is that it allows people to more easily test the new beta releases of NetBox.   
Drawbacks is that it seems like it does require some manual work from the maintainers.

**Comment by tobiasge** [comment]
Images will be pushed in a few minutes with release 1.6.0.
