### ISSUE TITLE
LDAP not authenticating after upgrading to 3.2.3

### ISSUE THREAD

**Issue by abbyers73** [netbox-community/netbox-docker#762]
### Current Behavior

unable to login with AD credentials after upgrading from 3.0 to 3.2.3 

### Expected Behavior

Able to login with AD credentials same as prior to upgrade.

### Docker Compose Version

docker-compose version 1.28.5, build c4eb3a1f

### Docker Version

```text
Docker version 20.10.14, build a224086
```

### The git Revision

6a52a48b71187eabb16db2149060cffc159f5f72

### The git Status

```text
On branch release
```

### Startup Command

docker-compose up -d

### NetBox Logs

```text
netbox-docker_postgres_1 is up-to-date
netbox-docker_redis-cache_1 is up-to-date
netbox-docker_redis_1 is up-to-date
netbox-docker_netbox-housekeeping_1 is up-to-date
netbox-docker_netbox-worker_1 is up-to-date
netbox-docker_netbox_1 is up-to-date
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - 8088:8080
```

**Comment by tobiasge** [comment]
Not enough information. If the issue persists in the newest images please open with more details.
