### ISSUE TITLE
Enable bulk setting of location to null

### ISSUE THREAD

**Issue by suncruise** [netbox-community/netbox-docker#764]
### Desired Behavior

Enable setting the location field to null when editing multiple devices. in the WEBUI and via automation tools such as Ansible.

### Contrast to Current Behavior

Currently the only way to set the location to null is do this manually per device via the WEBUI. My attempts to code this also fail as null is not a valid option. I tried using Ansible.

### Required Changes

Enable setting of null when editing multiple devices via the WEBUI and also via scripts.

### Discussion: Benefits and Drawbacks

Improves the functionally by having the option to set the location field to null for multiple devices. 
Although there may not be many use-cases for this specific requirement, I do not see a downside and the type of capability. In addition this type of capability exists for other fields such as serial and airflow.

**Comment by cimnine** [comment]
You have opened the issue on the repository of the Docker image of NetBox. This seems to be an issue of the [NetBox](https://github.com/netbox-community/netbox) itself. Feel free to reopen the issue here if you believe this to be specific to the Docker build.
