### ISSUE TITLE
Social Auth OIDC missing dependencies

### ISSUE THREAD

**Issue by mttradebyte** [netbox-community/netbox-docker#769]
### Current Behavior

After enabling social auth, the following error is thrown, accompanied by a 500 status code, when attempting to visit Netbox:
```
<class 'ModuleNotFoundError'>

No module named 'jose'

Python version: 3.9.5
NetBox version: 3.2.3
```

There seems to be some discussion and extensive fettling done here https://github.com/netbox-community/netbox/discussions/8579 which seemed to get them working, but it feels like it should work out of the box ;)

### Expected Behavior

Users should be prompted with the OIDC login option

### Docker Compose Version

N/A (k8s)

### Docker Version

```text
N/A (k8s)
```

### The git Revision

image: netboxcommunity/netbox:v3.2-1.6.1

### The git Status

```text
N/A
```

### Startup Command

N/A

### NetBox Logs

```text
Nothing is shown in the logs, it seems to start perfectly fine. All the logs show is 500 responses to ELB health checks, that's it.
```

### Content of docker-compose.override.yml

```yaml
REMOTE_AUTH_ENABLED = True
REMOTE_AUTH_AUTO_CREATE_USER = True
REMOTE_AUTH_BACKEND = 'social_core.backends.okta_openidconnect.OktaOpenIdConnect'
SOCIAL_AUTH_OKTA_OPENIDCONNECT_KEY = 'xxx'
SOCIAL_AUTH_OKTA_OPENIDCONNECT_SECRET = 'xxx'
SOCIAL_AUTH_OKTA_OPENIDCONNECT_API_URL = 'https://xxxx.okta.com/oauth2/v1/authorize'
```

**Comment by tobiasge** [comment]
Closed with #786

Thanks to @rjmidau
