### ISSUE TITLE
Builds Broken due to textfsm/six

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox-docker#794]
### Current Behavior

Builds are breaking because NAPALM requires textfsm, but does not pin to any version.  

- google/textfsm#105

### Expected Behavior

Builds to work.

### Docker Compose Version

N/A

### Docker Version

```text
N/A
```

### The git Revision

N/A

### The git Status

```text
N/A
```

### Startup Command

docker-compose up

### NetBox Logs

```text
N/A
```

### Content of docker-compose.override.yml

```yaml
N/A
```

**Comment by ryanmerolle** [comment]
https://github.com/netbox-community/netbox-docker/runs/7295912839?check_suite_focus=true

**Comment by tobiasge** [comment]
See here: #793
