### ISSUE TITLE
No 3.2.6 ldap docker image available

### ISSUE THREAD

**Issue by IDerr** [netbox-community/netbox-docker#806]
### Current Behavior

I try to upgrade my setup for 3.2.6. 
I use a custom image from docker hub including LDAP, but no 3.2.6 version including LDAP is available.

### Expected Behavior

I expected that a 3.2.6-ldap version exist 

### Docker Compose Version

1.21.0

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:37 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimu
```

### The git Revision

main

### The git Status

```text
main
```

### Startup Command

docker-compose up -d 

### NetBox Logs

```text
.
```

### Content of docker-compose.override.yml

```yaml
.
```
Thanks a lot for your work !

**Comment by tobiasge** [comment]
See the release notes: https://github.com/netbox-community/netbox-docker/releases/tag/2.0.0
