### ISSUE TITLE
Image is missing bzip2, needed for backup command sugested in Wiki

### ISSUE THREAD

**Issue by herbetom** [netbox-community/netbox-docker#811]
### Current Behavior

I'm basically using the [command sugested inside the Wiki for backing up the media folder](https://github.com/netbox-community/netbox-docker/wiki/Troubleshooting#file-operations). Hoewer, it's failing since the second to last update:

```
root@stats ~ # docker compose --file /opt/docker/netbox/docker-compose.yml exec -T netbox tar c -jf - -C /opt/netbox/netbox/media ./ > /opt/docker/netbox/media-backup_borg.tar.bz2
/bin/sh: 1: bzip2: not found
tar: -: Cannot write: Broken pipe
tar: Child returned status 127
tar: Error is not recoverable: exiting now
root@stats ~ #
```

### Expected Behavior

I see two options:

1. add `bzip2` to the image. This would allow people to do backups as they are used to and it's less likely that people end up not having backups because they didn't notice that their backup failed.
2. change the Wiki to another command. For Example the proposed change by @u1735067 in https://github.com/netbox-community/netbox-docker/issues/262#issuecomment-607795598 (using gzip instead of bzip2) seems to work fine.

### Docker Compose Version

Docker Compose version v2.0.1

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:17 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

ebda4660de9edc5731497e92a98395b4ec16e613

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.

nothing to commit, working tree clean
```

### Startup Command

docker compose up -d

### NetBox Logs

```text
not releavant
```

### Content of docker-compose.override.yml

```yaml
not relevant
```

**Comment by tobiasge** [comment]
Closed with #836
