### ISSUE TITLE
Problem with initializing device type and using anchors/alias

### ISSUE THREAD

**Issue by jose-pr** [netbox-community/netbox-docker#826]
### Current Behavior

I was using a definition of a current device type to initialize another one, basically two versions of a switch one with front to rear airflow and another with rear to front airflow. So i aliased the default model added the unique prop model, .. and noticed that components such as interfaces and power ports were being populated by only one element without a name for all but the first device declaration.

### Expected Behavior

When using an alias to not have to recreate components that are the same between type for it to work.

Issue seems seems to come from using pop to get the name for a property, as the yaml loader seems to share the common object when aliasing is used. 
Poossible solution that work for me is doing a copy.deepcopy of params, to create new object and for the pop not to affect other device types. 
Other possible solution would be not to pop.

### Docker Compose Version

Not a docker issue

### Docker Version

```text
Not a docker issue.
```

### The git Revision

Main/master

### The git Status

```text
Clean
```

### Startup Command

Docker compose up

### NetBox Logs

```text
-
```

### Content of docker-compose.override.yml

```yaml
-
```

**Comment by tobiasge** [comment]
Initializers were extracted to a plugin
