### ISSUE TITLE
3.2.8 version of LDAP variant

### ISSUE THREAD

**Issue by gijs007** [netbox-community/netbox-docker#828]
### Desired Behavior

I'm using the LDAP variant of the Docker container, and receive a message that there is a new version: 3.2.8. When updating I'd expect to receive this latest stable version.

### Contrast to Current Behavior

After updating I still receive an older 3.2.5 version. It appears that the Docker repo for the LDAP variant hasn't been updated in two months.

**Comment by tobiasge** [comment]
Please read the release notes.
