### ISSUE TITLE
Netbox v3.3.0 Cable Change breaks docker test script of cables

### ISSUE THREAD

**Issue by ns1pelle** [netbox-community/netbox-docker#834]
### Current Behavior

https://github.com/netbox-community/netbox-docker/runs/7966943768?check_suite_focus=true#step:7:2724

The build fails, and no docker images created

### Expected Behavior

Docker image should be created.

The scripts should pass

### Docker Compose Version

Docker Compose (Docker Inc., 2.9.0+azure-1)

### Docker Version

```text
Client:
   Version:           20.10.17+azure-1
   API version:       1.41
   Go version:        go1.17.11
   Git commit:        100c70180fde3601def79a59cc3e996aa553c9b9
   Built:             Mon Jun  6 21:36:39 UTC 2022
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true
  
  Server:
   Engine:
    Version:          20.10.17+azure-1
    API version:      1.41 (minimum version 1.12)
    Go version:       go1.17.11
    Git commit:       a89b84221c8560e7a3dee2a653353429e7628424
    Built:            Mon Jun  6 22:32:38 2022
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.5.13+azure-1
    GitCommit:        a17ec496a95e55601607ca50828147e8ccaeebf1
   runc:
    Version:          1.0.3
    GitCommit:        f46b6ba2c9314cfc8caae24a32ec5fe9ef1059fe
   docker-init:
    Version:          0.19.0
    GitCommit:
```

### The git Revision

ebda4660de9edc5731497e92a98395b4ec16e613

### The git Status

```text
On Branch Main
```

### Startup Command

Run IMAGE="docker.io/netboxcommunity/netbox:v3.3.0" ./test.sh

### NetBox Logs

```text
https://github.com/netbox-community/netbox-docker/runs/7966943768?check_suite_focus=true#step:7:2724
```

### Content of docker-compose.override.yml

```yaml
N/A
```

**Comment by ns1pelle** [comment]
It looks like @tobiasge is looking to remove the scripts from the docker image process to ignore this. But is there agreement on this and is there a timeline?

**Comment by halo779** [comment]
Based on PR https://github.com/netbox-community/netbox-docker/pull/831 looks like the changes just need to go through a change review.

Not really much point in rushing too hard, or you do land with problems like experienced.
Very much CICD doing it's job 👍 


I'll certainly be deploying soon as it comes out, our network engineers are very keen on the L2VPN modeling as one of those Key nails in the coffin to get rid of horrid wiki documentation!

**Comment by ananace** [comment]
Got some people who are very eager to start using N:M mapping of cables at us as well, since we're using MPO breakouts quite heavily.

**Comment by tobiasge** [comment]
Initializers were extracted to a plugin
