### ISSUE TITLE
netbox version 3.3.0 or newer not build automatically ?

### ISSUE THREAD

**Issue by miconx** [netbox-community/netbox-docker#837]
### Current Behavior

the newest version of netbox ist not being build automatically ?
the last release of netbox-docker is 27 days ago?

### Expected Behavior

if i youse my dockerfile with ARG FROM_IMAGE=netboxcommunity/netbox 
and the tag "latest" the netbox version is 2.9.0 not 3.3.1

### Docker Compose Version

1.29.2

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:46 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:00:51 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

ebda4660de9edc5731497e92a98395b4ec16e613

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.

nothing to commit, working tree clean
```

### Startup Command

docker compose up

### NetBox Logs

```text
no error logs
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - 8000:8080
```

**Comment by cimnine** [comment]
Thanks. We're aware. There are currently some blockers because of the intializers. We're in the process of removing them from the default image now so that we're not blocked by them in the future.

Furthermore, please remember, that since we're doing this work mainly in our spare time, things may take their time to get sorted out.

**Comment by tobiasge** [comment]
New version was release. Image should be pushed soon.
