### ISSUE TITLE
Version 2.0.0 does not have -ldap tags

### ISSUE THREAD

**Issue by alarsing** [netbox-community/netbox-docker#838]
### Desired Behavior

You should remove lines:
Then there is currently one extra tags for each of the above tags:

-ldap: These container images contain additional dependencies and configuration files for connecting NetBox to an LDAP directory. [Learn more about that in our wiki](https://github.com/netbox-community/netbox-docker/wiki/LDAP).

### Contrast to Current Behavior

This is still in the readme

**Comment by tobiasge** [comment]
This was done in PR #825.
