### ISSUE TITLE
Update nginx-unit and allow custom nginx-unit.json config

### ISSUE THREAD

**Issue by tagur87** [netbox-community/netbox-docker#875]
### Desired Behavior

We are running into an issue with nginx-unit used in the netbox-docker image where we are getting an HTTP 431 due to the large header size of our k8s ingress.

Nginx-unit team is working on a fix(https://github.com/nginx/unit/pull/771), but we will need this project to be updated once this is released. 

We will also need to be able to add the following config entries to the nginx-unit.json file

```json
"settings": {
    "http": {
        "large_header_buffer_size": 16384
    }
},
```

### Contrast to Current Behavior

There does not appear to be a way to add a custom nginx-unit.json config file through an environment variable or similar. We would prefer this be an option so we don't have to roll our own image.

### Required Changes

Add an option to allow a custom nginx-unit config file to be provided to a consumer of the docker image.

### Discussion: Benefits and Drawbacks

This would allow others to specify unique configurations for nginx-unit in their projects.

**Comment by cimnine** [comment]
Isn't it possible to mount a custom nginx-unit config file where our default file is?

With an ENV variable you'd have to either build your image as well, or mount a config file. I believe it's possible to skip the ENV variable part and already mount a custom config file to the proper location.

**Comment by tagur87** [comment]
I was initially thinking of something like how it's done in https://github.com/netbox-community/netbox-docker/blob/release/configuration/configuration.py but since unit is external to netbox that doesn't make much sense. 

I agree that we can just override it in our deployment with a custom file. 

Will close this for now and reopen when the new version of nginx-unit is released to request an update.
