### ISSUE TITLE
Update Vulnerable OpenSSL: 3.0.2->3.0.7 (image “netboxcommunity/netbox:v3.2”)

### ISSUE THREAD

**Issue by OlegMudryak** [netbox-community/netbox-docker#877]
### Desired Behavior

Updated image “netboxcommunity/netbox:v3.2” with the non-vulnerable OpenSSL version (3.0.7).

### Contrast to Current Behavior

The current version uses vulnerable OpenSSL 3.0.2:
https://www.openssl.org/news/vulnerabilities.html

### Required Changes

Update the current image “netboxcommunity/netbox:v3.2”  ( https://hub.docker.com/r/netboxcommunity/netbox  ) with the non-vulnerable OpenSSL version (3.0.7). 

### Discussion: Benefits and Drawbacks

Recently published OpenSSL vulnerability (https://github.com/advisories/GHSA-h8jm-2x53-xhp5 and https://github.com/advisories/GHSA-8rwr-x37p-mx23):
https://www.openssl.org/news/vulnerabilities.html
The current version of the “netboxcommunity/netbox:v3.2” image uses vulnerable OpenSSL version: 3.0.2
https://hub.docker.com/r/netboxcommunity/netbox 
Could you please update the image using non-vulnerable OpenSSL version (3.0.7)?

**Comment by cimnine** [comment]
Duplicate of https://github.com/netbox-community/netbox-docker/issues/874
