### ISSUE TITLE
Upgrading docker images fails

### ISSUE THREAD

**Issue by claremont-awilson** [netbox-community/netbox-docker#901]
### Current Behavior

I received a notification that v3.4.0 was available in the GUI (was on v3.3.9 I think, only setup this environment on 08/12/2022). I followed [these](https://github.com/netbox-community/netbox-docker/wiki/Updating) steps in the wiki.

After executing docker-compose up the logs started erroring with: 

> netbox-docker-redis-1                | 1:M 19 Dec 2022 11:15:27.063 * DB loaded from append only file: 0.069 seconds
netbox-docker-redis-1                | 1:M 19 Dec 2022 11:15:27.063 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
netbox-docker-redis-1                | 1:M 19 Dec 2022 11:15:27.063 * Ready to accept connections
netbox-docker-postgres-1             |
netbox-docker-postgres-1             | PostgreSQL Database directory appears to contain a database; Skipping initialization
netbox-docker-postgres-1             |
netbox-docker-postgres-1             | 2022-12-19 11:15:27.470 UTC [1] FATAL:  database files are incompatible with server
netbox-docker-postgres-1             | 2022-12-19 11:15:27.470 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 15.1.
netbox-docker-postgres-1 exited with code 1
netbox-docker-netbox-1               | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1               | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1               | ⏳ Waiting on DB... (0s / 30s)
netbox-docker-netbox-1               | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1               | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1               | ⏳ Waiting on DB... (3s / 30s)
netbox-docker-netbox-1               | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1               | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1               | ⏳ Waiting on DB... (6s / 30s)
netbox-docker-netbox-1               | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1               | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1               | ⏳ Waiting on DB... (9s / 30s)
netbox-docker-netbox-1               | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1               | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1               | ⏳ Waiting on DB... (12s / 30s)
netbox-docker-netbox-1               | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1               | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1               | ⏳ Waiting on DB... (15s / 30s)
netbox-docker-netbox-1               | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1               | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1               | ⏳ Waiting on DB... (18s / 30s)
netbox-docker-netbox-1               | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1               | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1               | ⏳ Waiting on DB... (21s / 30s)
netbox-docker-netbox-1               | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1               | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1               | ⏳ Waiting on DB... (24s / 30s)
netbox-docker-netbox-1               | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1               | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1               | ⏳ Waiting on DB... (27s / 30s)
netbox-docker-netbox-1               | ❌ Waited 30s or more for the DB to become ready.
netbox-docker-netbox-1 exited with code 1
netbox-docker-redis-1                | 1:M 19 Dec 2022 11:20:27.064 * 100 changes in 300 seconds. Saving...
netbox-docker-redis-1                | 1:M 19 Dec 2022 11:20:27.065 * Background saving started by pid 14
netbox-docker-redis-1                | 14:C 19 Dec 2022 11:20:27.072 * DB saved on disk
netbox-docker-redis-1                | 14:C 19 Dec 2022 11:20:27.072 * Fork CoW for RDB: current 2 MB, peak 2 MB, average 2 MB
netbox-docker-redis-1                | 1:M 19 Dec 2022 11:20:27.166 * Background saving terminated with success
^CGracefully stopping... (press Ctrl+C again to force)

And so now the database won't start.

I tried the troubleshooting steps to take a backup of the database to perform a restore, but the container won't start, it just errors out with the FATAL messages about Postgres v14 not compatible with v15.1. 

### Expected Behavior

I expected the upgrade process to work, or at least provide a warning if the postgres version jump was going to cause an issue.

### Docker Compose Version

Docker Compose version v2.14.0

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:04:24 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:02:38 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12
  GitCommit:        a05d175400b1145e5e6a735a6710579d181e7fb0
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

39c7de4af41703108f8b3af7274bc65813c41799

### The git Status

```text
# On branch release
# Your branch is ahead of 'origin/release' by 20 commits.
#   (use "git push" to publish your local commits)
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   configuration/logging.py
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       docker-compose.override.yml.broken
no changes added to commit (use "git add" and/or "git commit -a")
```

### Startup Command

docker-compose up

### NetBox Logs

```text
netbox-docker-netbox-1  | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1  | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1  | ⏳ Waiting on DB... (0s / 30s)
netbox-docker-netbox-1  | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1  | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1  | ⏳ Waiting on DB... (3s / 30s)
netbox-docker-netbox-1  | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1  | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1  | ⏳ Waiting on DB... (6s / 30s)
netbox-docker-netbox-1  | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1  | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1  | ⏳ Waiting on DB... (9s / 30s)
netbox-docker-netbox-1  | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1  | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1  | ⏳ Waiting on DB... (12s / 30s)
netbox-docker-netbox-1  | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1  | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1  | ⏳ Waiting on DB... (15s / 30s)
netbox-docker-netbox-1  | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1  | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1  | ⏳ Waiting on DB... (18s / 30s)
netbox-docker-netbox-1  | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1  | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1  | ⏳ Waiting on DB... (21s / 30s)
netbox-docker-netbox-1  | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1  | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1  | ⏳ Waiting on DB... (24s / 30s)
netbox-docker-netbox-1  | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
netbox-docker-netbox-1  | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-docker-netbox-1  | ⏳ Waiting on DB... (27s / 30s)
netbox-docker-netbox-1  | ❌ Waited 30s or more for the DB to become ready.
```

### Content of docker-compose.override.yml

```yaml
version: "3.4"
services:
  netbox:
    ports:
      - 8001:8080
    environment:
      REMOTE_AUTH_ENABLED: "True"
      REMOTE_AUTH_BACKEND: "netbox.authentication.LDAPBackend"
      AUTH_LDAP_SERVER_URI: "ldap://ddg-dfgdfg-dgdgdg.dgdfg.dgdg.dgdg"
      AUTH_LDAP_USER_SEARCH_BASEDN: "cn=users,cn=accounts,dc=dgdg,dc=dgdg,dc=dgdg"
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "cn=groups,cn=accounts,dc=dgdg,dc=dgdg,dc=dgdg"
      AUTH_LDAP_REQUIRE_GROUP_DN: "cn=netbox-users,cn=groups,cn=accounts,dc=dgdg,dc=dgdg,dc=dgdg"
      AUTH_LDAP_IS_ADMIN_DN: "cn=netbox-admin,cn=groups,cn=accounts,dc=dgdg,dc=dgdg,dc=dgdg"
      AUTH_LDAP_IS_SUPERUSER_DN: "cn=infra-team,cn=groups,cn=accounts,dc=dgdg,dc=dgdg,dc=dgdg"
      LDAP_IGNORE_CERT_ERRORS: "true"
      AUTH_LDAP_BIND_AS_AUTHENTICATING_USER: "true"
      AUTH_LDAP_USER_DN_TEMPLATE: "uid=%(user)s,cn=users,cn=accounts,dc=dgdg,dc=dgdg,dc=dgdg"
      AUTH_LDAP_MIRROR_GROUPS: "true"
```

**Comment by tobiasge** [comment]
Please read the [release notes](https://github.com/netbox-community/netbox-docker/releases/tag/2.4.0) and this [documentation](https://github.com/netbox-community/netbox-docker/wiki/Updating#postgresql-update).
