### ISSUE TITLE
Unable to start new netbox release 2.4.0: containers unhealthy

### ISSUE THREAD

**Issue by kangchen06** [netbox-community/netbox-docker#907]
### Current Behavior

After a basic clone, and rename docker-compose.override.yml.example to docker-compose.override.yml, unable to start netbox.

'Container unhealthy'

### Expected Behavior

Starting an 'out-of-the-box' docker netbox. 

### Docker Compose Version

docker-compose version 1.29.2

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:47:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:50 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

39c7de4af41703108f8b3af7274bc65813c41799

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.

nothing to commit, working tree clean
```

### Startup Command

docker-compose up

### NetBox Logs

```text
netbox-docker_postgres_1 is up-to-date
netbox-docker_redis-cache_1 is up-to-date
netbox-docker_redis_1 is up-to-date
Starting netbox-docker_netbox_1 ... done
Creating netbox-docker_netbox-housekeeping_1 ... done

ERROR: for netbox-worker  Container "c5e65652034f" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - 8000:8080
```

**Comment by serge-deiss-obt** [comment]
**I have the same Issue:**

![Snag_61c409b](https://user-images.githubusercontent.com/86469440/209338159-c4818498-abcf-4803-a9a2-c69bdf2c9960.png)

Docker Compose version v2.14.1

```
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:30:24 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:28:33 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by tobiasge** [comment]
I think the problem are the new health checks. It might be that the [start_period](https://github.com/netbox-community/netbox-docker/blob/39c7de4af41703108f8b3af7274bc65813c41799/docker-compose.yml#L12) is to short.
Could you try to set value to maybe 90 oder 120 seconds?

**Comment by serge-deiss-obt** [comment]
I did a restore of the Database because in the new Instance according [postgresql-update](https://github.com/netbox-community/netbox-docker/wiki/Updating#postgresql-update)
With Health Check [start_period](https://github.com/netbox-community/netbox-docker/blob/39c7de4af41703108f8b3af7274bc65813c41799/docker-compose.yml#L12) to 360s it still failed. Waiting on Netbox Container to finalise.

In my Case it seams to fail based on deprecated data:

```
netbox-docker-netbox-1       |     raise DataError(
netbox-docker-netbox-1       | django.db.utils.DataError: Unable to proceed with deleting contact fields from Provider model: Found 2 providers with legacy contact data. Please ensure all legacy provider contact data has been migrated to contact objects before proceeding. Or, set the NETBOX_DELETE_LEGACY_DATA environment variable to bypass this safeguard and delete all legacy provider contact data.
netbox-docker-netbox-1       |   Applying circuits.0040_provider_remove_deprecated_fields...⚙️ Applying database migrations
netbox-docker-netbox-1       | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-docker-netbox-1       | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-docker-netbox-1       | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-docker-netbox-1       | 🧬 loaded config '/etc/netbox/config/plugins.py'

```
_Edited: 23.12.22 16:28_
In Addition to the extended Start_Period , everything works after adding "docker-compose.override.yml":
![Snag_6b207bf](https://user-images.githubusercontent.com/86469440/209360056-9ca5342f-39bc-4f83-97ff-5b40acd92740.png)

So my Case is solved, thx mates.

**Comment by kangchen06** [comment]
Thank you for your quick answers.
I have changed the start_period in docker-compose.yml for the netbox-housekeeping service / healthcheck and netbox-worker / healthcheck (because the issue arrives sometimes on both) without success.

With a "watch docker ps -a" I can see the main service "netbox" starts but stops after only 15s.

**Comment by kangchen06** [comment]
On my side I try to start Netbox with a brand new DB.

**Comment by tobiasge** [comment]
> Thank you for your quick answers. I have changed the start_period in docker-compose.yml for the netbox-housekeeping service / healthcheck and netbox-worker / healthcheck (because the issue arrives sometimes on both) without success.
> 
> With a "watch docker ps -a" I can see the main service "netbox" starts but stops after only 15s.

Do you have set a value for `ALLOWED_HOSTS`? If yes, please try to include `localhost` into it.

**Comment by serge-deiss-obt** [comment]
> Thank you for your quick answers. I have changed the start_period in docker-compose.yml for the netbox-housekeeping service / healthcheck and netbox-worker / healthcheck (because the issue arrives sometimes on both) without success.
> 
> With a "watch docker ps -a" I can see the main service "netbox" starts but stops after only 15s.

I changed the "start_period" only in the netbox container itself which did not solve my perticular issue as on my instance it takes 35s with a pre existing DB so below the default value.

What do you see if you run the "docker compose up" you should see the logs and where it might fail.

**Comment by kangchen06** [comment]
See logs below:

==================================================================
jdoe@dksrv02:~/containers/netbox-docker$ docker-compose up
Creating network "netbox-docker_default" with the default driver
Creating netbox-docker_postgres_1    ... done
Creating netbox-docker_redis-cache_1 ... done
Creating netbox-docker_redis_1       ... done
Creating netbox-docker_netbox_1      ... done
Creating netbox-docker_netbox-housekeeping_1 ... done

ERROR: for netbox-worker  Container "646ea5e927ce" is unhealthy.
ERROR: Encountered errors while bringing up the project.

============================================================
jdoe@dksrv02:~$ docker logs netbox-docker_netbox_1
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
💡 Superuser Username: admin, E-Mail: admin@example.com
✅ Initialisation is done.
⏳ Waiting for control socket to be created... (1/10)
2022/12/23 15:47:49 [warn] 6#6 Unit is running unprivileged, then it cannot use arbitrary user and group.
2022/12/23 15:47:49 [info] 6#6 unit 1.27.0 started
2022/12/23 15:47:49 [info] 13#13 discovery started
2022/12/23 15:47:49 [notice] 13#13 module: python 3.10.4 "/usr/lib/unit/modules/python3.10.unit.so"
2022/12/23 15:47:49 [info] 6#6 controller started
2022/12/23 15:47:49 [notice] 6#6 process 13 exited with code 0
2022/12/23 15:47:49 [info] 15#15 router started
2022/12/23 15:47:49 [info] 15#15 OpenSSL 3.0.2 15 Mar 2022, 30000020

**Comment by resparis** [comment]
I have the same problem, even after changing the start_period on every container

resparis@ubuntu:/new_box/netbox-docker$ more docker-compose.yml | grep start
      start_period: 120s
      start_period: 120s
      start_period: 120s
resparis@ubuntu:/new_box/netbox-docker$ sudo docker-compose up
netbox-docker_redis_1 is up-to-date
Starting netbox-docker_postgres_1 ...
Starting netbox-docker_postgres_1 ... done
netbox-docker_netbox_1 is up-to-date

ERROR: for netbox-housekeeping  Container "1f0290cbed7c" is unhealthy.

ERROR: for netbox-worker  Container "1f0290cbed7c" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by bloomcake** [comment]
I just had the same problem. However, with me only `localhost` was missing in `ALLOWED_HOSTS`. A bit confusing was that they are separated with a space, I'm used to it with comma, but then could figure it out with a look into `configuration.py`. jfyi

**Comment by tobiasge** [comment]
Fixed for next release.

**Comment by anders-m** [comment]
> 

In which file did you add localhost?

**Comment by vhristev** [comment]
@anders-m 
```
 # grep -ri ALLOWED_HOSTS ./
./configuration/configuration.py:# Example: ALLOWED_HOSTS = ['netbox.example.com', 'netbox.internal.local']
./configuration/configuration.py:ALLOWED_HOSTS = environ.get('ALLOWED_HOSTS', '*').split(' ')

```

**Comment by salimmariche1** [comment]
i've the same issue whene i try to build, whene i do docker-compose up --build i've this message error : 
ERROR: for netbox-housekeeping  Container "2701a86b4cac" is unhealthy.

ERROR: for netbox-worker  Container "2701a86b4cac" is unhealthy.
ERROR: Encountered errors while bringing up the project.
but whene i just do docker-compose up it works absolutely normal.
what can i do to solve this issue
