### ISSUE TITLE
upgrade not work

### ISSUE THREAD

**Issue by dg1kwa** [netbox-community/netbox-docker#924]
### Current Behavior

Upgrade or new installation I become this:

docker-compose pull
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.netbox-housekeeping.depends_on contains an invalid type, it should be an array
services.netbox-worker.depends_on contains an invalid type, it should be an array

### Expected Behavior

how can fix?

### Docker Compose Version

docker-compose version 1.25.0, build unknown docker-py version: 4.1.0 CPython version: 3.8.10 OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

### Docker Version

```text
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.2
  Git commit:       20.10.12-0ubuntu2~20.04.1
  Built:            Thu Feb 10 15:03:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu1~20.04.6
  GitCommit:
 runc:
  Version:          1.1.0-0ubuntu1~20.04.2
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### The git Revision

39c7de4af41703108f8b3af7274bc65813c41799

### The git Status

```text
Auf Branch release
Ihr Branch ist auf demselben Stand wie 'origin/release'.

nichts zu committen, Arbeitsverzeichnis unverändert
```

### Startup Command

docker compuse up

### NetBox Logs

```text
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.netbox-housekeeping.depends_on contains an invalid type, it should be an array
services.netbox-worker.depends_on contains an invalid type, it should be an array
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - 8000:8080
```

**Comment by tobiasge** [comment]
Please read the README.md:

This project relies only on Docker and docker-compose meeting these requirements:
- The Docker version must be at least 20.10.10.
- The containerd version must be at least 1.5.6.
- The docker-compose version must be at least 1.28.0.

To check the version installed on your system run docker --version and docker-compose --version.
