### ISSUE TITLE
Error IPV6 launch Netbox version v3.4.1

### ISSUE THREAD

**Issue by chrisho95** [netbox-community/netbox-docker#925]
### Current Behavior

When I launch Netbox version 3.4.1 with docker-compose, I have the following error coming up.

2023/01/10 13:50:17 [notice] 7#7 process 14 exited with code 0
2023/01/10 13:50:17 [info] 16#16 router started
2023/01/10 13:50:17 [info] 16#16 OpenSSL 3.0.2 15 Mar 2022, 30000020
âï¸ Applying configuration from /etc/unit/nginx-unit.json
2023/01/10 13:50:18 [alert] 7#7 socket("[::]:8080") failed (97: Address family not supported by protocol)
2023/01/10 13:50:18 [alert] 16#16 failed to apply new conf
â ï¸ Could no load Unit configuration
2023/01/10 13:50:18 [notice] 7#7 process 12 exited with code 1
2023/01/10 13:50:18 [notice] 7#7 process 15 exited with code 0
2023/01/10 13:50:18 [notice] 7#7 process 16 exited with code 0

The "nginx-unit.json" file has a new session in the file:

"listeners": {
"0.0.0.0:8080": {
"pass": "routes"
},
"[::]:8080": {
"pass": "routes"
}
},

When I remove the IPV6 part, Netbox launches correctly.

"listeners": {
"0.0.0.0:8080": {
"pass": "routes"
}
},

I would like to not use IPV6 IPs but don't modify the file "nginx-unit.json".

BR,

Chris.

### Expected Behavior

The launch of netbox is going well.

### Docker Compose Version

docker-compose version 1.18.0, build 8dd22a9 docker-py version: 2.6.1 CPython version: 3.6.8 OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:30:24 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:28:33 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

N/A

### The git Status

```text
N/A
```

### Startup Command

docker-compose up -d

### NetBox Logs

```text
ð§¬ loaded config '/etc/netbox/config/configuration.py'
ð¡ Superuser Username: admin, E-Mail: admin@example.com
â
 Initialisation is done.
â³ Waiting for control socket to be created... (1/10)
2023/01/10 13:50:17 [warn] 7#7 Unit is running unprivileged, then it cannot use arbitrary user and group.
2023/01/10 13:50:17 [info] 7#7 unit 1.27.0 started
2023/01/10 13:50:17 [info] 14#14 discovery started
2023/01/10 13:50:17 [notice] 14#14 module: python 3.10.4 "/usr/lib/unit/modules/python3.10.unit.so"
2023/01/10 13:50:17 [info] 7#7 controller started
2023/01/10 13:50:17 [notice] 7#7 process 14 exited with code 0
2023/01/10 13:50:17 [info] 16#16 router started
2023/01/10 13:50:17 [info] 16#16 OpenSSL 3.0.2 15 Mar 2022, 30000020
âï¸ Applying configuration from /etc/unit/nginx-unit.json
2023/01/10 13:50:18 [alert] 7#7 socket(\"[::]:8080\") failed (97: Address family not supported by protocol)
2023/01/10 13:50:18 [alert] 16#16 failed to apply new conf
â ï¸ Could no load Unit configuration
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
    - 8081:8080
```

**Comment by tobiasge** [comment]
Added [section](https://github.com/netbox-community/netbox-docker/wiki/Troubleshooting#netbox-container-doesnt-start-when-ipv6-is-disabled) to the Wiki.
