### ISSUE TITLE
Make netbox container bind mounts optional.

### ISSUE THREAD

**Issue by timrabl** [netbox-community/netbox-docker#937]
### Desired Behavior

Currently the bind mount in the `docker-compose.yml` and `docker-compose.test.yml` files are fixed. And users are told to customize the overwrite compose file.

The paths `startup_scripts`, `initializers`, `configuration` are already copied to the container image on build.
https://github.com/netbox-community/netbox-docker/blob/ebda4660de9edc5731497e92a98395b4ec16e613/Dockerfile#L73-L75

So for the standard netbox docker user there is no reason for bind mounts. IMO this is a very huge overhead. Incidentally, this is also an implicit behavior of software. When installing a new raw NetBox docker instance, this creates paths on the host for each source bind mount path in the compose files that is not found on the host system.

Some users may have a read only filesystem, so this found result in a crash at compose stack startup. Some users don't care and ignore it, or they care and have to manually adjust the `docker-compose.yaml` or `docker-compose.overwrite.yaml` file.

OK, someone could argue, why aren't you just overwrite the bind mounts in the `docker-compose.overide.yml` file ? Well, why should i ? Why should the person that does not need to make any modifications to any scripts or configurations, be forced to override the default behaviour of a software ?

Wouldn't it be better to switch this case. Let's say someone would like to extend the `configuration/configuration.py` with its own modifications ? So he could than clone the original configurations path, extend it and then copy it into the container with a bind mount in the `docker-compose.override.yml` file ?

Sure it would be better, to build a custom image, instead of a bind mount, but that's not the point now.

With scenario two, a raw native netbox docker deployment would not create local files/paths, 
or overwrites anything. It would be just configuration via environment and starting the compose stack.

### Contrast to Current Behavior

Users are no longer forced to modify the `docker-compose.yaml`, `docker-compose.test.yaml` and/or `docker-compose.overwrite.yaml` file if they don't want the `startup_scripts`, `initializers`, `configuration` paths to be created on container startup.

Instead, anyone who wants to mount paths to a container must mount them via bind mounts. Either in `docker-compose.yaml` or better in `docker-compose.overwrite.yaml`. Which is the intent of an overwrite file.

### Required Changes

Remove the following lines from `docker-compose.yml` file:

https://github.com/netbox-community/netbox-docker/blob/39c7de4af41703108f8b3af7274bc65813c41799/docker-compose.yml#L17-L19

Remove the following lines from `docker-compose.test.yml` file:
https://github.com/netbox-community/netbox-docker/blob/39c7de4af41703108f8b3af7274bc65813c41799/docker-compose.test.yml#L15

https://github.com/netbox-community/netbox-docker/blob/39c7de4af41703108f8b3af7274bc65813c41799/docker-compose.test.yml#L17-L18

### Discussion: Benefits and Drawbacks

See above...

**Comment by tobiasge** [comment]
With the changes made in Netbox 3.5 the bind mounts for reports and scripts have been converted to volumes like the media file mount.
This leaves only the configuration bind mount. This makes using the repository much easier as users only have to change the configuration files in the directory.
The remaining bind mount in the test files is needed to make the output of the tests useful, so it will stay too.
