### ISSUE TITLE
Update nginx-unit

### ISSUE THREAD

**Issue by tagur87** [netbox-community/netbox-docker#944]
### Desired Behavior

As indicated in #875, we need some added functionality in nginx-unit to support large header sizes. This was added in nginx-unit v1.29.

### Contrast to Current Behavior

We are unable to customize the max allowed header size, which causes errors in our environment

### Required Changes

Update nginx-unit package to latest supported version

**Comment by tagur87** [comment]
@tobiasge  initially indicated there were some issues with the latest update and compatibility, however another version v1.30 has been released since then.
https://github.com/netbox-community/netbox-docker/pull/899#issuecomment-1355440824

**Comment by tobiasge** [comment]
At the moment the Nginx Unit homepage still lists 1.29 as the current release.

**Comment by tagur87** [comment]
> At the moment the Nginx Unit homepage still lists 1.29 as the current release.


Sorry I misread the NXT_VERSION field as current version: https://github.com/nginx/unit/blob/master/version#L4

Is the issue you were running into related to this? https://github.com/nginx/unit/issues/817

**Comment by tobiasge** [comment]
> Is the issue you were running into related to this? [nginx/unit#817](https://github.com/nginx/unit/issues/817)

Yes, that was the problem. See this thread: https://mailman.nginx.org/pipermail/unit/2022-December/CTHXK37SGZICG2KTFCTURYYSZWUO74FK.html

**Comment by tobiasge** [comment]
Fixed with #951
