### ISSUE TITLE
docker-entrypoint.sh needs to be updated to run `manage.py reindex --lazy` after migrations

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox-docker#947]
### Desired Behavior

`manage.py reindex --lazy` needs to be executed on startup because of https://github.com/netbox-community/netbox/issues/11787

### Contrast to Current Behavior

The search index is not regenerated as it should be.

### Required Changes

The following command:

`./manage.py reindex --lazy`

Should be added somewhere here (after migrations have run):
https://github.com/netbox-community/netbox-docker/blob/39c7de4af41703108f8b3af7274bc65813c41799/docker/docker-entrypoint.sh#L39-L49

### Discussion: Benefits and Drawbacks

Users will be able to search for IPAddresses, Aggregates and Prefixes again.

Any users that have already updated can run the reindex command manually.

**Comment by tobiasge** [comment]
Closed with #948
