### ISSUE TITLE
Docker Hub Build's for v3.4.7 missing

### ISSUE THREAD

**Issue by Delta1977** [netbox-community/netbox-docker#974]
### Current Behavior

.......

### Expected Behavior

Docker Hub Build's for v3.4.7 missing

### Docker Compose Version

...

### Docker Version

```text
...
```

### The git Revision

...

### The git Status

```text
...
```

### Startup Command

...

### NetBox Logs

```text
...
```

### Content of docker-compose.override.yml

```yaml
...
```

**Comment by kkthxbye-code** [comment]
Edit: I see you were faster than me and it's already fixed :)

@tobiasge - social-auth-core was bumped in 3.4.7:

https://github.com/netbox-community/netbox/commit/4eaba7993f63a29bf0a3b632be87e7f9be83ef11#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552

Bumping social-auth-core[all] to 4.4.0 in requirements-container.txt fixes it for me locally:
https://github.com/netbox-community/netbox-docker/blob/release/requirements-container.txt

**Comment by tobiasge** [comment]
Will be fixed in: https://github.com/netbox-community/netbox-docker/pull/975
