### ISSUE TITLE
 Tag latest and v3.4-2.5.2 is not v3.4.8-2.5.2

### ISSUE THREAD

**Issue by Delta1977** [netbox-community/netbox-docker#986]
### Current Behavior

...

### Expected Behavior

updatet builds on dockerhub

### Docker Compose Version

...

### Docker Version

```text
.....
```

### The git Revision

...

### The git Status

```text
...
```

### Startup Command

...

### NetBox Logs

```text
...
```

### Content of docker-compose.override.yml

```yaml
...
```

**Comment by ryanmerolle** [comment]
This will be sorted in the next 2 days or so.
